### ISSUE TITLE
curl error: "SSL read: errno -5961"

### ISSUE THREAD

**Issue by marvinschroeder** [paypal/PayPal-PHP-SDK#336] opened 2015-06-25 09:56 UTC
I am getting the error "SSL read: errno -5961" when i am trying to get the infos of a payment.
Most of the time there were no errors, but in the last weeks i am getting this more and more.
In this specific call i am try to get the infos of 50 payments via a cronjob with a foreach loop.

Is there any chance to avoid the error or to get the details of a payment in batch mode?

**Comment by jaypatel512** [comment] 2015-06-25 15:32
Hey @marvinschroeder !

I am trying to see if I can reproduce this issue. Just for starters, I found few links that could be potentially causing this, but couldnt confirm based on your setup. 

- https://github.com/docker/docker/issues/2011
- https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/986147

Can you please see if you could spot any difference in the requests between a successful one and a failing one from the logs ?

**Comment by marvinschroeder** [comment] 2015-06-29 11:06
I just (manually) turned on the debugging mode on my live system to see whats failing. Most of the time where the requests "fail" is the request for the access token called about 6 times (retrys). So, i digged depper in the process of the access token and saw that every time i called the details of the 50 payments in the loop, a new access token was requested (50 payments = 50 access tokens). A few minutes ago i switched on the cache and will be getting back if i have any further results of this.

**Comment by jaypatel512** [comment] 2015-06-29 15:32
There are few security measures, that prevents you from making similar calls again and again on live servers, generally some kind of throttling mechanism. I think cache would be your best friend here, as it would let you make almost half number of calls to PayPal, making it faster. 

Also, not sure, if you are trying to get details of payments specific to something, but we do have a "List Payment" feature, that allows you to get multiple payments at a time. It may not have a lot of filters present yet, but few that could help.

Here is the developer docs: https://developer.paypal.com/webapps/developer/docs/api/#list-payment-resources
Here is the SDK sample:  http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/ListPayments.html

**Comment by jaypatel512** [comment] 2015-06-30 14:59
Closing this issue as it seems to be throttling issue. I would definitely recommend using `caching` of access token, or use List Payment features to make these batch calls. This does not seem to be an SDK issue.

**Closed by jaypatel512** 2015-06-30 14:59 UTC
Labels: question

**Comment by marvinschroeder** [comment] 2015-06-30 15:09
It could be a throttling issue. The caching of the access token was not the full solution, but i definitely get fewer errors. I try to switch to the list payment feature and will report the results here.

**Comment by jaypatel512** [comment] 2015-06-30 16:53
Please do, and for any case you still see these issues, feel free to reach back to me, and I should be able to help you further.
