### ISSUE TITLE
Trying to get payment Fee with Currency EUR

### ISSUE THREAD

**Issue by Newbie012** [paypal/PayPal-PHP-SDK#349] opened 2015-07-02 17:00 UTC
I dumped the response of the execution and the "transaction_fee" {..} is empty and there's some errors inside the response. The reason I see those errors and I don't receive the transaction_fee is it was created in sandbox?

**Paypal Response**

	{
	"id":"PAY-7HC461155B029844JKWKQICQ",
	"create_time":"2015-07-02T09:27:38Z",
	"update_time":"2015-07-02T09:27:58Z",
	"state":"approved",
	"intent":"sale",
	"payer":{
		"payment_method":"paypal",
		"payer_info":{
			"email":"XXX@XXX.com",
			"first_name":"XXX",
			"last_name":"XXX",
			"payer_id":"ZTRB28BXCJCTJ",
			"shipping_address":{
				"line1":"XXX",
				"city":"XXX",
				"state":"",
				"postal_code":"",
				"country_code":"XXX",
				"recipient_name":"XXX"
			}
		}
	},
	"transactions":[
		{
			"amount":{
				"total":"10.00",
				"currency":"EUR",
				"details":{
					"subtotal":"10.00"
				}
			},
			"description":"XXXXXX",
			"item_list":{
				"items":[
					{
						"name":"XXX",
						"price":"10.00",
						"currency":"EUR",
						"quantity":"1"
					}
				],
				"shipping_address":{
					"recipient_name":"XXX",
					"line1":"XXX",
					"city":"XXX",
					"state":"",
					"postal_code":"",
					"country_code":"XXX"
				}
			},
			"related_resources":[
				{
					"sale":{
						"id":"217224619C549403J",
						"create_time":"2015-07-02T09:27:38Z",
						"update_time":"2015-07-02T09:27:58Z",
						"amount":{
							"total":"10.00",
							"currency":"EUR"
						},
						"payment_mode":"INSTANT_TRANSFER",
						"state":"pending",
						"reason_code":"RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION",
						"protection_eligibility":"ELIGIBLE",
						"protection_eligibility_type":"ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE",
						"parent_payment":"PAY-7HC461155B029844JKWKQICQ",
						"transaction_fee":{

						},
						"links":[
							{
								"href":"https://api.sandbox.paypal.com/v1/payments/sale/217224619C549403J",
								"rel":"self",
								"method":"GET"
							},
							{
								"href":"https://api.sandbox.paypal.com/v1/payments/sale/217224619C549403J/refund",
								"rel":"refund",
								"method":"POST"
							},
							{
								"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-7HC461155B029844JKWKQICQ",
								"rel":"parent_payment",
								"method":"GET"
							}
						]
					}
				}
			]
		}
	],
	"links":[
		{
			"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-7HC461155B029844JKWKQICQ",
			"rel":"self",
			"method":"GET"
		}
	]

**Comment by Newbie012** [comment] 2015-07-02 18:45
after hours of testing, I finally understand what is the problem.
When I change the currency from EUR to USD, it worked. but the problem is still exists.. I need to know the fee in Euros and not US Dollars. my primary currency on my account is EUR. is it because of this?
What I need to do?

**Comment by jaypatel512** [comment] 2015-07-02 18:57
Possible duplicate of #344

**Comment by Newbie012** [comment] 2015-07-02 21:15
I'm not sure it's a the same issue, because my problem is that when I pay with USD, I get the fee. But I don't get fee when I pay with EUR. The other issue is when he uses credit_card method he gets an empty fee (as far as I understood).

**Comment by jaypatel512** [comment] 2015-07-02 22:46
Yes. I was able to reproduce the issue where I create a payment using EUR, and I am not receiving transaction fee. I will create an internal issue for API team to investigate further.

**Comment by Newbie012** [comment] 2015-07-03 06:54
Thanks you, @jaypatel512. How long does it take to be fixed? Because I saw on some.previous issue that it took for like a year

**Comment by Newbie012** [comment] 2015-07-03 06:55
Thanks you, @jaypatel512. How long does it take to be fixed? Because I saw on some previous issues that it took for like a year to get solved

**Comment by jaypatel512** [comment] 2015-07-04 03:52
Hey @Newbie012 !

I may not have a definite answer to that unfortunately. our team always try to push the API design teams to implement these fixes/features as soon as possible, however, we do not have a huge amount of control on their priority plannings. However, I assure you, we all wish to see these issues closed sooner.

I know that was not the answer you were hoping for, however, I will definitely make sure your feedback is shared and heard by API team.

**Comment by Newbie012** [comment] 2015-07-04 17:59
OK, so for now, how should I calculate for now the fee?

**Comment by jaypatel512** [comment] 2015-07-11 00:49
Hey @Newbie012 !

I got a response from Payments API team about your issue.

As you can see in the "Sale" object inside "related_resources", the state is mentioned as "pending", instead of "completed". It means that the sale is still in pending state, and will be set to completed, once approved. (I am trying to get more details on how it will happen, and could you automate this instantly.)

However, this means, that the currency your business account is on would accept the payment instantly if your merchant account accepts same currency. E.g. 

Merchant with EUR countries, would instantly accept any EUR payments, however, it would make the payment as "pending" on USD payments.

**Closed by jaypatel512** 2015-07-11 00:49 UTC
Labels: api-bug, api-payments

**Comment by Newbie012** [comment] 2015-07-11 17:53
The thing is, our primary currency is already EUR. The fee we pay is 0.39%
+ 0.35 EUR.
בתאריך 11 ביול 2015 03:49,‏ "Jay" <notifications@github.com> כתב:

**Comment by jaypatel512** [comment] 2015-07-11 21:54
Oh ok. In that case I think the issue is with the developer account. You might have some configuration that is stopping you from getting this processed. 

I would recommend you talking directly to [Merchant Technical Services](https://ppmts.custhelp.com/) about this issue, and they should be able to fix this right away. 

Closing this issue for now, as the issue is not API or SDK related.
