### ISSUE TITLE
Paypal SDK error

### ISSUE THREAD

**Issue by mobi35** [paypal/PayPal-PHP-SDK#1036] opened 2018-01-05 00:51 UTC
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

https://stackoverflow.com/questions/48058851/paypal-php-sdk-implementation

I post a problem regarding Paypal PHP sdk please help

**Comment by xiaoleih41** [comment] 2018-01-05 15:18
Do you have a 'debugId'? I noticed that  you posted `Use PayPal\Auth\OAuthTokenCredential;` instead of `use PayPal\Auth\OAuthTokenCredential;`. That could have been the cause of it.

**Comment by pp-randy** [comment] 2018-01-05 15:42
Your code here
```
    $details = new Details();
    $details->setShipping($tax)
    ->setSubtotal($price)
    ->setTax(2.00);
    
    $amount = new Amount();
    $amount->setCurrency('USD')
    ->setTotal($total)
    ->setDetails($product);
```

If your total is tax and price of the item, then don't set shipping.  Also amount->setDetails should be details.

```
$details = new Details();
$details->setSubtotal($price)
->setTax(2.00);

$amount = new Amount();
$amount->setCurrency('USD')
->setTotal($total)
->setDetails($details);
```

**Comment by pp-randy** [comment] 2018-01-05 15:43
Review https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing it will help getting additional details for the errors.

**Comment by pp-randy** [comment] 2018-01-08 20:56
Closing as my answer should resolve this for you.  Please let me know if you need further assistance.

**Closed by pp-randy** 2018-01-08 20:56 UTC
