### ISSUE TITLE
Where can I get the payment ID?

### ISSUE THREAD

**Issue by nyel-dev** [paypal/PayPal-PHP-SDK#1162] opened 2018-07-24 12:04 UTC
as the title says.

where can I see the payment ID on the dashboard of paypal? All I can see is transaction ID.

I am trying to do this: https://developer.paypal.com/demo/checkout/#/pattern/client

**Comment by gpcaretti** [comment] 2018-09-14 12:32
Transaction ID is the identifier of PayPal transactions **once it is completed**, regardless of which API it comes from (Classic API, REST API, Adaptive Payment API etc). It will be issued if and only if the transaction has been completed.

In contrast, Payment ID is identifier of payment in REST API which does not necessarily indicates a completed payment.

At the moment Payment ID is not visible in the dashboard, nor the transaction is accessible via an URL with it (it is accessible only via the Transaction ID. E.g. https://www.paypal.com/activity/payment/your_transaction_ID)

I absolute agree with you, PayPal should display and provide the possibility to access to the transaction via the Payment ID.

**Comment by gpcaretti** [comment] 2018-10-09 11:04
@nyel-dev  

> You mean I should not be using Payment ID as the primary identifier of successful transaction? If this is the case, what do you suggest as ID that I should use?

Exactly. Although I don't like the approach used by PayPal, this is the situation: until the payment is not confirmed, you must refer to the Transaction ID.
Once you receive the payment confirmation, you must store in your system the Payment ID, because the transaction ID is "discarded" by paypal (you have no APIs or other instrument to recover the transaction with it).
Payment ID will let you refer to the payment directly with a URI likes https://www.paypal.com/activity/payment/[payment_id].

Last, but not least: payment ID can be taken from the return value received by PayPal, once executed **sucessfully** the method. Here a C# code (similar in JS or PHP):

```
    var executedPayment = payment.Execute(apiContext, paymentExecution);
    // PaymentId ID is available here (only if the payment is completed):
    var paymentId = executedPayment.transactions[0].related_resources[0].sale.id;
```

**Comment by prakash-gangadharan** [comment] 2019-09-20 06:27
Hi @nyel-dev it looks like your query has been answered by @gpcaretti, hence closing this issue.

Thanks!

**Closed by prakash-gangadharan** 2019-09-20 06:27 UTC
Labels: question

**Comment by Mplunsford** [comment] 2020-02-11 19:20
Hi gpcaretti, 

Can you post this method in php code?

var executedPayment = payment.Execute(apiContext, paymentExecution);
    // PaymentId ID is available here (only if the payment is completed):
    var paymentId = executedPayment.transactions[0].related_resources[0].sale.id;

Thanks,

**Comment by gpcaretti** [comment] 2020-02-19 08:19
I don't use php. Just seen a couple of times in my life.

I remember it has objects as well. If so, it is only a matter of syntax.
Classes will be for sure the same.

Gianpiero

Il mar 11 feb 2020, 20:20 Mplunsford <notifications@github.com> ha scritto:

**Comment by Mplunsford** [comment] 2020-02-21 03:44
Thank you for responding. I think I found it:

<?php
$pagecode=   "$transactions = $payment->getTransactions();
$related_resources = $transactions[0]->getRelatedResources();
$sale = $related_resources[0]->getSale();
$sale_id = $sale->getId();
\n";

LOL But, I still don't have a clue about how to use it!  I'm trying to populate a field in my payment form so I have the payment ID to enter into a reference field before closing out a sale with a POS plugin that doesn't have PayPal integration.
