### ISSUE TITLE
Payouts on Sandbox (and also Live) always returns Denied status

### ISSUE THREAD

**Issue by ivanbarlog** [paypal/PayPal-PHP-SDK#220] opened 2015-01-20 08:38 UTC
Sandbox client ID: `AZDc4BAhqVdUjfvBSiLGd_ICWtMwxO322YJYwDgwPeel4TMyiW6PqtLXW5Pv`
Live client ID: `AUtztBDYAAV312gSsyvOnC0EZ4sqGQz6F2Etkalne2wsiottooTlVuQfeTMc`

[More information about this issue](http://stackoverflow.com/questions/27980541/paypal-payout-always-denied-sandbox)

**Comment by jziaja** [comment] 2015-01-20 14:28
Hi @ivanbarlog, I noticed on the StackOverflow issue you mentioned receiving an `INTERNAL_ERROR` response.  Can you share the response you're getting on Sandbox along with the included `debug_id`?  The `debug_id` will allow us to look in our logs to see exactly what is causing the error.

Also, when you authenticate with PayPal, can you verify the response you're receiving has Payouts listed as one of the scopes?  We've had some reports of developers who enable Payouts support on pre-existing REST apps and the scope for Payouts doesn't get added correctly.  Another way to verify this is to create a new REST app in your account settings and try using Payouts calls with that app.  If this is the case, I can forward your information to the API team (who is already aware of this issue) to get the scope properly added to your existing app.

**Comment by jaypatel512** [comment] 2015-01-20 15:51
Hey @jziaja I asked him to try out the sample clientId and secret, and it works, but it fails when he uses his. I think the issue is with the payout scope not getting added properly. That would be a good to know about creating new app and trying, but I am fairly certain the issue is with scoping.

**Comment by ivanbarlog** [comment] 2015-01-20 16:59
@jziaja I don't know what you mean by `debug_id` but this is message from my PayPal.log file:

```
[19-01-2015 04:08:51] PayPal\Core\PayPalHttpConnection: INFO: GET https://api.sandbox.paypal.com/v1/payments/payouts/MTRJPE9L69SP2
[19-01-2015 04:08:51] PayPal\Core\PayPalHttpConnection: FINE: Content-Type: application/json
[19-01-2015 04:08:51] PayPal\Core\PayPalHttpConnection: FINE: User-Agent: PayPalSDK/PayPal-PHP-SDK 1.0.0 (lang=PHP;v=5.5.9-1ubuntu4.5;bit=64;os=Linux_3.13.0-44-generic;machine=x86_64;openssl=1.0.1f;curl=7.35.0)
[19-01-2015 04:08:51] PayPal\Core\PayPalHttpConnection: FINE: Authorization: Bearer A015q165-ief9wnkGxXB5K9BXhIzWQna2n4rKWNhZ1abnVc
[19-01-2015 04:08:51] PayPal\Core\PayPalHttpConnection: FINE: No Request Payload

[19-01-2015 04:08:52] PayPal\Core\PayPalHttpConnection: FINE: Response : {"batch_header":{"payout_batch_id":"MTRJPE9L69SP2","batch_status":"DENIED","time_created":"2015-01-19T15:08:50Z","time_completed":"2015-01-19T15:08:51Z","sender_batch_header":{},"amount":{"currency":"EUR","value":"10.0"},"fees":{"currency":"EUR","value":"0.2"}},"items":[{"payout_item_id":"2FPFQFJNMM2E2","transaction_status":"FAILED","payout_item_fee":{"currency":"EUR","value":"0.2"},"payout_batch_id":"MTRJPE9L69SP2","payout_item":{"amount":{"currency":"EUR","value":"10.0"},"note":"message","receiver":"cockootec@gmail.com","recipient_type":"EMAIL","sender_item_id":"prefix_54bd1e01f179d"},"errors":{"name":"INTERNAL_ERROR","message":"Internal error","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_ERROR"},"links":[{"href":"https://api.sandbox.paypal.com/v1/payments/payouts-item/2FPFQFJNMM2E2","rel":"item","method":"GET"}]}],"links":[{"href":"https://api.sandbox.paypal.com/v1/payments/payouts/MTRJPE9L69SP2","rel":"self","method":"GET"}]}
```

**Comment by jaypatel512** [comment] 2015-01-20 17:15
Hey @ivanbarlog Can you make sure you have enough balance in your sandbox developer account ? This can be seen by logging into https://developer.paypal.com/webapps/developer/applications/accounts, and then clicking on your Business Pro account (generally the first one that was created), and cilck on Profile. There should be a tab named as "Funding" that should have PayPal balance at the end. 

Something like this: 

![screen shot 2015-01-20 at 11 12 23 am](https://cloud.githubusercontent.com/assets/1309895/5821963/a4d3a39a-a095-11e4-8884-6dacd30470a6.png)

**Comment by jziaja** [comment] 2015-01-20 17:15
@ivanbarlog, PayPal error responses should normally contain a [`debug_id`](https://developer.paypal.com/docs/api/#error-object), especially ones marked as `INTERNAL_ERROR`, because it allows us to quickly look in the services logs to see what exactly caused the problem.  We're following up with the Payouts API team to see if they can determine the reason why you're encountering this error and will keep you posted.

**Comment by ivanbarlog** [comment] 2015-01-20 23:28
@jaypatel512 I am trying to Payout 10 EUR + 0.2 EUR FEE and I have 500 USD in my Business account. Default account which was created by sandbox is showing error `We experienced some issues on our end while creating this Sandbox account. Please delete it and try again.` But I cannot delete it since it is default one. Unfortunately this is not the issue because Application I am using is associated with other sandbox account which has balance of funding 500 USD.

@jziaja I sent you log from one request which was returned as `denied`. I `grep`ped my `PayPal.log` file for `debug_id` but there is none. I wish I can provide such an information but PayPal sandbox never returned me one.

**Comment by jaypatel512** [comment] 2015-01-20 23:42
I have sent your client Id to our sandbox team, and they will help me look into the issue on why you are getting denied ! I will update you as soon as possible !

**Comment by jaypatel512** [comment] 2015-01-21 17:11
Hey @ivanbarlog, can you please try the payout again. The internal team mentioned us that they were re-setting some internal components, that affected payout unknowingly, and so you were getting those weird exceptions. Just wanted to confirm it was that, and not something. If it is still failing, we can dig deeper. Sorry about the confusion. Thanks for helping us out.

**Comment by ivanbarlog** [comment] 2015-01-23 09:27
Hi, finally I resolved this issue. In my sandbox I have created business account which was US located and uses `USD` as currency. In my script I was sending `EUR` currency.

I didn't know that you can't pay between different currencies - it is not mentioned anywhere. Also the error message should be more descriptive - `DENIED` or `INTERNAL ERROR` is not very helpful.

If you can respond me only one last question: Is `Payout` function available globally or only for US market? I am trying to implement `Payout` in Europe but in my developer account I have `Payouts` disabled [see picture](https://www.dropbox.com/s/6m6rqwi7q4f2hbd/account-permissions.png?dl=0).

**Comment by jaypatel512** [comment] 2015-01-23 17:54
Hey @ivanbarlog ! I completely agree that DENIED or INTERNAL ERROR is not helpful. I have raised an issue that would correct to a proper message like "INSUFFICIENT FUND" or "INSUFFICIENT FUND FOR THAT CURRENCY" or something. 

And I am not entirely sure about why the Payouts are disabled in live, however, I am not sure but the link to "Enable Live Credentials" should set it up for you. Generally, for these features you may need to provide additional information to better secure your account. However, let me know if you run into issue enabling that. I have asked Payouts team to see why your clientId is not enabled.

**Closed by jaypatel512** 2015-01-23 17:54 UTC
Labels: question

**Comment by jaypatel512** [comment] 2015-01-23 18:09
Hey @ivanbarlog ! Got an answer from our Payout Team. 

##### Availability
* Payouts is available to send from any country Mass Payments is.  So – yes it is globally available.
* However – the self-service onboarding flow is what is only available in the US.
* For a non-US account to get Payouts – they need to contact their local CS (contact us link on their home pp.com site), and request MassPayments, that’ll get the flag turned on, then they will automatically see that Payouts is enabled in the My Account area on developer.pp.com – and they are good to go.

##### Currency
* Sender must have the currency they want to send in an open balance that they have already – today it does not auto-convert USD to EUR.
* If you have USD, but want to send EUR, you must first convert USD->EUR manually and create your EUR balance.  Then you can send EUR.


That explains why your payout is not enabled by default. The web wizard flow to enable Payout in live is only supported for US merchants currently. For you, all you need to do is contact Support, and request MassPayment to be enabled, and you should be good to go.

**Comment by dli1022** [comment] 2017-02-21 18:08
Hi There, 

I'm getting "Insufficient Funds" even though I clearly have more than enough in my test account. I'm trying to create a payout for $75 with $1970 in the account. Here is my client id: AeIY3qMI04pOa_8pHmaKjITqVf2y_YeKrtaVUYN9grUiaiwWHrfMzf-VTnXZxiJNDKeMA_H0lTwtoMKa

**Comment by pp-randy** [comment] 2017-02-23 15:07
Looked into that here: https://github.com/paypal/PayPal-Ruby-SDK/issues/271
