### ISSUE TITLE
Namespace and class conflicts with sdk-core-php

### ISSUE THREAD

**Issue by jrbasso** [paypal/PayPal-PHP-SDK#264] opened 2015-03-05 02:12 UTC
This is basically the same of #131, where wasn't resolved but closed with some workaround for one specific scenario.

My company uses merchant API v3.8.107 (latest at the moment), which has core-sdk as dependency (we are using 1.5.3) and we also use the rest sdk (1.3.1). Everything installed via composer.

This makes the API to work randomly, depending which file composer user for the duplicated class.

Scanning the code we found that are just 3 classes/interfaces that are duplicated:
- `PayPal\Auth\OAuthTokenCredential`
- `PayPal\Rest\ApiContext`
- `PayPal\Rest\IResource`

Changing the namespace of these 3 classes/interfaces should solve the problem, but it will break the backward compatibility, so probably needs to be done in a major version. I would recommend to suggest on the migration guide / release notes for people to use `class_alias()` in order to not update the whole code. This is just a temporary solution for the major update, clearly it shouldn't be a definitive solution.

**Comment by jaypatel512** [comment] 2015-03-05 02:22
Hey @jrbasso !

I agree. There are few classes that are extremely hard to rename, as it causes a major breakdown. Definitely making similar changes during major version would be an ideal situation. However, that needs to be handled nicely even further. 

What we have in mind is to come up with a way to determine, if classic APIs are present alongside, it would use class_alisaing to automatically resolve such issue. However this would be a tricky undertaking, as this is something that we want to officially support to be backward compatible, as well as work with classic SDKs. 

However, from the list, 
- OAuthTokeCredential is something just used by rest, and wont be required in SDK Core anymore. 
- IResource is an interface with no methods. Its more of a structural design (which I hate, but existed before), which I will go ahead and remove in major release soon.
- ApiContext, is tricky, as it is may be used by classic SDKs. 

I think instead of making changes to REST SDK, we would deprecate and remove these classes from SDK Core or Merchant SDKs. This should reduce the number of people getting impacted by this, and if they want to make it work, they could definitely update the SDK Core, with minimum breaking change on their code.

**Comment by jaypatel512** [comment] 2015-03-06 17:00
Also, @jrbasso ! I am fairly certain, all the 3 conflicting classes are used only for REST communications. So, if you are running into this issue, the interim solution could be to delete them from SDK Core Project. I will however, go ahead and plan a release on sdk-core-php package that does not have these three files. This way, you should be able to update in future, without any issue in future.

**Comment by thomasrose** [comment] 2015-05-19 00:33
Hi, this still doesn't appear to be fixed - just "closed" with an untenable workaround. Is a fix being developed?

**Comment by jaypatel512** [comment] 2015-05-19 14:02
Reopening to figure a way out to resolve this conflict.

**Comment by jaypatel512** [comment] 2015-05-20 19:33
Hey @thomasrose ! Can you please help me assure the fix is properly handled. I have created a new release for [SDK Core PHP to 3.0.0](https://github.com/paypal/sdk-core-php/releases/tag/v3.0.0), and also updated the [namespace-5.3 branch](https://github.com/paypal/merchant-sdk-php/commit/4ccde61dd99be2604c29d3acb45749d6dafb3ce3) in merchant SDK PHP. 

- Can you please update your SDK to use `"paypal/merchant-sdk-php": "dev-namespace-php5.3"` in your composer.json and check if the latest SDK Core is downloaded, and the issue is resolved. 

I have tested this on my machine, however, I want to make sure I am not accidently breaking any backward compatibility. If it works, I will go ahead and make a major release on merchant-sdk-php with the latest sdk core update.

Thanks.

**Comment by jaypatel512** [comment] 2015-06-08 16:39
Closing this issue, as the new release should have fixed the problem. Please re-open if the issue still exists.

**Closed by jaypatel512** 2015-06-08 16:39 UTC
Labels: sdk-enhancement

**Comment by dubrox** [comment] 2015-07-17 00:49
Hi @jaypatel512 I'm having this issue of conflict with ApiContext when using the Adaptive Payments SDK together with the REST API.
The [first one has defined a dependency](https://github.com/paypal/adaptivepayments-sdk-php/blob/master/composer.json) with the version 1.5.* of the SDK Core, where the fix you made is not available.
Is it possible to update the dependency to version 3 or are those incompatible?

**Comment by handybitesize** [comment] 2015-09-08 10:30
Same issue as dubrox, on Adaptive using ApiContext. Can this 'fix' be rolled out to all classic sdks?
