### ISSUE TITLE
How to change the Credit Card of the created billing agreement

### ISSUE THREAD

**Issue by deepakkailashgupta** [paypal/PayPal-PHP-SDK#243] opened 2015-02-10 11:22 UTC
While trying to change the credit card for the existing agreement, we getting the error kindly help

[10-02-2015 03:20:17] PayPal\Core\PayPalHttpConnection: INFO    : PATCH https://api.sandbox.paypal.com/v1/payments/billing-agreements/I-EVT6R87K9T2Y
[10-02-2015 03:20:18] PayPal\Core\PayPalHttpConnection: DEBUG   : Request Headers       : PATCH /v1/payments/billing-agreements/I-EVT6R87K9T2Y HTTP/1.1, Host: api.sandbox.paypal.com, Accept: */*, Content-Type: application/json, User-Agent: PayPalSDK/PayPal-PHP-SDK 1.2.0 (lang=PHP;v=5.5.11;bit=64;os=Linux_2.6.32-431.11.2.el6.x86_64;machine=x86_64;openssl=1.0.1e-fips;curl=7.19.7), Authorization: Bearer A015DeYVtl5tzRRjFvGdO4SopPHWeOh.lfllJsvSfBSgYQQ, Content-Length: 329, ,
[10-02-2015 03:20:18] PayPal\Core\PayPalHttpConnection: DEBUG   : Request Data          : [{"op":"replace","path":"/payer/","value":{"payment_method":"credit_card","funding_instruments":[{"credit_card":{"type":"visa","number":"4xxxxxxxxx8","expire_month":1,"expire_year":"2020","billing_address":{"line1":"H 455, Buty Road, Sita buldi","city":"Nagpur","state":"Mh","postal_code":"440012","country_code":"IN"}}}]}}]
--------------------------------------------------------------------------------------------------------------------------------

[10-02-2015 03:20:18] PayPal\Core\PayPalHttpConnection: INFO    : Response Status       : 400
[10-02-2015 03:20:18] PayPal\Core\PayPalHttpConnection: DEBUG   : Response Headers      : HTTP/1.1 400 Bad Request, Server: Apache-Coyote/1.1, PROXY_SERVER_INFO: host=slcsbplatformapiserv3002.slc.paypal.com;threadId=370946, Paypal-Debug-Id: dffc241481568, SERVER_INFO: paymentsplatformserv:v1.payments.billing-agreements&CalThreadId=501214&TopLevelTxnStartTime=14b7337e5b4&Host=slcsbpaymentsplatformserv3001.slc.paypal.com&pid=22725, Content-Language: *, Date: Tue, 10 Feb 2015 11:20:18 GMT, Connection: close, Content-Type: application/json, Content-Length: 271, Connection: close, ,
[10-02-2015 03:20:18] PayPal\Core\PayPalHttpConnection: ERROR   : Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/I-EVT6R87K9T2Y. {"name":"BUSINESS_VALIDATION_ERROR","details":[{"field":"validation_error","issue":"Invalid Path provided."}],"message":"Validation Error.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#BUSINESS_VALIDATION_ERROR","debug_id":"dffc241481568"}
[10-02-2015 03:20:18] PayPal\Core\PayPalHttpConnection: DEBUG   :

**Comment by jziaja** [comment] 2015-02-10 14:27
Duplicate of #241 

This is not yet supported, unfortunately.

**Closed by jziaja** 2015-02-10 14:27 UTC

**Comment by deepakkailashgupta** [comment] 2015-02-10 17:30
yes Your are right...

I need to cancel the agreement and setup the new agreement with the same plan and update credit card details
