### ISSUE TITLE
Webhook validation broken in the sandbox

### ISSUE THREAD

**Issue by omarkilani** [paypal/PayPal-PHP-SDK#412] opened 2015-10-02 23:56 UTC
I have an issue where a webhook fires, and the sandbox returns 404 for the ID (even though it's correct):

```
[02-10-2015 11:44:36] PayPal\Core\PayPalHttpConnection: INFO    : GET https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-52K88793W20818249-2XG78528F3752401T
[02-10-2015 11:44:37] PayPal\Core\PayPalHttpConnection: DEBUG   : No Request Payload
--------------------------------------------------------------------------------------------------------------------------------

[02-10-2015 11:44:37] PayPal\Core\PayPalHttpConnection: INFO    : Response Status       : 404
[02-10-2015 11:44:37] PayPal\Core\PayPalHttpConnection: DEBUG   : Response Headers      : HTTP/1.1 404 Not Found, Date: Fri, 02 Oct 2015 23:44:36 GMT, Server: Apache, PROXY_SERVER_INFO: host=slcsbplatformapiserv3001.slc.paypal.com;threadId=73462, Paypal-Debug-Id: dc56acf7947d4, CORRELATION-ID: dc56acf7947d4, Content-Language: *, Content-Length: 78, Paypal-Debug-Id: dc56acf7947d4, Vary: Authorization, Content-Type: application/json, Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D880%26app%3Dplatformapiserv%26TIME%3D3826650966; domain=.paypal.com; path=/; Secure; HttpOnly, Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT, Connection: close, , 
[02-10-2015 11:44:37] PayPal\Core\PayPalHttpConnection: ERROR   : Got Http response code 404 when accessing https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-52K88793W20818249-2XG78528F3752401T. {"name":"INVALID_RESOURCE_ID","details":[],"message":"Resource id is invalid"}
[02-10-2015 11:44:37] PayPal\Core\PayPalHttpConnection: DEBUG   : 

================================================================================================================================
```

The webhook input starts off like this

```json
{"id":"WH-52K88793W20818249-2XG78528F3752401T","create_time":"2015-10-02T23:44:26Z","resource_type":"sale","event_type":"PAYMENT.SALE.COMPLETED"
````

Seems right to me... :)

**Comment by usubhash** [comment] 2015-10-03 18:42
The current PHP validation depends on API call as there are some limitations on certificate chain validation in PHP. It takes sometime(10-15seconds) for the event to be available in the API. 

If you try to get this event after ~10 seconds, it will be available.

**Comment by jaypatel512** [comment] 2015-10-08 21:12
Hey @omarkilani !

We were able to reproduce this issue, and are working on a fix which will allow languages without the ability to validate certificate chain to work properly. 

In the mean time, there is an intermediate fix that should help you get past this error.

When you receive a 404, back and an `InvalidArgumentException`, please return back with HTTP 503 status code. What this does is, it will let PayPal webhooks server to resend you this similar request in later time. You can optionally set [retry-after](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.37) header with 503 response.

You can read more on [how to return 503 in PHP here](http://stackoverflow.com/a/2760908/486784)

I will keep this issue open for when the final fix has been made, but for now, this should unblock you. Please let me know if you face any other issue implementing that.

**Comment by vmdumitrache** [comment] 2015-10-22 09:32
Hey @jaypatel512,

Is there any possibility that you could give me an example of how to do what you are saying? It's not very clear to me. 

Thank you very much for your help!

**Comment by Bubelbub** [comment] 2016-10-09 09:57
Same issue here. I think you, @jaypatel512 find a solution since 2015?
**In the PHP SDK there is:**

    $signatureVerification->setCertUrl("https://api.sandbox.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-a5cafa77"); // todo: this isn't going to work

I have the newest version 1.8.0 - installed by composer.

**All the time I get:**

    Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/notifications/verify-webhook-signature.

**Script:**

	$signatureVerification = new VerifyWebhookSignature();
	$signatureVerification->setAuthAlgo($head['paypal-auth-algo'][0]);
	$signatureVerification->setTransmissionId($head['paypal-transmission-id'][0]);
	$signatureVerification->setCertUrl($head['paypal-cert-url'][0]); // todo: this isn't going to work
	$signatureVerification->setWebhookId($json['resource']['id']);
	$signatureVerification->setTransmissionSig($head['paypal-transmission-sig'][0]);
	$signatureVerification->setTransmissionTime($head['paypal-transmission-time'][0]);
	
	$webhookEvent = new WebhookEvent();
	$webhookEvent->fromArray($json);
	$signatureVerification->setWebhookEvent($webhookEvent);
	$request = clone $signatureVerification;
	
	try
	{
		/** @var \PayPal\Api\VerifyWebhookSignatureResponse $output */
		$output = $signatureVerification->post($apiContext);
	}
	catch (Exception $ex)
	{
		/** @var \PayPal\Exception\PayPalConnectionException $ex */
		echo $ex->getMessage();
		exit(1);
	}

**Comment by bluk** [comment] 2016-10-10 16:02
Please try the new [Webhooks Verification API](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/notifications/ValidateWebhookEvent.php) which should help resolve this issue.

**Closed by bluk** 2016-10-10 16:02 UTC
Labels: api-bug, api-webhooks
