### ISSUE TITLE
VALIDATION_ERROR 

### ISSUE THREAD

**Issue by kcppdevelopers** [paypal/PayPal-PHP-SDK#1052] opened 2018-02-06 10:43 UTC
### General information

* SDK/Library version: 1.7.3.0
* Environment: Production
* `PayPal-Debug-ID` values: 1d461c8b64458
* Language, language version, and OS: 

### Issue description

12-19-2017 @ 16:24:31 - PayPal\Api\Payment Object
(
    [_propMap:PayPal\Common\PayPalModel:private] => Array
        (
            [experience_profile_id] => XP-CSN2-6C6Y-XUF9-7UFA
            [redirect_urls] => PayPal\Api\RedirectUrls Object
                (
                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                        (
                            [return_url] => http://nagelpilz24.com/?wc-api=WC_Gateway_PayPal_Plus_AngellEYE
                            [cancel_url] => http://nagelpilz24.com
                        )

                )

            [intent] => sale
            [payer] => PayPal\Api\Payer Object
                (
                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                        (
                            [payment_method] => paypal
                        )

                )

            [transactions] => Array
                (
                    [0] => PayPal\Api\Transaction Object
                        (
                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                (
                                    [amount] => PayPal\Api\Amount Object
                                        (
                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                    [total] => 79.40
                                                    [currency] => EUR
                                                    [details] => PayPal\Api\Details Object
                                                        (
                                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                                (
                                                                    [subtotal] => 79.40
                                                                    [tax] => 0.00
                                                                    [shipping] => 0.00
                                                                )

                                                        )

                                                )

                                        )

                                    [description] => 
                                    [item_list] => PayPal\Api\ItemList Object
                                        (
                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                    [items] => Array
                                                        (
                                                            [0] => PayPal\Api\Item Object
                                                                (
                                                                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                                        (
                                                                            [name] => PREMIUM-PAKET
                                                                            [price] => 39.70
                                                                            [currency] => EUR
                                                                            [quantity] => 1
                                                                        )

                                                                )

                                                            [1] => PayPal\Api\Item Object
                                                                (
                                                                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                                        (
                                                                            [name] => PREMIUM-PAKET
                                                                            [price] => 39.70
                                                                            [currency] => EUR
                                                                            [quantity] => 1
                                                                        )

                                                                )

                                                        )

                                                )

                                        )

                                    [related_resources] => Array
                                        (
                                        )

                                )

                        )

                )

            [id] => PAY-5WK96737LL223904DLI4SCHY
            [state] => created
            [create_time] => 2017-12-19T14:24:31Z
            [links] => Array
                (
                    [0] => PayPal\Api\Links Object
                        (
                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                (
                                    [href] => https://api.paypal.com/v1/payments/payment/PAY-5WK96737LL223904DLI4SCHY
                                    [rel] => self
                                    [method] => GET
                                )

                        )

                    [1] => PayPal\Api\Links Object
                        (
                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                (
                                    [href] => https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-9L318591YF0320711
                                    [rel] => approval_url
                                    [method] => REDIRECT
                                )

                        )

                    [2] => PayPal\Api\Links Object
                        (
                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                (
                                    [href] => https://api.paypal.com/v1/payments/payment/PAY-5WK96737LL223904DLI4SCHY/execute
                                    [rel] => execute
                                    [method] => POST
                                )

                        )

                )

        )

)

12-19-2017 @ 16:25:51 - {"name":"VALIDATION_ERROR","details":[{"field":"purchase_units[0]","issue":"Item amount must add up to specified amount subtotal (or total if amount details not specified)"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"1d461c8b64458"}

**Comment by xiaoleih41** [comment] 2018-02-06 15:20
I could not find anything related to this `debugId`. I could not reproduce the error in sandbox. Is it a production only issue? Please contact developer.paypal.com/support. The engineer there will help you with your account specific issue.

**Comment by kcppdevelopers** [comment] 2018-02-07 05:08
@xiaoleih41 yes I am getting this issue in live production side.

**Comment by kcppdevelopers** [comment] 2018-02-07 05:16
@xiaoleih41  above error is generating on client website, it's not my website.

**Comment by xiaoleih41** [comment] 2018-02-08 16:38
It looks like  you have got the success transaction from the response. I am not sure where you got this error if the success response was returned.

**Comment by xiaoleih41** [comment] 2018-02-13 15:52
@kcppdevelopers Could you please help clarify this issue or close the issue if it's solved.

**Comment by xiaoleih41** [comment] 2018-02-22 16:32
close due to inactivity.

**Closed by xiaoleih41** 2018-02-22 16:32 UTC

**Comment by hohuunhat** [comment] 2018-12-22 08:57
I'm also grappling with this problem please show me how to subdue it,
