### ISSUE TITLE
Getting a "InvalidArgumentException" thrown by PayPal\Validation\UrlValidator when optional "NotifyUrl" value is NULL in the RESPONSE from PAYPAL API

### ISSUE THREAD

**Issue by mxaddict** [paypal/PayPal-PHP-SDK#1157] opened 2018-07-20 07:22 UTC
### General information

* SDK/Library version: 1.13.0
* Environment: production
* `PayPal-Debug-ID` values: N/A
* Language, language version, and OS: PHP 7.0 Ubuntu 16.04

### Issue description

Getting a "InvalidArgumentException" thrown by PayPal\Validation\UrlValidator when optional "NotifyUrl" value is NULL in the RESPONSE from PAYPAL API

**Comment by mxaddict** [comment] 2018-07-20 07:24
Created a fix for it here #1158

**Comment by peterjk83** [comment] 2018-07-20 09:44
How can I get this fix into production if I'm using composer to manage the library dependency? Is a version update available? 

This issue has broken the paypal payment flow on our service. We need to get a fix out asap.

**Comment by srjlewis** [comment] 2018-07-20 13:48
I did something along to fix our site

```text
{
  "type": "project",
  "minimum-stability": "dev",
  "prefer-stable": true,
  "repositories": [
    {
      "type": "vcs",
      "url": "git@github.com:srjlewis/PayPal-PHP-SDK.git"
    }
  ],
  "require": {
    "paypal/rest-api-sdk-php": "dev-master"
  }
}
```

**Comment by Syndesi** [comment] 2018-07-23 10:40
Btw, why wasn't this bug covered by tests?

**Comment by prakash-gangadharan** [comment] 2019-09-14 05:27
Hi folks, this issue was also reported by Beatstars late in 2018 who is using the PHP SDK to create billing plans. The cause of the issue is, during GET call null is obtained for most of the response parameters (ex return_url, cancel_url, notify_url & state etc.,) from paypal server side when it was not set by the merchant.

The fix for this issue has been pushed to LIVE around 2nd October,2018 04:30 PM PST from paypal server side. This issue was not happening anymore. Hence closing this issue as it is no longer applicable.

**Closed by prakash-gangadharan** 2019-09-14 05:27 UTC
Labels: sdk-bug
