### ISSUE TITLE
Checkout - Order summary with fields blank

### ISSUE THREAD

**Issue by santanamic** [paypal/PayPal-PHP-SDK#753] opened 2016-12-24 02:43 UTC
I have this problem when I am about to finalize a billing contract creation within the paypal environment. As can see there is simply no price, shipping or totals
The reference code is located in PayPal-PHP-SDK / vendor / paypal / rest-api-sdk-php / sample / CreateBillingAgreementWithPayPal.php. It has not changed since I installed the PayPal SDK.

Does anyone know cause of this little problem ?

![capturar](https://cloud.githubusercontent.com/assets/18386043/21464783/96c875b4-c96f-11e6-9aa6-9bbcc1ce420b.PNG)
![capturard](https://cloud.githubusercontent.com/assets/18386043/21464784/96cb4794-c96f-11e6-8cfb-babae5918089.PNG)

### Required Information

- PHP Version: 5.5
- PayPal-PHP-SDK Version:
- Debug ID(s):

### Issue Description
> Please include as many details (logs, steps to reproduce) as you can to help us reproduce this issue faster.

**Comment by jaypatel512** [comment] 2016-12-27 18:03
Duplicate of https://github.com/paypal/PayPal-PHP-SDK/issues/149

**Closed by jaypatel512** 2016-12-27 18:03 UTC
