### ISSUE TITLE
Paypal Express payer API not returning data $paymentJson["payer"]["payer_info"]

### ISSUE THREAD

**Issue by KICKdesigns** [paypal/PayPal-PHP-SDK#320] opened 2015-06-03 19:21 UTC
The JSON return of a Paypal Express checkout using live credentials is not returning the payer's info (email, name, address). The JSON returned in Sandbox mode works fine. This only happens when switching to live mode.

I have a store thats live right now, and it's processing transactions properly, it's just not returning the proper JSON so I can save the customer's information and attach it to the order info I have on my local database. Please update on how we can get this data for the live credentials.

**Comment by jaypatel512** [comment] 2015-06-03 19:23
Can you please elaborate on what you mean by PayPal Express API ? Do you mean Payment APIs ? as shown here: https://developer.paypal.com/webapps/developer/docs/api/#create-a-payment

**Comment by KICKdesigns** [comment] 2015-06-03 19:24
Sorry. Yes, the Paypal REST API.

**Comment by jaypatel512** [comment] 2015-06-03 19:29
I am not able to reproduce the issue here. Can you please share your code snippet or something more specific ?
![screen shot 2015-06-03 at 2 28 47 pm](https://cloud.githubusercontent.com/assets/1309895/7969504/e3b7c5f2-09fc-11e5-89b0-fd1fbc50c623.png)

**Comment by KICKdesigns** [comment] 2015-06-03 19:34
Thanks for the quick reply. Here is a code snippet. Basically, the API returns proper payer data for sandbox accounts, but I have live transactions from customers that returns blank payer info for email, address, name.

$paymentJson = json_decode($payment,true);
$_POST["email"] = $paymentJson["payer"]["payer_info"]["email"];
$_POST["name"] = $paymentJson["payer"]["payer_info"]["first_name"] . " " . $paymentJson["payer"]["payer_info"]["last_name"];
$_POST["address_line1"] = $paymentJson["payer"]["payer_info"]["shipping_address"]["line1"];
$_POST["address_city"] = $paymentJson["payer"]["payer_info"]["shipping_address"]["city"];
$_POST["address_state"] = $paymentJson["payer"]["payer_info"]["shipping_address"]["state"];
$_POST["address_zip"] = $paymentJson["payer"]["payer_info"]["shipping_address"]["postal_code"];

**Comment by jaypatel512** [comment] 2015-06-03 19:44
Just to make sure, in your live transactions, you are using `paypal` as your payment method only ? Or do you pass `credit_cards` too. Because, only `paypal` payment mode would return payer info, with all the information.

**Comment by KICKdesigns** [comment] 2015-06-03 19:48
On initiating payment, the mode is set here: 
$payer->setPaymentMethod("paypal");
----
$payment = new Payment();
$payment->setIntent("sale")
    ->setPayer($payer)
    ->setRedirectUrls($redirectUrls)
    ->setTransactions(array($transaction));

**Comment by jaypatel512** [comment] 2015-06-04 03:31
Interesting. Let me se if I could get more details from internal API team who is responsible for Payments.

**Comment by ppmtscory** [comment] 2015-06-04 17:38
@KICKdesigns can you please provide a sale ID or a debug ID of a successful transaction that didn't populate any payer_info?

**Comment by jaypatel512** [comment] 2015-06-04 17:44
Btw, @KICKdesigns ! You can retreive that information by reading the logs generated by SDK. You can setup logging easily by following this, if you have not setup yet: https://github.com/paypal/PayPal-PHP-SDK/wiki/Adding-Configurations

**Comment by KICKdesigns** [comment] 2015-06-04 19:28
Thanks @jaypatel512, I'll kep that in mind. 

@ppmtscory the transaction ID is: #1P2119132X257611N
There were a few more Paypal transactions made yesterday, and the data seems to be coming through... the only other exception is Transaction ID #3NW42665PD360643A where only first name, email and address is coming through, but Last name is coming through.

**Comment by ppmtscory** [comment] 2015-06-04 20:20
@KICKdesigns for the first transaction, it appears that there was a glitch that didn't include payer_info in the Execute response.  It was, however, there in the GET call you did on the Payment ID a few seconds after the Execute.  The second transaction did have the last name populated in the response that we sent back to you.  Since the first one was a one-off disconnect between our internal systems that was corrected a couple seconds later when you did the GET call, I'm going to close this out for now.  I'm glad to hear that everything has been coming through so far since.  Please do let us know if you run into any issues again.

**Closed by ppmtscory** 2015-06-04 20:20 UTC
Labels: api-payments, question
