### ISSUE TITLE
Please help me what can I do next...

### ISSUE THREAD

**Issue by landguy423** [paypal/PayPal-PHP-SDK#1006] opened 2017-12-04 17:25 UTC
Hello, How are you?
I tried to create monthly (yearly) subscription using PayPal-PHP-SDK
**I used codebase like below:**
```
{
        $amount = 100;

        // Set billing plan definitions
        $paymentDefinition = new PaymentDefinition();
        $paymentDefinition->setName('Regular Payments')
          ->setType('REGULAR')
          ->setFrequency('Month')
          ->setFrequencyInterval('1')
          ->setCycles('0')
          ->setAmount(new Currency(array('value' => $amount, 'currency' => 'USD')));

        // Set merchant preferences
        $merchantPreferences = new MerchantPreferences();
        $merchantPreferences->setReturnUrl('http://mysite.com/subscribe/paypal_redirect')
          ->setCancelUrl('http://mysite.com/subscribe/paypal_return')
          ->setAutoBillAmount('yes')
          ->setInitialFailAmountAction('CONTINUE')
          ->setMaxFailAttempts('0');

           // Create a new billing plan
        $plan = new Plan();
        $plan->setName($plan_name)
          ->setDescription($plan_description)
          ->setType('infinite');
        $plan->setPaymentDefinitions(array($paymentDefinition));
        $plan->setMerchantPreferences($merchantPreferences);

        //create the plan
        try {
            $createdPlan = $plan->create($this->apiContext);

            try {
                $patch = new Patch();
                $value = new PayPalModel('{"state":"ACTIVE"}');
                $patch->setOp('replace')
                  ->setPath('/')
                  ->setValue($value);
                $patchRequest = new PatchRequest();
                $patchRequest->addPatch($patch);
                $createdPlan->update($patchRequest, $this->apiContext);
                $plan = Plan::get($createdPlan->getId(), $this->apiContext);

                // Output plan id
                **echo 'Plan ID:' . $plan->getId();**
            } catch (PayPal\Exception\PayPalConnectionException $ex) {
                echo $ex->getCode();
                echo $ex->getData();
                die($ex);
            } catch (Exception $ex) {
                die($ex);
            }
        } catch (PayPal\Exception\PayPalConnectionException $ex) {
            echo $ex->getCode();
            echo $ex->getData();
            die($ex);
        } catch (Exception $ex) {
            die($ex);
        }

    }
```
I successfully got PlanID (please see  echo 'Plan ID:' . $plan->getId();) but not sure what can I do next?
It doesn't redirect me to PayPal site.
Please help me what can I do next, I am on very busy situation.
Regards

**Comment by xiaoleih41** [comment] 2017-12-04 18:42
The next step will be to create a [billing agreement](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/CreateBillingAgreementWithPayPal.php) based on it. The **agreement ID** will be generated once you [execute the agreement](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/ExecuteAgreement.php)

**Comment by landguy423** [comment] 2017-12-04 20:17
Thanks for your update @xiaoleih41 
As I checked other codebase, the billing agreement code is located on paypal_redirect. am I right?
`public function paypal_redirect(){
        // Create new agreement
        $agreement = new Agreement();
        $agreement->setName('RentMerchant Monthly Subscription Agreement')
          ->setDescription('Basic Subscription')
          ->setStartDate(\Carbon\Carbon::now()->addMinutes(5)->toIso8601String());

        // Set plan id
        $plan = new Plan();
        $plan->setId($this->plan_id);
        $agreement->setPlan($plan);
        echo 'Plan ID:' . $this->plan_id;
        // Add payer type
        $payer = new Payer();
        $payer->setPaymentMethod('paypal');
        $agreement->setPayer($payer);

        try {
          // Create agreement
          $agreement = $agreement->create($this->apiContext);

          // Extract approval URL to redirect user
          $approvalUrl = $agreement->getApprovalLink();

          return redirect($approvalUrl);
        } catch (PayPal\Exception\PayPalConnectionException $ex) {
          echo $ex->getCode();
          echo $ex->getData();
          die($ex);
        } catch (Exception $ex) {
          die($ex);
        }

    }`
But seems that it function is not calling. could you help me?

**Comment by xiaoleih41** [comment] 2017-12-04 21:10
where do you call this function? I don't see it anywhere.

**Comment by landguy423** [comment] 2017-12-04 21:30
Seems that it is called from 
` $merchantPreferences->setReturnUrl('http://mysite.com/subscribe/paypal_redirect')
          ->setCancelUrl('http://mysite.com/subscribe/paypal_return')
          ->setAutoBillAmount('yes')
          ->setInitialFailAmountAction('CONTINUE')
          ->setMaxFailAttempts('0');`

Am I wrong?

**Comment by landguy423** [comment] 2017-12-05 06:40
Hi @xiaoleih41
Could you explain me more detail? 
Thanks

**Comment by xiaoleih41** [comment] 2017-12-05 20:31
I don't see it... Can you please follow our [sample](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/CreateBillingAgreementWithPayPal.php) instead? You first create a billing plan, then update the billing plan status to active then based on the the active billing plan, you create the billing agreement, you direct the buyer to the **approval_url** to login PayPal and approve, then you redirect him back to your site and execute the billing agreement.  we have all the sample code listed [here]( https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/)

**Comment by landguy423** [comment] 2017-12-06 20:02
Hi @xiaoleih41 , Thanks for your help.
Should I implement the features  step by step like this?
1. Create billing plan,
2. Update the billing plan status to active
3. Create billing aggrement
4. Redirect the buyer to the Paypal site

**Comment by landguy423** [comment] 2017-12-07 10:46
Hi @xiaoleih41
Could I use this instruction?
http://itsolutionstuff.com/post/how-to-integrate-paypal-payment-gateway-with-laravel54example.html

**Comment by xiaoleih41** [comment] 2017-12-07 15:47
I would suggest you to follow the READ.MD of the SDK and install SDK and the sample. Run the sample code successfully and make change based the the sample as the sample should walk you through all the steps.

**Comment by landguy423** [comment] 2017-12-07 17:09
Thanks @xiaoleih41 
Seems that above my urls are not for recurring payment.
Ok, I will follow the READ.MD and samples.

**Comment by landguy423** [comment] 2017-12-07 20:20
Hi @xiaoleih41 
Sorry to bothering your busy day.

I followed sample steps (CreatePlan, UpdatePlan, CreateBillingAgreementWithPayPal).
But Error (**cannot access empty property**)  is occured in below code:
$agreement = $agreement->create($apiContext);  //CreateBillingAgreementWithPayPal.php

How could I fix it?
And how to use $approvalUrl = $agreement->getApprovalLink(); //CreateBillingAgreementWithPayPal.php

Regards,

**Comment by xiaoleih41** [comment] 2017-12-07 20:54
I am not sure what had happened.  If you have run the samples as part of the SDK and it should does everything for you including printing out the request and response on the screen. the approval url should be shown in the response of CreateBillingAgreementWithPayPal.php. Your buyer goes to that URL to login PayPal and approve the agreement which should trigger the execute billing agreement file. Do you have a debugId that I can take a look at?

**Comment by landguy423** [comment] 2017-12-07 21:36
Hi @xiaoleih41 
Could you check my codebase again?
`          
        // Set billing plan definitions
        $paymentDefinition = new PaymentDefinition();
        $paymentDefinition->setName('Regular Payments')
            ->setType('REGULAR')
            ->setFrequency('Month')
            ->setFrequencyInterval('1')
            ->setCycles('0')
            ->setAmount(new Currency(array('value' => '100', 'currency' => 'USD')));

        // Set merchant preferences
        $merchantPreferences = new MerchantPreferences();
        $return_url = 'payment_status';
        $cancel_url = 'payment_status';
        $merchantPreferences->setReturnUrl($return_url)
            ->setCancelUrl($cancel_url)
            ->setAutoBillAmount('yes')
            ->setInitialFailAmountAction('CONTINUE')
            ->setMaxFailAttempts('0');

            // Create a new billing plan
        $plan = new Plan();
        $plan->setName($plan_id)
            ->setDescription($plan_name)
            ->setType('infinite');
        $plan->setPaymentDefinitions(array($paymentDefinition));
        $plan->setMerchantPreferences($merchantPreferences);

        //create the plan
        try {
            $createdPlan = $plan->create($this->apiContext);

            try {
                $patch = new Patch();
                $value = new PayPalModel('{"state":"ACTIVE"}');
                $patch->setOp('replace')
                    ->setPath('/')
                    ->setValue($value);
                $patchRequest = new PatchRequest();
                $patchRequest->addPatch($patch);
                $createdPlan->update($patchRequest, $this->apiContext);
                $plan_update = Plan::get($createdPlan->getId(), $this->apiContext);

                $new_plan = new Plan();
                $agreement = new Agreement();
                $agreement->setName('RentMerchant Agreement')
                    ->setDescription('Rentmerchant Agreement')
                    ->setStartDate($now);
                $new_plan->setId($plan_update->getId());
                $agreement->setPlan($new_plan);
                // Add Payer
                $payer = new Payer();
                $payer->setPaymentMethod('paypal');
                $agreement->setPayer($payer);
                // ### Create Agreement
                try {
                    $agreement = $agreement->create($this->$apiContext);
                    
                    // ### Get redirect url
                    $approvalUrl = $agreement->getApprovalLink();
                } catch (Exception $ex) {
                    ResultPrinter::printError("Created Billing Agreement.", "Agreement", null, $request, $ex);
                    exit(1);
                }
            } catch (PayPal\Exception\PayPalConnectionException $ex) {
                echo $ex->getCode();
                echo $ex->getData();
                die($ex);
            } catch (Exception $ex) {
                die($ex);
            }
        } catch (PayPal\Exception\PayPalConnectionException $ex) {
            echo $ex->getCode();
            echo $ex->getData();
            die($ex);
        } catch (Exception $ex) {
            die($ex);
        }
    }`

This code contains CreatePlan, **UpdatePlan and CreateBillingAgreementWithPayPal** same as sample codes you attached.

**Comment by landguy423** [comment] 2017-12-08 22:17
Hello @xiaoleih41
Could you get chance to check my codebase attached above?
Thanks

**Comment by landguy423** [comment] 2017-12-13 19:59
Hi @xiaoleih41 
Thanks for letting me know.

Yes I used name sapces like below:

use PayPal\Rest\ApiContext;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Api\Agreement;
use PayPal\Api\Payer;
use PayPal\Api\Plan;
use PayPal\Api\Patch;
use PayPal\Api\PatchRequest;
use PayPal\Api\ShippingAddress;
use PayPal\Api\ChargeModel;
use PayPal\Api\Currency;
use PayPal\Api\MerchantPreferences;
use PayPal\Api\PaymentDefinition;
use PayPal\Common\PayPalModel;

As I checked API files, it returns own result to other file so seems that it's not problem to call APIs in one file.

The occurred error is **"Cannot access empty property"**
It happened in $agreement = $agreement->create($this->$apiContext);
You can see this code from my attached codebase in above.

Thanks

**Comment by xiaoleih41** [comment] 2017-12-13 21:12
Can you give me your debugId, it will help me better understand what the issue is.

**Comment by landguy423** [comment] 2017-12-13 21:14
@xiaoleih41 
Could you let me know what is the debugId?

**Comment by landguy423** [comment] 2017-12-21 18:28
Hello @xiaoleih41 
How are you?
I am still facing the same issue.
`Cannot access empty property`.
This error is occurred when run this code $agreement=$agreement->create($apiContext).
All codes before this `$agreement=$agreement->create($apiContext)` are working properly.
Could you let me know how to fix it?

**Comment by landguy423** [comment] 2017-12-21 18:41
debugid is `ecbd41a7d414c`

**Comment by landguy423** [comment] 2017-12-21 20:49
hello @xiaoleih41

**Comment by xiaoleih41** [comment] 2017-12-22 18:14
How did you pass `start_date` and `payer`? can you attach the code again when you create the agreement. It may have some format issue.

**Comment by landguy423** [comment] 2017-12-22 18:17
Hi @xiaoleih41 
Thanks for your response.

This is my codebase.
    private $apiContext;
    public function __construct()
    {
        // setup PayPal api context
        $paypal_conf = Config::get('paypal');
        $this->apiContext = new ApiContext(new OAuthTokenCredential($paypal_conf['sandbox_client_id'], $paypal_conf['sandbox_secret']));
        $this->apiContext->setConfig($paypal_conf['settings']);
    }    


public function paypal_payment(Request $request) {
        $now = \Carbon\Carbon::now();
        // Set billing plan definitions
        $paymentDefinition = new PaymentDefinition();
        $paymentDefinition->setName('Regular Payments')
            ->setType('REGULAR')
            ->setFrequency('MONTH')
            ->setFrequencyInterval('1')
            ->setCycles('0')
            ->setAmount(new Currency(array('value' => $amount, 'currency' => 'USD')));
        
        // Set merchant preferences
        $merchantPreferences = new MerchantPreferences();
        $return_url = paypal_return';
        $cancel_url = paypal_fail';

        $merchantPreferences->setReturnUrl($return_url)
            ->setCancelUrl($cancel_url)
            ->setAutoBillAmount('yes')
            ->setInitialFailAmountAction('CONTINUE')
            ->setMaxFailAttempts('0');

            // Create a new billing plan
        $plan = new Plan();
        $plan->setName($plan_name)
            ->setDescription($plan_name)
            ->setType('infinite');
        $plan->setPaymentDefinitions(array($paymentDefinition));
        $plan->setMerchantPreferences($merchantPreferences);

        //create the plan
        try {
            $createdPlan = $plan->create($this->apiContext);
            try {
                $patch = new Patch();
                $value = new PayPalModel('{"state":"ACTIVE"}');
                $patch->setOp('replace')
                    ->setPath('/')
                    ->setValue($value);
                $patchRequest = new PatchRequest();
                $patchRequest->addPatch($patch);

                $createdPlan->update($patchRequest, $this->apiContext);
                $updatePlan = Plan::get($createdPlan->getId(), $this->apiContext);

                // Output plan id
                $agreement = new Agreement();
                $agreement->setName('RentMerchant Agreement')
                    ->setDescription('Rentmerchant Agreement')
                    ->setStartDate($now);
                
                $new_plan = new Plan();
                $new_plan->setId($updatePlan->getId());
                $agreement->setPlan($new_plan);
                // Add Payer
                $payer = new Payer();
                $payer->setPaymentMethod('paypal');
                $agreement->setPayer($payer);

                // ### Create Agreement
                try {
                    $new_agreement = $agreement->create($this->apiContext);
                    $approvalUrl = $new_agreement->getApprovalLink();
                } catch (PayPal\Exception\PayPalConnectionException $ex) {
                    echo $ex->getCode();
                    echo $ex->getData();
                    die($ex);
                }
            } catch (PayPal\Exception\PayPalConnectionException $ex) {
                echo $ex->getCode();
                echo $ex->getData();
                die($ex);
            } catch (Exception $ex) {
                die($ex);
            }
        } catch (PayPal\Exception\PayPalConnectionException $ex) {
            echo $ex->getCode();
            echo $ex->getData();
            die($ex);
        } catch (Exception $ex) {
            die($ex);
        }
    }

    public function paypal_return(Request $request) {
        if (isset($request['success']) && $request['success'] == 'true') {
            $token = $request['token'];
            $agreement = new Agreement();
          
            try {
              // Execute agreement
              $agreement->execute($token, $this->apiContext);
            } catch (PayPal\Exception\PayPalConnectionException $ex) {
              echo $ex->getCode();
              echo $ex->getData();
              die($ex);
            } catch (Exception $ex) {
              die($ex);
            }
        } else {
            echo "user canceled agreement";
        }
    }

**Comment by xiaoleih41** [comment] 2017-12-22 19:26
The `start_date` is formatted wrong. can you refer to the API documents to give it correct format? It should be something like ` "start_date": "2017-12-22T09:13:49Z",` Please chekc the definition of `status` [here](https://developer.paypal.com/docs/api/payments.billing-agreements#billing-agreements_create). you can use this [link](http://carbon.nesbot.com/docs/#api-formatting) as reference to fix the format.

**Comment by landguy423** [comment] 2017-12-22 19:26
Thanks @xiaoleih41 
Let me check it

**Comment by landguy423** [comment] 2017-12-22 19:47
Hi @xiaoleih41 
I tried but same issue

**Comment by xiaoleih41** [comment] 2017-12-22 20:20
Did you do `$now->toIso8601String()`?

**Comment by landguy423** [comment] 2017-12-22 21:08
Yes @xiaoleih41 
I used $now->toIso8601String() and $now->toW3cString(); as well.
But both are not working

**Comment by pp-randy** [comment] 2017-12-26 17:24
@landguy423 what does ` $now->toIso8601String() ` output?  Can you provide a new debug_id as well it could be a new issue causing this if the date is resolved.  

On a side note, if your Plan information does not change, you can reuse it and not need to create and activate a new plan every time.  

Just populate the id 
```
 $new_plan = new Plan();
  $new_plan->setId(EXISTING_PLAN_ID);
  $agreement->setPlan($new_plan);
```

**Comment by landguy423** [comment] 2017-12-26 17:31
@pp-randy  Thanks for your reply.
Yes, you and @xiaoleih41 are right. start_date was wrong.
I tested it using static date and it worked well.
But could you let me know how to use the current DateTime same as '2017-17-25T9:45:04Z`?
I used $now->toIso8601String() and it doesn't work.
The output of toIso8601String() is `2017-12-26T17:27:04+00:00`.
debug_id is '4004da8717872`

**Comment by pp-randy** [comment] 2018-01-04 15:19
@landguy423 did you get this working with Carbon?  It appears to support escape characters in its format function so you could toss in `\\T` and `\\Z` if you need to ` Y-m-d\\TH:i:s\\Z`.

**Comment by landguy423** [comment] 2018-01-05 06:29
Hi @pp-randy 
I tried like that but it doesn't work

**Comment by pp-randy** [comment] 2018-01-05 14:47
What date string did that produce?  Can you provide the error response you are getting now?

**Comment by landguy423** [comment] 2018-01-05 15:40
Hi @pp-randy 
I tried like this:
\Carbon\Carbon::now()->format('Y-m-d\\TH:i:s\\Z')
and the result of Date is '2018-01-05T15:36:15Z'.
The occurred error is 400 and debug id is 3b4ddcc4a915b

**Comment by pp-randy** [comment] 2018-01-05 15:56
The format looks good, can you add the output shown here for the exception details?

https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing#understand-your-errors

**Comment by pp-randy** [comment] 2018-01-05 15:58
Start Date needs to be in the future, most likely that is the error we are seeing now, but lets confirm.

**Comment by landguy423** [comment] 2018-01-05 16:02
When I use start Date like below it works well.
date = \Carbo\Carbon::tomorrow()->format('Y-m-d').'T0:00:00Z'
But I think it's not correct because Date is not current time and payment will run tomorrow.

**Comment by pp-randy** [comment] 2018-01-05 16:25
If you need a payment today look over `setup_fee`  https://developer.paypal.com/docs/api/payments.billing-plans#definition-merchant_preferences.

**Comment by xiaoleih41** [comment] 2018-01-12 21:10
Close this issue as the answer has been given.

**Closed by xiaoleih41** 2018-01-12 21:10 UTC
