### ISSUE TITLE
Error in Create Billing Plan - NotifyUrl is not a fully qualified URL

### ISSUE THREAD

**Issue by engrsandeep** [paypal/PayPal-PHP-SDK#1184] opened 2018-09-07 17:50 UTC
We are trying to crate billing plan and getting error "NotifyUrl is not a fully qualified URL"

I also tried to supply it then also got issue.

object(InvalidArgumentException)#55 (7) {
  ["message":protected]=>
  string(38) "NotifyUrl is not a fully qualified URL"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(115) "/home/ior/public_html/application/third_party/vendor/paypal/rest-api-sdk-php/lib/PayPal/Validation/UrlValidator.php"
  ["line":protected]=>
  int(23)
  ["trace":"Exception":private]=>
  array(13) {
    [0]=>
    array(6) {
      ["file"]=>
      string(115) "/home/ior/public_html/application/third_party/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/MerchantPreferences.php"
      ["line"]=>
      int(131)
      ["function"]=>
      string(8) "validate"
      ["class"]=>
      string(30) "PayPal\Validation\UrlValidator"
      ["type"]=>
      string(2) "::"
      ["args"]=>
      array(2) {
        [0]=>
        NULL
        [1]=>
        string(9) "NotifyUrl"
      }
    }
    [1]=>
    array(6) {
      ["file"]=>
      string(110) "/home/ior/public_html/application/third_party/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalModel.php"
      ["line"]=>
      int(256)
      ["function"]=>
      string(12) "setNotifyUrl"
      ["class"]=>
      string(30) "PayPal\Api\MerchantPreferences"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        NULL
      }
    }
    [2]=>
    array(6) {
      ["file"]=>
      string(110) "/home/ior/public_html/application/third_party/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalModel.php"
      ["line"]=>
      int(244)
      ["function"]=>
      string(11) "assignValue"
      ["class"]=>
      string(25) "PayPal\Common\PayPalModel"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(2) {
        [0]=>
        string(10) "notify_url"
        [1]=>
        NULL
      }
    }
    [3]=>
    array(6) {
      ["file"]=>
      string(110) "/home/ior/public_html/application/third_party/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalModel.php"
      ["line"]=>
      int(223)
      ["function"]=>
      string(9) "fromArray"
      ["class"]=>
      string(25) "PayPal\Common\PayPalModel"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        array(11) {
          ["setup_fee"]=>
          array(2) {
            ["currency"]=>
            string(3) "GBP"
            ["value"]=>
            string(4) "58.8"
          }
          ["max_fail_attempts"]=>
          string(1) "1"
          ["return_url"]=>
          string(38) "https://ior.org/checkout/complete/1305"
          ["cancel_url"]=>
          string(36) "https://ior.org/checkout/cancel/1305"
          ["notify_url"]=>
          NULL
          ["id"]=>
          NULL
          ["state"]=>
          NULL
          ["auto_bill_amount"]=>
          string(3) "YES"
          ["initial_fail_amount_action"]=>
          string(6) "CANCEL"
          ["accepted_payment_type"]=>
          NULL
          ["char_set"]=>
          NULL
        }
      }
    }

**Comment by Omegatcu** [comment] 2018-09-08 20:44
Have this as well - If I add a Notify URL it gives back a bad status code and if I don't set it I get an error because it is not in there...

**Comment by Neokyuubi** [comment] 2018-09-08 22:43
I faced the same problem, and if i'm not mistaken this is Validation Problem with in the SDK (please correct me if i'm wrong).
Assuming it's an SDK problem, i did change a bit the function setNotifyUrl in the file lib\PayPal\Api\MerchantPreferences.php from:

```
UrlValidator::validate($notify_url, "NotifyUrl");
$this->notify_url = $notify_url;
return $this;
```

to:

```
if(!empty($notify_url))
{
    UrlValidator::validate($notify_url, "NotifyUrl");
}
$this->notify_url = $notify_url;
return $this;
```

This will work if you don't set notifyUrl, since usually the webhooks take care of this kind of stuff (in my case).
I hope there will be some update about this part in the future.

**Comment by andrewchart** [comment] 2018-09-08 22:45
I believe this is the same issue as [#1152](https://github.com/paypal/PayPal-PHP-SDK/pull/1152)

There are some short term suggestions there until Paypal merge the solution.

**Comment by Krishnankk** [comment] 2018-09-22 06:58
I have just fixed this issue by editing urlvalidator.php and MerchantPreferences.php
check this out. 
https://www.paypal-community.com/t5/REST-APIs/NotifyUrl-is-not-a-fully-qualified-URL/m-p/1555143#M237

**Comment by prakash-gangadharan** [comment] 2019-09-14 05:35
Hi folks, this issue was also reported by Beatstars late in 2018 who is using the PHP SDK to create billing plans. The cause of the issue is, during GET call null is obtained for most of the response parameters (ex return_url, cancel_url, notify_url & state etc.,) from paypal server side when it was not set by the merchant.

The fix for this issue has been pushed to LIVE around 2nd October,2018 04:30 PM PST from paypal server side. This issue was not happening anymore. Hence closing this issue as it is no longer applicable.

**Closed by prakash-gangadharan** 2019-09-14 05:35 UTC
Labels: sdk-bug
