### ISSUE TITLE
Incorrect JSON data

### ISSUE THREAD

**Issue by fredeastside** [paypal/PayPal-PHP-SDK#541] opened 2016-04-06 14:20 UTC
Hi,
in log file I get response with this incorrect json data (It contains "on" and "\n"), for example :
```
[06-04-2016 05:08:16] PayPal\Core\PayPalHttpConnection: DEBUG	: Response Data 	: on

{"id":"PAY-59F93447LJ941144TK4CRQVA","intent":"sale","state":"created","payer":{"payment_method":"paypal"},"transactions":[{"amount":{"total":"15800.00","currency":"RUB","details":{"subtotal":"15800.00","shipping":"0.00"}},"description":"Payment description","invoice_number":"889","item_list":{"items":[{"name":"510&#8482; Skinny Fit Jeans","sku":"0","price":"7900.00","currency":"RUB","quantity":1},{"name":"Джинсы 721 High Rise Skinny","sku":"1","price":"7900.00","currency":"RUB","quantity":1},{"name":"Discount","sku":"2","price":"0.00","currency":"RUB","quantity":1}]},"related_resources":[]}],"create_time":"2016-04-06T14:08:20Z","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-59F93447LJ941144TK4CRQVA","rel":"self","method":"GET"},{"href":"https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-4MJ33818AV584483B","rel":"approval_url","method":"REDIRECT"},{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-59F93447LJ941144TK4CRQVA/execute","rel":"execute","method":"POST"}]}
```

In file "rest-api-sdk-php/lib/PayPal/Common/PayPalModel.php"
line 266
method
```
public function fromJson($json)
    {
        return $this->fromArray(json_decode($json, true));
    }
```

Here json_decode return false,
and json_last_error return JSON_ERROR_SYNTAX

**Comment by ppmtscory** [comment] 2016-04-06 15:50
Is this from a create payment call?  Let me know which call you are doing so that I can try to replicate to see what may be happening.

**Comment by fredeastside** [comment] 2016-04-07 05:16
I use this http://paypal.github.io/PayPal-PHP-SDK/

and call this method for create payment (rest-api-sdk-php/lib/PayPal/Api/Payment.php line:569)
```
public function create($apiContext = null, $restCall = null)
    {
        $payLoad = $this->toJSON();
        $json = self::executeCall(
            "/v1/payments/payment",
            "POST",
            $payLoad,
            null,
            $apiContext,
            $restCall
        );
        $this->fromJson($json);
        return $this;
    }
```

My $apiContext is:

```
PayPal\Rest\ApiContext Object ( [requestId:PayPal\Rest\ApiContext:private] => [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object ( [logger:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Core\PayPalLoggingManager Object ( [loggerName:PayPal\Core\PayPalLoggingManager:private] => PayPal\Auth\OAuthTokenCredential [isLoggingEnabled:PayPal\Core\PayPalLoggingManager:private] => [loggingLevel:PayPal\Core\PayPalLoggingManager:private] => [loggerFile:PayPal\Core\PayPalLoggingManager:private] => ) [clientId:PayPal\Auth\OAuthTokenCredential:private] => AfbaD_bVuqiStGXRpkKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXMkS-c73pBel6bDK [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EI51XhXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXwUDT-AudLwr [accessToken:PayPal\Auth\OAuthTokenCredential:private] => [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object ( [secretKey:PayPal\Security\Cipher:private] => EI51XhXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXDT-AudLwr ) [_propMap:PayPal\Common\PayPalModel:private] => Array ( ) ) )
```
$payLoad after this ```$payLoad = $this->toJSON();``` is:

```
{"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://xxxxxxxxxx.com/checkout/?ORDER_ID=889&guid=8ab6a450-f6de-4a1b-ad28-1daa20f1ad55&fast=false&success=true","cancel_url":"http://xxxxxxxxxxx.com/checkout/?ORDER_ID=889&guid=8ab6a450-f6de-4a1b-ad28-1daa20f1ad55&fast=false&success=false"},"transactions":[{"amount":{"currency":"RUB","total":"15800.00","details":{"shipping":"0.00","subtotal":"15800"}},"item_list":{"items":[{"name":"510™ Skinny Fit Jeans","currency":"RUB","quantity":1,"sku":0,"price":"7900"},{"name":"\u0414\u0436\u0438\u043d\u0441\u044b 721 High Rise Skinny","currency":"RUB","quantity":1,"sku":1,"price":"7900"},{"name":"Discount","currency":"RUB","quantity":1,"sku":2,"price":"0"}]},"description":"Payment description","invoice_number":"889"}]}
```

And json response is
```
on {"id":"PAY-2E31320457244924BK4C6WKY","intent":"sale","state":"created","payer":{"payment_method":"paypal"},"transactions":[{"amount":{"total":"15800.00","currency":"RUB","details":{"subtotal":"15800.00","shipping":"0.00"}},"description":"Payment description","invoice_number":"889","item_list":{"items":[{"name":"510™ Skinny Fit Jeans","sku":"0","price":"7900.00","currency":"RUB","quantity":1},{"name":"Джинсы 721 High Rise Skinny","sku":"1","price":"7900.00","currency":"RUB","quantity":1},{"name":"Discount","sku":"2","price":"0.00","currency":"RUB","quantity":1}]},"related_resources":[]}],"create_time":"2016-04-07T05:07:55Z","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-2E31320457244924BK4C6WKY","rel":"self","method":"GET"},{"href":"https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-2PL92496SG822071A","rel":"approval_url","method":"REDIRECT"},{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-2E31320457244924BK4C6WKY/execute","rel":"execute","method":"POST"}]}
```

**Comment by Newman101** [comment] 2016-04-07 15:46
Usually ```JSON_ERROR_SYNTAX``` means that the JSON is malformed. I validated ```$payLoad```, and noticed that the JSON is valid.  

How ever: one thing I noticed was that some of the numbers are being passed on as strings? Another thing worth checking is the utf-8 encoded trademark (510&#8482), which might cause issues is your system is not configured to handle utf-8 special characters properly.

I hope this helps.

**Comment by ppmtscory** [comment] 2016-04-07 17:31
Closing as I don't believe this is an issue with the SDK.  I'm not able to reproduce with the samples, even with passing the trademark symbol.  As @Newman101 suggested, I'd recommend checking your system setup and also try with no special characters at all and see if you get the same response.  Below is what I get with the samples.
`PayPal\Core\PayPalHttpConnection: DEBUG	: Response Data 	: {"id":"PAY-2J54179115194990HK4DJPHA","intent":"sale","state":"approved","cart":"9U6078723V9195220","payer":{"payment_method":"paypal","status":"VERIFIED","payer_info":{"email":"co..................`

**Closed by ppmtscory** 2016-04-07 17:31 UTC
Labels: question

**Comment by fredeastside** [comment] 2016-04-08 07:15
This happens because I send this:
```
"\u0414\u0436\u0438\u043d\u0441\u044b 721 High Rise Skinny"
```

It is word in cyrillic. json_encode function coding multibyte symbols Unicode like **\uXXXX**

Without
```
\u0414\u0436\u0438\u043d\u0441\u044b 
```
response json is correct

Settings in profile:
site language: Russian,
charset: UTF-8
