### ISSUE TITLE
Payer not available from invoice payments paid through PayPal?

### ISSUE THREAD

**Issue by vbenny** [paypal/PayPal-PHP-SDK#310] opened 2015-05-18 04:47 UTC
I've been trying to get basic payer information on invoices that have been paid through PayPal, and I don't think the information is available due to an API (or possibly SDK) bug. From my interpretation of the object model, the way to do get payer information from an invoice should be to link from Invoice -> PaymentDetails-> [Capture, Authorization, or Sale] -> Payment (via parent_payment) -> Payer. The best I can figure is that there's a missing parent_payment field in capture/authorization/order objects.

Here's what I've done so far on an invoice payment paid through PayPal (replicated many times in the sandbox and with similar data queried from live environment):
1) Taken an Invoice object, and gotten the transaction ID listed in the associated PaymentDetails.(of type "sale").
2) Taken that transaction ID, and retrieved the associated Capture, Authorization, and Order objects - there were no Sale or Payment objects associated with that transaction ID. The Capture and Authorization objects had no parent_payment HATEOAS link or attribute. The Order object had a parent_payment HATEOAS link of null, and no parent_payment attribute.

Invoice creation and payment workflow:
1) Use the PHP SDK to generate an invoice OR create an invoice through PayPal.
2) Pay using a PayPal account (or an e-check through PayPal).

Here's samples of most of the objects involved.

PaymentDetails: 
```
{
    "type": "PAYPAL",
    "transaction_id": "47K914790U8642731",
    "transaction_type": "SALE",
    "method": "PAYPAL",
    "date": "2015-05-17 16:54:49 PDT"
}
```

Capture (with a get based on transaction_id from PaymentDetails):
```
{
    "id": "1DD24300VN443742U",
    "create_time": "2015-05-17T23:54:49Z",
    "amount": {
        "total": "135.00",
        "currency": "USD"
    },
    "state": "completed",
    "invoice_number": "INV2-K43Y-4SQ9-3A7W-D5V4",
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/capture/1DD24300VN443742U",
            "rel": "self",
            "method": "GET"
        },
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/capture/1DD24300VN443742U/refund",
            "rel": "refund",
            "method": "POST"
        }
    ]
}
```

Authorization (with a get based on transaction_id from PaymentDetails):
```
{
    "id": "1DD24300VN443742U",
    "create_time": "2015-05-17T23:54:49Z",
    "state": "completed",
    "valid_until": "2015-06-15T23:54:49Z",
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/authorization/1DD24300VN443742U",
            "rel": "self",
            "method": "GET"
        },
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/authorization/1DD24300VN443742U/capture",
            "rel": "capture",
            "method": "POST"
        },
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/authorization/1DD24300VN443742U/void",
            "rel": "void",
            "method": "POST"
        },
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/authorization/1DD24300VN443742U/reauthorize",
            "rel": "reauthorize",
            "method": "POST"
        }
    ]
}
```

Order (with a get based on transaction_id from PaymentDetails):
```
{
    "id": "1DD24300VN443742U",
    "create_time": "2015-05-17T23:54:49Z",
    "state": "completed",
    "amount": {
        "total": "135.00",
        "currency": "USD",
        "details": {
            "subtotal": "135.00"
        }
    },
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/orders/1DD24300VN443742U",
            "rel": "self",
            "method": "GET"
        },
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/payment/null",
            "rel": "parent_payment",
            "method": "GET"
        }
    ]
}
```

GET requests of Sale and Payment objects with either the PaymentDetails transaction_id returned an 404 response. Note the null parent payment in the order record, and the lack of parent_payment links or attributes in the captures and authorizations.

Am I missing something in the data model? Or is there really something wrong with the lack of parent_payment links in the API? Any help would be greatly, greatly appreciated!

**Comment by jaypatel512** [comment] 2015-05-18 20:41
Hey @vbenny ! 

I am able to reproduce the issue you are seeing. The issue is not on the SDK, but on the API itself. I have created an internal ticket to Payments/Invoicing Team to figure out why is that the case. Thank you so much for such a detailed information. Really helps us determine the issue.

**Comment by jaypatel512** [comment] 2015-08-18 20:20
Hey @vbenny ! 

From the internal team, we got more details on this issue. 

> The Payment APIs documented here: https://developer.paypal.com/webapps/developer/docs/api/ only work if the payments were made thru these APIs. In your case the Payment is made on an invoice thru a different API, and not the APIs documented here.

Closing the issue, as this would be a new improvement on API end, and not SDK. Please reach out to [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) for any API specific issues. They would be able to help you much faster, as they have the ability to impact feature prioritization.

**Closed by jaypatel512** 2015-08-18 20:20 UTC
Labels: api-bug, api-invoicing, api-payments

**Comment by vbenny** [comment] 2015-08-19 12:33
Hi @jaypatel512,

Thanks for your response - I appreciate your help and follow-up! I can certainly see how it's not an SDK issue. I'll see what I can do by contacting MTS.

**Comment by jaypatel512** [comment] 2015-08-19 15:41
Thanks for understanding @vbenny !
