### ISSUE TITLE
Question about Billing agreements 

### ISSUE THREAD

**Issue by JCarlosR** [paypal/PayPal-PHP-SDK#960] opened 2017-10-27 02:35 UTC
### General information

* PHP SDK version: 1.12.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
![image](https://user-images.githubusercontent.com/3101238/32084748-90ee9192-ba90-11e7-9b1e-ae94d98c2b72.png)
* Language version: PHP 7.0.10 (Laravel 5.4.36)

### Issue description

- I have created a billing plan (`P-5CG897082G574680RLISL7CQ`).
- My app creates a new agreement and redirects the user to Paypal (to approve the agreement).
- My doubts are related to the agreement execution.
___
Question 1: 
[Here](https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/#execute-billing-agreement), the sample code uses a `success` parameter. However, when the user approves the agreement, the redirect is performed to `http://localhost.com:8000/paypal/return?token=EC-2PL071170B629453H` (in my case).
**It means that the `success` parameter is not used anymore and the docs have to be updated?**
___
Question 2:
I am using the following lines to create a new subscription after the agreement is successfully created.
```
$token = $request->input('token');
$agreement = new Agreement();

try {
  // Execute agreement
  $agreement->execute($token, $this->apiContext);

  $subscription = new Subscription();
  // [...]
  $subscription->paypal_agreement_id = $agreement->getId();
  $subscription->save();
} catch (PayPalConnectionException $ex) {
  echo $ex->getCode();
  echo $ex->getData();
  die($ex);
} catch (Exception $ex) {
  die($ex);
}
```
It works and the subscription is created in my db. 
However, if I refresh the page, the token can be reused. It still works and none exceptions are thrown.
The `execute` method "accepts" the same token several items.
**I will redirect the user to a different page, but is it a bug?**
___
Question 3:
I have used 2 different sandbox accounts to approve their agreements respectively. 
However, when I enter to the sandbox page, **the credit is still the same, am I doing something wrong?**
___
Question 4:
Considering the question 2, I guess I should use the `BILLING.SUBSCRIPTION.CREATED` event and define a webhook listener to be notified just once after a subscription is created.
But **the sandbox page allows to the sandbox accounts to cancel, suspend and/or reactivate a subscription? Or these events can only occur when my app uses the API to perform these operations?**
___
Question 5:
The Paypal site where the user is redirected shows fields about shipping address.
I want to avoid that, because my app doesn't require that information.
For that, [I have to create a web profile](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payment-experience/CreateWebProfile.html) and use that with the recurring payments?
___
Question 6:
I have 2 business accounts, which one will receive the payments in the sandbox mode?

Sorry for post a lot of questions, and thank you in advance.
I am implementing the recurring payments for a first time.

**Comment by xiaoleih41** [comment] 2017-10-27 19:55
Q1: I saw it by running the SDK sample code. `success=true` is a part of URL. 
Q2: Once the customer approve the agreement, and you execute the EC token and completed the payment, you should not be able re-use the EC token. In my situation I was not able to reproduce another agreement by running  the [sample code](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/ExecuteAgreement.php) Please provide `dBugId` . 
Q3: Please elaborate what you mean by credit and provide examples. 
Q4: Buyer can cancel the subscription from his account. The rest operation should be done through APIs. 
Q5: Web experience profile is not supported in Billing agreement at this time. Please see the issue here https://github.com/paypal/PayPal-REST-API-issues/issues/4
Q6 You will need to log in developer.paypal.com dashboard and create a sandbox business account under **my account**.  You can make up an email address whatever you what. You don't have to use real email address. 

If Q5 is a critical feature for you, I would encourage you to look in [Expresscheckout via Braintree SDK](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) or [Braintree Direct](https://developers.braintreepayments.com/guides/paypal/overview/javascript/v3) PayPal option. instead.

**Comment by JCarlosR** [comment] 2017-10-28 00:37
@xiaoleih41  Thank you for your help.

Q1: If I don't get the success=true parameter, it means that the agreement is not being executed?
When I was redirected from Paypal to my app, the route only got the token parameter. However the subscriptions were executed (see the next notifications):
![image](https://user-images.githubusercontent.com/3101238/32128366-b39c76f2-bb42-11e7-96f2-324f0172c7bc.png)

Q2: I have posted an image before (issue description). 
In my Sandbox API Call History, the column Paypal Debug Id is empty :(

Q3: I mean that the balance of the buyers was not updated. But now I have checked it again and the transfer is registered now.
When I created the agreement I added 5 minutes to the start date. I did that because I got errors trying to use the exact datetime.
**There is a way to leave blank the start date and let Paypal to set the proper dateTime immediately after the user aproval?**
When the user is redirected to my app I want to execute the agreement and know if the billing was procesed successfully at that moment.

Q4: Ok. Then I will allow the users to suspend/reactivate its subscription. Because if they cancel and create a new one, they will be charged twice.
But my concern is, **if I set a delay to the start date of 5 minutes, when the user approves the agreement, he/she has to wait 1 or 2 minutes in my app for the subscription activation?**

Q5: Okay. It is important because the shipping address is useless for the majority of SaaS.

Q6: Really I have 4 sandbox accounts, but I have 2 business accounts, then I don't know which will be used to receive the payments. Where I can define that?

Unfortunately Braintree is not available for my country (Peru) :/

Thanks again.

**Comment by xiaoleih41** [comment] 2017-10-30 20:03
q1 and q2. I am not sure why it is not in the URL. I would strongly recommend you to  use our sample code instead.
Q3 and Q4: Use setup_fee instead. It will charge instantly. 
Q6: The one making the API call should be the one receiving the payments.

**Comment by JCarlosR** [comment] 2017-10-30 22:07
- Very strange, because I am using the sample code. Have you tried with the 1.12.0 sdk version?

-  I guess that `setup_fee` doesn't count as the first payment of the subscription. There is no way to start the subscription immediately after the user approval?

- What do you mean? The API call is associated with my app credentials, but doesn't with the sandbox accounts as I have seen.

Thanks.

**Comment by xiaoleih41** [comment] 2017-11-03 19:49
You define the `success=true` in the billing plan return URL [here](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/billing/CreatePlan.php#L50)
You can set the setup_fee the same amount as the the first payment and it should be count as the first payment of the subscription. 
The APP has to be created from one sandbox account.  If you log into developer.paypal.com and click the app, it will tell you which sandbox account it is created under.

**Comment by JCarlosR** [comment] 2017-11-04 19:44
I am using the ISO 8601 format for the start_date (when creating a new agreement):
![image](https://user-images.githubusercontent.com/3101238/32408828-7aead2c8-c16d-11e7-8b0f-28f43a1d7c0e.png)

After create the agreement, I get the paypal approval link and redirect the user to that link.
When the user has approved the agreement I get the next object:
![image](https://user-images.githubusercontent.com/3101238/32408789-e1ca6108-c16c-11e7-95ff-c1a81726718d.png)
Here, **the start_date has a different value**. Why?

In the Sandbox API Call History I can see the next:
![image](https://user-images.githubusercontent.com/3101238/32408806-2604c32c-c16d-11e7-8c9b-7297744e6435.png)
There are two warning icons (cut in half), but I can't see the warning messages.
The icons are cut in Chrome but also in Firefox, and **I can't see the DebugID** that you ask for before.

Thank you again, for your help.

**Comment by pp-randy** [comment] 2017-11-06 15:05
@JCarlosR this issue will explain the `start_date` behavior you are seeing https://github.com/paypal/PayPal-Java-SDK/issues/207#issuecomment-255794267.  This is also documented  https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_create_request

**Comment by pp-randy** [comment] 2017-11-10 16:01
Closing for now, let us know if you have further questions.

**Closed by pp-randy** 2017-11-10 16:01 UTC

**Comment by JCarlosR** [comment] 2017-11-12 05:04
@pp-randy Is it possible to know if the first payment was processed successfully immediately? I mean, after the user approves the agreement?

@xiaoleih41 Told me to use a `setup_fee` with the same value of the subscription. Is it a not documented trick?

The documentation says "The agreement can take up to 24 hours to activate". Therefore, there is no way to check if the first payment was processed at the moment of the user approval because the operation will be delayed?

Thank you.

**Comment by pp-randy** [comment] 2017-11-13 14:44
@xiaoleih41 is correct about the `setup_fee` and it is documented here: [payments.billing-plans#definition-merchant_preferences](https://developer.paypal.com/docs/api/payments.billing-plans#definition-merchant_preferences).  It can be used with `initial_fail_amount_action` as well.   The `setup_fee` transaction should be relatively soon and does not follow the 24 hour rule, that is why you can use it for same day billing when its needed.

**Comment by JCarlosR** [comment] 2017-11-19 15:23
Is the following correct?

- No setup fee: A user approves an agreement, and the first payment is processed in the next 24 hours. The second payment will occur in the next month (based on the frequency of the plan).

- Using a setup fee with the same amount of the subscription price: A user approves an agreement, and the first payment happens immediately. When the agreement is executed, the response tells to my app if the charge was performed (don't need to listen a webhook for validate the first successful payment, only for future cancels).

Is that right?

**Comment by xiaoleih41** [comment] 2017-11-21 17:47
@JCarlosR  The first payment should start at the start date in both situations following the 24 hours rule. 
You should get the payment complete webhook for the setup fee payment as well.
