### ISSUE TITLE
Method PayPal\Api\Payment::getBillingPlanUnits() does not exist

### ISSUE THREAD

**Issue by gmoigneu** [paypal/PayPal-PHP-SDK#694] opened 2016-10-17 06:45 UTC
Version: v0.15.1

`ReflectionException in PPReflectionUtil.php line 73:
Method PayPal\Api\Payment::getBillingPlanUnits() does not exist`

When trying to get a one-time payment details, the JSON sends back the property:
`"billing_plan_units":[{"billing_plan_approved":false}]`

My payment is not configured to match a billing plan or an agreement. Just a classic one-time sale.

Any idea to avoid this error ? Here is the full JSON:

```
{  
   "payment_method":"paypal",
   "status":"VERIFIED",
   "payer_info":{  
      "email":"---@---.com",
      "first_name":"test",
      "last_name":"buyer",
      "payer_id":"DR39XRLFRHPZA",
      "shipping_address":{  
         "recipient_name":"test buyer",
         "line1":"Av. de la Pelouse, 87648672 Mayet",
         "city":"Paris",
         "state":"Alsace",
         "postal_code":"75002",
         "country_code":"FR"
      },
      "country_code":"FR"
   }
},
"transactions":[  
   {  
      "amount":{  
         "total":"45.00",
         "currency":"EUR"
      },
      "payee":{  
         "email":"---@---.com"
      },
      "description":"Credits for ---",
      "item_list":{  
         "items":[  
            {  
               "name":"10 Credits Pack",
               "sku":"C10",
               "price":"45.00",
               "currency":"EUR",
               "quantity":1
            }
         ],
         "shipping_address":{  
            "recipient_name":"test buyer",
            "line1":"Av. de la Pelouse, 87648672 Mayet",
            "city":"Paris",
            "state":"Alsace",
            "postal_code":"75002",
            "country_code":"FR"
         }
      },
      "related_resources":[  

      ]
   }
],
"billing_plan_units":[  
   {  
      "billing_plan_approved":false
   }
],
"redirect_urls":{  
   "return_url":"http://---/credits/done?paymentId=PAY-74962478YA923923BLACG55Q",
   "cancel_url":"http://---/credits/cancel"
},
"create_time":"2016-10-17T06:25:58Z",
"update_time":"2016-10-17T06:37:44Z",
"links":[  
   {  
      "href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-74962478YA923923BLACG55Q",
      "rel":"self",
      "method":"GET"
   },
   {  
      "href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-74962478YA923923BLACG55Q/execute",
      "rel":"execute",
      "method":"POST"
   },
   {  
      "href":"https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-6YG76095BJ046333K",
      "rel":"approval_url",
      "method":"REDIRECT"
   }
]
}
```

**Comment by bluk** [comment] 2016-10-17 22:32
I've opened PPPLPAYPT-13792 to track this internally.

**Comment by jaypatel512** [comment] 2016-10-17 22:41
Hey @gmoigneu !

Can you please update the SDK to latest version. It has the fix which includes removing the warning /error it throws on missing getter setters in future. 

If for any reason you cannot update to latest, please add/update your configuration `validation.level=strict` to `disable`. Refer to sample [sdk_config.ini](https://github.com/paypal/PayPal-PHP-SDK/blob/v0.15.1/sample/sdk_config.ini#L44) or [Code based configuration](https://github.com/paypal/PayPal-PHP-SDK/blob/v0.15.1/sample/bootstrap.php#L71).

**Comment by jaypatel512** [comment] 2016-10-17 22:42
Duplicate of https://github.com/paypal/PayPal-Ruby-SDK/pull/214. Please refer to conversation there.

**Closed by jaypatel512** 2016-10-17 22:41 UTC
Labels: api-bug
