### ISSUE TITLE
Refunds : response code 400

### ISSUE THREAD

**Issue by yoye** [paypal/PayPal-PHP-SDK#393] opened 2015-09-08 08:54 UTC
Hi, I have got a transaction refused and a response code 400 when trying to create a sale refund.

I know this is not the PayPal support but I found the exception message not accurate. I have got only 2 sales which generate this error, all the others went fine.

Here are my debug_id : 84cfe386895dd, f809e49cd35ce.
A part of my stack trace : 
```
class PayPal\Exception\PayPalConnectionException#48 (10) {
  private $url =>
  string(64) "https://api.paypal.com/v1/payments/sale/SALE_ID/refund"
  private $data =>
  string(195) "{"name":"TRANSACTION_REFUSED","message":"The request was refused.{0}","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#TRANSACTION_REFUSED","debug_id":"f809e49cd35ce"}"
  protected $message =>
  string(107) "Got Http response code 400 when accessing https://api.paypal.com/v1/payments/sale/SALE_ID/refund."
```

**Comment by tomwhipple** [comment] 2015-09-08 15:13
So, to clarify, this bug is about the error message returned to your app?

Can you state the observed behavior vs. the expected behavior?

**Comment by yoye** [comment] 2015-09-08 16:16
This is the problem, with this message I don't know if this is the good behavior. Since 1 year all others sale refunds never returned an error. Then, I've got 2 in a row.

**Comment by jaypatel512** [comment] 2015-09-21 19:02
Are you seeing this error consistently now ? Or Is it still intermittent. I am trying to reproduce this issue to better debug. 

Also, in the meantime, you could also reach out to [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) to get more details on why it failed. I will continue to look into our SDK code to reproduce the issue :+1:

**Comment by yoye** [comment] 2015-09-22 08:05
Only with two sales. I don't get this problem anymore. 

As I said, I don't understand whats happened. To me the message is not clear.

Sorry but I don't get more information than the 2 debug_id.

**Comment by ppmtscory** [comment] 2015-09-24 21:26
@yoye the issue with the refunds were that they were outside of the valid 60 day refund period.  Your concern with the error message is accurate as there is a REFUND_TIME_LIMIT_EXCEEDED error that should be thrown instead.  I've filed this request with our internal engineers to have this changed.  Since this is not an issue specific to the SDK and the internal ticket to correct the error has been filed, I will be closing this issue.

(PPPLPAYPT-2906 - for PayPal's tracking)

**Closed by ppmtscory** 2015-09-24 21:26 UTC
Labels: api-payments, question
