### ISSUE TITLE
NotifyUrl is not a fully qualified URL

### ISSUE THREAD

**Issue by yoye** [paypal/PayPal-PHP-SDK#1153] opened 2018-07-19 11:54 UTC
### General information

* SDK / Library version: 1.13.0
* Environment: Sandbox and Produciton
* Language, language version, and OS: PHP 7.2

### Issue description
I can't create a Billing Plan anymore without getting an exception. My plan seems created but the JSON return to notify_url` empty which is normal because it's not required. But when the MerchantPreferences is build with this return I've got an `\ InvalidArgumentException` with the message:` NotifyUrl is not a fully qualified URL`

Same thing occured while I only use `Plan :: get ($ planId, $ context);`

Does your API have changed and this not reported on your code?

**Comment by srjlewis** [comment] 2018-07-19 12:13
Same as problem as #1151 - PR #1152 Fixes it.

**Comment by prakash-gangadharan** [comment] 2019-09-14 06:13
Hi @yoye , this issue was also reported by Beatstars late in 2018 who is using the PHP SDK to create billing plans. The cause of the issue is, during GET call null is obtained for most of the response parameters (ex return_url, cancel_url, notify_url & state etc.,) from paypal server side when it was not set by the merchant.

The fix for this issue has been pushed to LIVE around 2nd October,2018 04:30 PM PST from paypal server side. This issue was not happening anymore. Hence closing this issue as it is no longer applicable.

**Closed by prakash-gangadharan** 2019-09-14 06:13 UTC
Labels: question
