### ISSUE TITLE
Got Http response code 500 when accessing https://api.sandbox.paypal.com

### ISSUE THREAD

**Issue by anaskassis** [paypal/PayPal-PHP-SDK#686] opened 2016-10-11 11:42 UTC
### Required Information

- PHP Version:
- PayPal-PHP-SDK Version:
- Debug ID(s): 6bc34b17f055d

### Issue Description
I tested my code last week and it was working fine 
i did lot of test 

Today i try to test it and i got this error

{"name":"INTERNAL_SERVICE_ERROR","details":[],"message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"6bc34b17f055d"}

Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-5GX356603D440911TK76M4NI/execute.

I did some research about this error ,  i found lot of people have same error, but unfortunately i did't find any solution for this problem 

Here is The Code

 public function finalizePayment()
    {

        if (!isset($_GET['paymentId'], $_GET['PayerID'])) {
            die('');
        }

        $paymentId = $_GET['paymentId'];
        $payerId = $_GET['PayerID'];

        $execute = new PaymentExecution();
        $execute->setPayerId($payerId);

        $payment = Payment::get($paymentId, $this->paypal);

        try {
            $result = $payment->execute($execute, $this->paypal);
        } catch (PayPalConnectionException $e) {
            die($e->getData());
        }
        return json_decode($result);
    }

**Comment by sseidelmann** [comment] 2016-10-11 11:56
Here the same.
Maybe caused by the not "approved" state.
```
[11-10-2016 08:31:33] PayPal\Core\PayPalHttpConnection : INFO: Response Status  : 500
[11-10-2016 08:31:33] PayPal\Core\PayPalHttpConnection : DEBUG: Response Headers        : HTTP/1.1 500 Internal Server Error, Date: Tue, 11 Oct 2016 08:31:27 GMT, Server: Apache, PROXY_SERVER_INFO: host=slcsbplatformapiserv3002.slc.paypal.com;threadId=936, Paypal-Debug-Id: 7cc6adc3bc7be, CORRELATION-ID: 7cc6adc3bc7be, Content-Language: *, Connection: close, X-SLR-RETRY: 500, X-SLR-RETRY-API: /v1/payments/payment/{id}/execute, Connection: close, Paypal-Debug-Id: 7cc6adc3bc7be, Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D1604582487%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Tue, 11 Oct 2016 09:01:33 GMT; domain=.paypal.com; path=/; Secure; HttpOnly, Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT, Vary: Authorization, Content-Length: 207, Content-Type: application/json, ,
[11-10-2016 08:31:33] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-3VS02895UN202305RK76KCSY/execute. {"name":"INTERNAL_SERVICE_ERROR","details":[],"message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"7cc6adc3bc7be"}
[11-10-2016 08:31:33] PayPal\Core\PayPalHttpConnection : DEBUG:
```

If i fetch the payment details before the execute with
```
[11-10-2016 08:31:26] PayPal\Core\PayPalHttpConnection : INFO: GET https://api.sandbox.paypal.com/v1/payments/payment/PAY-3VS02895UN202305RK76KCSY
```
i get the response with the state "created" and not like documented "approved" (see https://developer.paypal.com/docs/integration/web/accept-paypal-payment/)

**Comment by pp-randy** [comment] 2016-10-11 14:54
Closing this issue as a duplicate.  I have put PayPal tracking information in the other issue https://github.com/paypal/PayPal-PHP-SDK/issues/685

@sseidelmann that could be a separate issue. Lets see if the state clears up when this issue is resolved.  I am not getting a 500 with my attempts but I do see the start in created when I look up the payment for I execute it, which is not matching what is documented.

**Closed by pp-randy** 2016-10-11 14:54 UTC

**Comment by anaskassis** [comment] 2016-10-11 23:16
OK thank you
