### ISSUE TITLE
Is EWP supoprted by the PHP SDK?

### ISSUE THREAD

**Issue by prionkor** [paypal/PayPal-PHP-SDK#502] opened 2016-02-26 06:58 UTC
I am trying to locate any **Encrypted Website Payments** code in this sdk searched by the string *Encrypted Website Payments* and *EWP* but it didn't get me any result.

Does the sdk supports EWP for encrypting payment buttons?

**Comment by pp-randy** [comment] 2016-02-26 15:45
Closing as duplicate of https://github.com/paypal/buttonmanager-sdk-php/issues/14

**Closed by pp-randy** 2016-02-26 15:45 UTC
Labels: duplicate, question
