### ISSUE TITLE
Double charge

### ISSUE THREAD

**Issue by luong** [paypal/PayPal-PHP-SDK#369] opened 2015-08-03 03:51 UTC
Hi,

Currently we are using Paypal REST API, latest version, we have the following issue:

1. User adds credit cards, we will store them in Paypal.
2. We charge user items by using Card ID, but some of them are double charged.
If user click "Pay", Paypal return error code 'INTERNAL_SERVICE_ERROR' but it is still charged in Paypal server. If this click "Pay" again, it says ok from Paypal (charged twice).

Could you pleased check why Paypal says 'INTERNAL_SERVICE_ERROR' but it still charged. I checked and see this case just happen for newly added cards.

Some debug codes you can check: 82889b86434a7, 296c2034fb2b4. They are codes from our live products.

**Comment by paultarr** [comment] 2015-08-03 09:38
We are also experiencing this issue on live since last week:

More debug_ids to check against (INTERNAL_SERVICE_ERROR responses from PayPal, but resulting in payments actually processing):

22d2fc4a49d9e, ee5295815fe33, b2c4da82393c6, dd049ace357fd

**Comment by paultarr** [comment] 2015-08-03 10:01
To confirm these duplicate payments have occurred on cards already transacted using stored credit id, as well as first time payments.

**Comment by jaypatel512** [comment] 2015-08-03 14:40
Hey @luong @paultarr ! 

I have asked the payments team to look into this. I should have some initial response from them very soon.

**Comment by jaypatel512** [comment] 2015-08-03 14:55
For internal tracking: PPPLPAYPT-1200

**Comment by tomwhipple** [comment] 2015-08-03 15:55
@luong @paultarr we'll look in to making any necessary changes to the SDK, but you should also open tickets at https://www.paypal-techsupport.com/app/ask to get help rolling back affected transactions.

**Comment by luong** [comment] 2015-08-04 02:41
I opened ticket at https://www.paypal-techsupport.com/app/ask. Hope to have a fix soon.

**Comment by paultarr** [comment] 2015-08-04 09:44
This has occurred again today. 2 transactions returning INTERNAL_SERVICE_ERROR but still processing transactions. Debug ids as follows:

0af0e6cc61ff2, 2868e5da572a1

Is there a further update on this, as this is resulting in users losing confidence in the payment platform.

**Comment by paultarr** [comment] 2015-08-04 14:21
@tomwhippie @jaypatel512  is there any further update? 

We need to formulate a response in conjunction with PayPal to confirm to users why they are being incorrectly repeat billed and also that this is an issue on the PayPal side.

An estimated fix time for this would also be appreciated, as this is a business critical issue.

**Comment by jaypatel512** [comment] 2015-08-04 18:07
Hey @paultarr !

We have reached out to the Payments API team, and they have realized the issue. They are working on it. However, I would definitely recommend reaching out to https://www.paypal-techsupport.com/app/ask to increase the priority, and getting more traction on this issue. Also, they might be able to help you with the work around, if any on this issue.

**Comment by paultarr** [comment] 2015-08-05 08:50
@jaypatel512 @tomwhipple 

I've already raised a ticket last week but feedback is incredibly opaque and we haven't had any technical updates other than that the issue is being investigated.

Can we please get an urgent update on this as it's still occurring, despite a new status being thrown up in responses today for some repeat payments of "The requested resource ID was not found". 

Example debug_id today, with INTERNAL_SERVICE_ERROR:

7432326fa467e

**Comment by tomwhipple** [comment] 2015-08-05 15:41
@paultarr Thanks for that feedback. I will escalate with the support management team.

**Comment by dannetstudio** [comment] 2015-08-05 19:11
We are experimenting the same issue since 5 days ago. The API SDK code is updated to the last version with comoposser but the problem still persists.

**Comment by tomwhipple** [comment] 2015-08-06 00:08
Update: The underlying API team has a patch and is working to push it as soon as it is safe to do so. 

In the mean time, please continue to open tickets with [merchant support](https://www.paypal-techsupport.com/app/ask) as the SDK engineering team does not have the ability to address transaction specific problems or issue refunds.

**Comment by juwlee** [comment] 2015-08-06 13:53
@paultarr @dannetstudio @luong Good news! The fix has been pushed. Please try again and let us know if you still see the issue.

**Closed by juwlee** 2015-08-06 13:53 UTC
Labels: api-bug, api-payments
