### ISSUE TITLE
WARNING: Missing Accessor: PayPal\Api\Transaction:setCoupledGroup

### ISSUE THREAD

**Issue by AnjaGoldmann** [paypal/PayPal-PHP-SDK#405] opened 2015-09-28 14:11 UTC
Hello,

in our OXID PayPal Plus modul we get a warning:

PayPal\Validation\ModelAccessorValidator: WARNING	: Missing Accessor: PayPal\Api\Transaction:setCoupledGroup.

Please help.

Regards

**Comment by jaypatel512** [comment] 2015-09-28 14:39
Duplicate of https://github.com/paypal/PayPal-PHP-SDK/issues/399

**Closed by jaypatel512** 2015-09-28 14:39 UTC
