### ISSUE TITLE
UNKNOWN_ERROR for valid vault repeat and regular card payments

### ISSUE THREAD

**Issue by paultarr** [paypal/PayPal-PHP-SDK#386] opened 2015-08-28 15:03 UTC
We are experiencing UNKNOWN_ERROR responses for the following debug_ids with vaulted cards and new cards:

Initial Debug ids (updated 16:03)
ed5a6143821e8
b69dee15f43f4
9fa0910929df7
46f5615f5d6c7

More Debug ids (updated 16:07)
400e04fc70157

More detail on why these are causing errors would be helpful, as these transactions are not unusual in that many other thousands of transactions successfully process.

**Comment by jaypatel512** [comment] 2015-08-28 15:49
Is this happening on live or sandbox btw ?

**Comment by jaypatel512** [comment] 2015-08-28 15:52
This looks like the issue related to the Payments API, and not specifically SDK. I will look further into this. However, [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) would be the better channel to get this issue resolved. This issue tracker is mainly focused on SDK bugs.

**Comment by paultarr** [comment] 2015-08-28 15:54
I can confirm requests are being submitted via live.

The SDK is being used for all requests, so this could affect any user that implements their integration with the SDK.

I'll also submit a ticket with merchant technical support.

**Comment by jaypatel512** [comment] 2015-08-28 15:56
That sounds good. I will look into this from my end to figure out why it is failing. Btw, just to make sure, can you verify the credit cards in use are not expired ? 

Still a more appropriate error response would have helped.

**Comment by paultarr** [comment] 2015-08-28 15:57
I can confirm the cards in question have expiry dates at least a year in the future. Also, the tokens have validity for around 3 years.

**Comment by jaypatel512** [comment] 2015-08-28 16:27
Sounds good. I will definitely pass all that information to Merchant Technical Support. Please reach out to them :+1: !

**Comment by juwlee** [comment] 2015-08-28 16:46
@paultarr it seems they are failing due to a few different reasons. Most of them were indeed internal service errors, but one that seems to be caused by client. The total transaction amount was 0.

As @jaypatel512 suggested, please contact PayPal MTS and share the `debug IDs`.

**Comment by jaypatel512** [comment] 2015-08-28 17:44
We have passed the information to MTS, and you should be able to get this resolved from them. Thanks. Closing the issue as it is not directly related to SDK.

**Closed by jaypatel512** 2015-08-28 17:44 UTC
Labels: api-payments, question
