### ISSUE TITLE
Unable to find transaction in sandbox transaction in developer dashboard

### ISSUE THREAD

**Issue by mukundindianic** [paypal/PayPal-PHP-SDK#688] opened 2016-10-12 08:02 UTC
### Required Information

- PHP Version: 5.6
- PayPal-PHP-SDK Version: -
- Debug ID(s): -

I have created one transaction using payments/CreatePayment.php using provided SDK. Executed successfully. No error shown but I wonder where can I find the transaction details in developer dashboard:

Sample Request:
```
{
    "intent": "sale",
    "payer": {
        "payment_method": "credit_card",
        "funding_instruments": [
            {
                "credit_card": {
                    "type": "visa",
                    "number": "4111111111111111",
                    "expire_month": "11",
                    "expire_year": "2019",
                    "cvv2": "012",
                    "first_name": "Joe",
                    "last_name": "Shopper"
                }
            }
        ]
    },
    "transactions": [
        {
            "amount": {
                "currency": "USD",
                "total": "20",
                "details": {
                    "shipping": "1.20",
                    "tax": "1.30",
                    "subtotal": "17.50"
                }
            },
            "item_list": {
                "items": [
                    {
                        "name": "Ground Coffee 40 oz",
                        "description": "Ground Coffee 40 oz",
                        "currency": "USD",
                        "quantity": 1,
                        "tax": "0.30",
                        "price": "7.50"
                    },
                    {
                        "name": "Granola bars",
                        "description": "Granola Bars with Peanuts",
                        "currency": "USD",
                        "quantity": 5,
                        "tax": "0.20",
                        "price": "2"
                    }
                ]
            },
            "description": "Payment description",
            "invoice_number": "57fde9b10902d"
        }
    ]
}
```
Response:
```

{
    "intent": "sale",
    "payer": {
        "payment_method": "credit_card",
        "funding_instruments": [
            {
                "credit_card": {
                    "type": "visa",
                    "number": "xxxxxxxxxxxx1111",
                    "expire_month": "11",
                    "expire_year": "2019",
                    "first_name": "Joe",
                    "last_name": "Shopper"
                }
            }
        ]
    },
    "transactions": [
        {
            "amount": {
                "total": "20.00",
                "currency": "USD",
                "details": {
                    "subtotal": "17.50",
                    "tax": "1.30",
                    "shipping": "1.20"
                }
            },
            "description": "Payment description",
            "item_list": {
                "items": [
                    {
                        "name": "Ground Coffee 40 oz",
                        "price": "7.50",
                        "currency": "USD",
                        "quantity": "1",
                        "description": "Ground Coffee 40 oz",
                        "tax": "0.30"
                    },
                    {
                        "name": "Granola bars",
                        "price": "2.00",
                        "currency": "USD",
                        "quantity": "5",
                        "description": "Granola Bars with Peanuts",
                        "tax": "0.20"
                    }
                ]
            },
            "related_resources": []
        }
    ],
    "id": "PAY-4HR21577GL095970LK766TMQ",
    "create_time": "2016-10-12T07:43:46Z",
    "update_time": "2016-10-12T07:43:46Z",
    "state": "created",
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-4HR21577GL095970LK766TMQ",
            "rel": "self",
            "method": "GET"
        }
    ]
}
```

**Comment by cyclux** [comment] 2016-10-12 14:19
I also recognized this. Just getting "Notifications". Nothing in https://developer.paypal.com/developer/dashboard/sandbox/

**Comment by bluk** [comment] 2016-10-12 14:43
Hi, this is a duplicate of https://github.com/paypal/PayPal-PHP-SDK/issues/663 . There is currently an issue with the sandbox transactions developer dashboard page. You should be able to find the transactions if you login using your sandbox seller account at https://www.sandbox.paypal.com/ . Please follow #663 for more updates.

**Closed by bluk** 2016-10-12 14:43 UTC
