### ISSUE TITLE
Unable to pay: NotifyUrl is not a fully qualified URL error retrieved

### ISSUE THREAD

**Issue by xserrat** [paypal/PayPal-PHP-SDK#1151] opened 2018-07-19 10:52 UTC
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

I'm having an error when I try to pay, when creating an agreement. The error returned is:

`NotifyUrl is not a fully qualified URL`.

Also, when I try to retrieve subscription information about an agreementId, I get a similar error but with another url: `ReturnUrl is not a fully qualified URL`.

Is there any recent change in your API that is not updated in the SDK? It's related to a merchant_preferences field where the API is returning three null urls: "cancelUrl, returnUrl and notifyUrl".

I hope someone helps...

Thanks.

**Comment by marcogrossisas** [comment] 2018-07-19 11:11
Hello @xserrat we also noticed it since 16 hours ago more or less. 

The problem is that 
`POST https://api.sandbox.paypal.com/v1/payments/billing-agreements/` now returns the parameter `notify_url` and this provokes `PayPal\Validation\UrlValidator::validate` to fail. Until yesterday no `notify_url `was returned if wasn't set. 

Unable to process payments now. 
This is a serious bug. 
Thanks

**Comment by xserrat** [comment] 2018-07-19 11:21
You're totally right. I've just compared the old return json and now appear the field you're saying.

We've tried to update the notify_url using a PATCH request with the agreement_id but it is only available when creating the plan... The error I see is the following:


```json
{
    "name": "BUSINESS_VALIDATION_ERROR",
    "details": [
        {
            "field": "validation_error",
            "issue": "Can update template only in created state"
        }
    ],
    "message": "Business error",
    "information_link": "https://developer.paypal.com/docs/api/payments.billing-plans#errors",
    "debug_id": "b429385e17919"
}
```

**Comment by sasky** [comment] 2018-07-19 23:28
Not Happy Guys. I had to figure out what was going on and apply a quick fix in the middle of the night. As our website suddenly stopped accepting payment plans. We probably lost a few hundred in sales. Then my 8 month baby is apparently 'teething' so didn't get much sleep after fixing this on our site. Lets just say today I am sleep deprived and grumpy. I think I need another coffee.

**Comment by crowd8** [comment] 2018-07-20 09:10
the same here...

**Comment by karthiksekars** [comment] 2018-07-20 17:34
Check the below link 

https://stackoverflow.com/questions/51424433/paypal-php-sdk-notifyurl-is-not-a-fully-qualified-url-error/51447678#51447678

**Comment by highhair20** [comment] 2018-07-29 21:44
When will PR #1152 be merged to master and will there be an official patch release?

**Comment by daviduarte** [comment] 2018-08-18 15:44
The same here. I'm new with PayPal and I install the SDK PHP through this [page](https://developer.paypal.com/docs/api/overview/#additional-information). I solve the problem with the link shared by **karthiksekars**. I'm waiting for a official patch release

**Comment by waqasraza123** [comment] 2018-08-20 09:53
same issue here.

**Comment by phillipsnick** [comment] 2018-08-29 21:13
This is really bad, broken the live site due to API changes on PayPal.

**Comment by phillipsnick** [comment] 2018-08-29 21:30
Is there no fix for this on existing plans?

**Comment by phillipsnick** [comment] 2018-08-30 21:07
Spent a few hours on this now and made zero successful progress.

Looked at the response by @karthiksekars and created the following class.

```php
use PayPal\Api\MerchantPreferences as BaseMerchantPreferences;
use PayPal\Validation\UrlValidator;

class MerchantPreferences extends BaseMerchantPreferences
{
    public function setNotifyUrl($notify_url)
    {
        if(!empty($notify_url)){
            UrlValidator::validate($notify_url, "NotifyUrl");
        }

        $this->notify_url = $notify_url;
        return $this;
    }
}
```

Then create a new plan using the following MerchantPreferences

```php
$merchantPreferences = new MerchantPreferences();
$merchantPreferences->setReturnUrl("https://REDACTED.com/subscriptions/paypal/processagreement")
        ->setNotifyUrl("https://REDACTED.com/subscriptions/paypal/notify")
        ->setCancelUrl("https://REDACTED.com/subscriptions/paypal/cancel")
        ->setAutoBillAmount('YES')
        ->setInitialFailAmountAction('CONTINUE')
        ->setMaxFailAttempts('0');
```

But the response from PayPal is still

```json
{
	"name": "VALIDATION_ERROR",
	"details": [{
		"field": "merchant_preferences.notify_url",
		"issue": "Field is invalid in a request."
	}],
	"message": "Invalid request. See details.",
	"information_link": "https://developer.paypal.com/docs/api/payments.billing-plans#errors",
	"debug_id": "40c3fa3bcd7ae"
}
```

I'm at a loss here as the URL looks perfectly valid to me. 

According to the API docs at https://developer.paypal.com/docs/api/payments.billing-plans/v1/

```
notify_url string
The URL where the customer is notified that the agreement was created. Read-only and reserved for future use.
Read only.

Maximum length: 1000.
```

Could anyone point me in the right direction?

**Comment by bootell** [comment] 2018-08-31 08:33
@phillipsnick According to docs, notify_url is a read only param, just remove the `setNotifyUrl` line should work fine.
You can set notify_url in paypal's REST Api webhook page.

**Comment by MrMooky** [comment] 2018-09-02 16:48
I solved the issue with `setNotifyUrl` as described in the link posted by @karthiksekars. Now I can make payments (still in Sandbox). When I get redirected to the ReturnUrl – which is already the correct Url, I get this error: `ReturnUrl is not a fully qualified URL`.

Again: payment is successfully made, a token is generated and the "PayPal Developer Backend" even tells me the payment went through. I do get redirected to the page I defined, yet the API gives me that error. Any idea what else it could be?

**Comment by markantonay** [comment] 2018-09-12 00:34
@MrMooky 

try to add an if not empty condition in both `function setCancelUrl ` and ` function setReturnUrl `  for the validator.

**Comment by prakash-gangadharan** [comment] 2019-09-14 06:11
Hi folks, this issue was also reported by Beatstars late in 2018 who is using the PHP SDK to create billing plans. The cause of the issue is, during GET call null is obtained for most of the response parameters (ex return_url, cancel_url, notify_url & state etc.,) from paypal server side when it was not set by the merchant.

The fix for this issue has been pushed to LIVE around 2nd October,2018 04:30 PM PST from paypal server side. This issue was not happening anymore. Hence closing this issue as it is no longer applicable.

**Closed by prakash-gangadharan** 2019-09-14 06:11 UTC
Labels: sdk-support
