### ISSUE TITLE
Get Billing Agreement fails with validation error

### ISSUE THREAD

**Issue by nsanden** [paypal/PayPal-PHP-SDK#1179] opened 2018-09-01 15:17 UTC
### General information
Can no longer call Agreement::get() without getting this validation error:

`ReturnUrl is not a fully qualified URL`

* SDK/Library version: 1.13.0
* Environment: Production
* `PayPal-Debug-ID` values:  
* Language, language version, and OS:

### Issue description

```text
ReturnUrl is not a fully qualified URL

#0 /home/sortingsocial/app/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/MerchantPreferences.php(107): PayPal\Validation\UrlValidator::validate(NULL, 'ReturnUrl')
#1 /home/sortingsocial/app/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalModel.php(256): PayPal\Api\MerchantPreferences->setReturnUrl(NULL)
#2 /home/sortingsocial/app/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalModel.php(244): PayPal\Common\PayPalModel->assignValue('return_url', NULL)
#3 /home/sortingsocial/app/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalModel.php(223): PayPal\Common\PayPalModel->fromArray(Array)
#4 /home/sortingsocial/app/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalModel.php(223): PayPal\Common\PayPalModel->fromArray(Array)
#5 /home/sortingsocial/app/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalModel.php(270): PayPal\Common\PayPalModel->fromArray(Array)
#6 /home/sortingsocial/app/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Agreement.php(440): PayPal\Common\PayPalModel->fromJson('{"id":"I-C5NB5E...')
#7 /home/sortingsocial/app/components/Paypal.php(198): PayPal\Api\Agreement::get('I-C5NB5ERLNW8T', Object(PayPal\Rest\ApiContext))
```

**Comment by srjlewis** [comment] 2018-09-05 14:58
We are waiting for https://github.com/paypal/PayPal-PHP-SDK/pull/1152 to be palled to fix this issue

**Comment by prakash-gangadharan** [comment] 2019-09-13 11:41
Hi @nsanden and @srjlewis , This issue was also reported by Beatstars who is using the PHP SDK to create billing plans. The cause of the issue is, during GET call null is obtained for most of the response parameters (ex return_url, cancel_url, notify_url & state etc.,) from paypal server side when it was not set by the merchant.

The fix for this issue has been pushed to LIVE around 2nd October,2018 04:30 PM PST from paypal server side. This was not happening anymore. Hence closing this issue as it is no longer applicable.

**Closed by prakash-gangadharan** 2019-09-13 11:41 UTC
Labels: sdk-bug
