### ISSUE TITLE
Charge an initial payment with a billing agreement, don't create if user can't be charged (since plan with setup_fee can be created even for accounts with 0 funds)

### ISSUE THREAD

**Issue by iadj** [paypal/PayPal-PHP-SDK#504] opened 2016-02-29 02:59 UTC
In the sandbox, when I create a billing plan & agreement with `setup_fee`, the plan can be created even with an account that has no funds.

My experience with the sandbox with `setup_fee` is that the `setup_fee` stays at 0, even though I configured it. However I heard it can take several minutes after the creation of the plan & agreement until it actually charges the account. How will we know until then if the user has sufficient funds in their account to pay the initial payment? What happens if the user cancels their plan before the `setup_fee` has gone through? I want my users to instantly utilize their subscription features after payment. Not require them to wait several minutes before the initial payment has (or hasn't) gone through.

I know that with the classic API it's suggested to combine the billing plan with a Checkout for Digital Goods item, and have the user authorize a payment for the digital goods item & the billing agreement together. This way the user can only create the billing profile if it was able to pay for the digital goods item. Is this still the best practice? If so, how do we do this using the PHP SDK?

**Comment by ppmtscory** [comment] 2016-03-01 17:26
@iadj this may just be a limitation of the sandbox, but in order to look into this, can you please provide an example of an agreement where the setup fee was charged incorrectly?  Also, please make sure that you're using `initial_fail_amount_action` appropriately as explained in your other issue #505.

**Comment by iadj** [comment] 2016-03-02 03:31
I am using `initial_fail_amount_action`.

I posted a follow-up on this in the latest comment at https://github.com/paypal/PayPal-PHP-SDK/issues/505#issuecomment-191033870

**Comment by ppmtscory** [comment] 2016-03-03 15:27
copying comment from other issue.....

@iadj this could be the way that your sandbox account is set up as well. Did your agreement eventually change to Active or is it still in a Pending state? Can you let me know the agreement ID so that I can take a look? Also, i will run some tests in the sandbox as this latency of setup_fee very well may be just an issue with Sandbox. The agreement will be pending until that fee is either charged or failed.

**Comment by iadj** [comment] 2016-03-03 15:39
@ppmtscory The `setup_fee` in the sandbox always appears to remain at `0.00` in the returned json, but if the account is successfully charged the configured `setup_fee` does get processed and is visible under `last_payment_amount` in the billing agreement, and the profile status is set to `active`. I suppose this is a bug.

If I want to proplerly check if the payment is made successfully instantly after the user authorized the agreement with Paypal (and not give a user a 'Thank you' page if the charge wasn't successful), I suppose I need to create a 'Processing...' page that captures the Paypal token with an AJAX request and checks (every second for instance) if the profile becomes Active or Canceled?

**Comment by ppmtscory** [comment] 2016-03-03 16:10
This should really only be happening in the sandbox.  I'm not aware of anything taking a long time to process in Production.  However, yes, your AJAX loop would be a sufficient method of getting the status if there's a delay.  Let me run some tests today and get back to you on the `setup_fee` showing 0 and also the delay in processing.  I will run a test in Production to ensure that there's not the same delay as in Sandbox.  I'll respond back here with my findings as soon as I get a chance to run the tests.

**Comment by iadj** [comment] 2016-03-03 17:15
Thank you @ppmtscory. What would be ideal is that the status is always returned as either 'Active' or 'Canceled' instantly after the `execute` command.

**Comment by ppmtscory** [comment] 2016-03-03 17:24
I'd agree with that... and I'm fairly certain that's what is happening in Production.  Standby.....

**Comment by ppmtscory** [comment] 2016-03-04 17:53
@iadj my apologies on the delay in testing, but I've filed too issues to the internal team for this.  One for the `setup_fee` showing 0.00 in the response and the other for `setup_fee` not charging immediately upon execution of the agreement.  I've noticed that, even in production, the setup fee wasn't charging immediately.

For PP Internal Tracking only - PPPLMER-11245 & PPPLMER-11251

**Comment by iadj** [comment] 2016-03-05 21:46
@ppmtscory Came across an issue regarding the AJAX call which I am currently using to work around the payment not being decently retrieved in the billing agreement API:
Paypal has an API call rate limit, which means if we have an ajax loop that gets the billing agreement state every second until it returns 'Active' or not 'Pending', it could hit the rate limit risking the entire app to be blocked from Paypal's API for several minutes.

Stripe has error handling with try/catch as follows:
```
try {
\Stripe\Customer::create(array(
                     'source' => $token,
                     'plan' => $plan,
                     ));
} catch(\Stripe\Error\Card $e) {

} catch (\Stripe\Error\Base $e) {

}
...
```

Next to the fact that `setup_fee` should be instantly charged and properly show in the Billing Agreement API, try/catch would be a decent way to handle the execution of billing agreements with Paypal (try execute billing agreement with `setup_fee`, catch error if `setup_fee` cannot be processed or billing status can not be set to 'Active'). 

Thanks for forwarding the issue to the team as well.

**Comment by josietam** [comment] 2016-03-07 03:23
Thanks all here who proposed the idea of using 'setup_fee' for the first subscription fee.  It helped to by-pass the start day problem (that start date has to be today+1) and the immediate transaction.

It works in sandbox.  Thank you!

**Comment by superstringman** [comment] 2016-04-06 00:29
Is this still broken?  Each time I execute an agreement it comes back pending and the setup_fee is 0 even though I verified in the agreement create response it is not.

**Comment by vbresults** [comment] 2016-04-09 15:49
@ppmtscory What became of this?  I am still experiencing the Pending limbo issue at agreement execution time.

**Comment by ppmtscory** [comment] 2016-04-11 15:56
I've reached out to the team internally and will keep you updated as I know more.

**Comment by danieltome** [comment] 2016-04-22 05:06
Re: the start date being "today + 1", that was working before, "the setup fee resulted in an immediate payment" cc: @josietam 
but around last Tuesday we started to get the delay as explained in this issue.

+1 for paypal to look into this.

I've been reading other issue here re: subscriptions and there are a lot of frustrated developers.
I hope they fix this soon and communicate it soon too.

**Comment by danadijans** [comment] 2016-04-22 05:22
For the sake of not opening a duplicate ticket, I too ask/ urge/ **beg** Paypal to look into this issue ASAP. 

A background on our implementation:
- We're currently using a sandbox account
- We have a service requiring a monthly subscription
- First month's payment uses the "setup fee" for immediate payment and access
- Recurring payments begin today + 30 days

This process had been working for the past 4-5 months. The project is currently in final testing the functionality has suddenly stopped working as expected.

Now we get a success message back from paypal after the user goes through the paypal process, but the agreement remains pending and no transaction has taken place.

Can someone confirm if this is an issue in production (non-sandbox) accounts?

**Comment by ppmtscory** [comment] 2016-04-22 19:58
I just followed up on our internal ticket for this and it looks like their making good progress on a fix.  However, I'm hesitant to promise any ETA until I get a more concrete answer on that.

**Comment by danadijans** [comment] 2016-04-27 06:19
@ppmtscory has there been any further updates by chance. This is a blocker to our testing.

Also can someone confirm if this is an issue in production (non-sandbox) accounts?

Thanks

**Comment by vbresults** [comment] 2016-04-27 06:39
@danadijans Confirm.

**Comment by danadijans** [comment] 2016-04-27 06:41
Thanks for confirming @vbresults

**Comment by iadj** [comment] 2016-04-27 11:12
@danadijans Confirmed. You can use an AJAX loop to check the payment profile status every x (i.e. 1.5) seconds until the payment status is no longer pending. The profile will either return Active or Canceled, and based on that status you can activate or deactivate the account. Also put a status check cron job in case the user leaves the AJAX page.

**Comment by danadijans** [comment] 2016-05-03 01:10
Thanks @iadj 

The AJAX loop isn't really an option for me. The status remains as "pending" for minutes to **hours** and not funds are received (at least in sandbox). Also our application requires immediate feedback and access to the time-sensitive site content, based on this subscription.

Is this issue specific to those leveraging the PHP SDK?

I don't see the Paypal .NET SDK Github with the same issue. Also there's subscription sites like Spotify which continue to use Paypal subscriptions although possibly not including an initial setup fee.

@ppmtscory is there any update on the internal tickets?

**Comment by iadj** [comment] 2016-05-03 01:11
Hours? I've yet to experience hours of pending. That would completely ruin the way I have it set up now.

**Comment by danadijans** [comment] 2016-05-03 01:29
@iadj yep, definitely experiencing over an hour using the sandbox (monitoring a test now) even though the transaction says "completed". It _was_ working instantly with the exact same code before something switched in Paypal.

We also allow users to upgrade their subscription based on the content they want access to. If we attempt to cancel and agreement that is still pending we receive further errors. Yes, we could test for this, but it's a long chain of issues if we're granting access to content without ever receiving funds.

**Comment by ppmtscory** [comment] 2016-05-03 20:46
I actually just received word a couple minutes ago, that they're shooting for an available release window for this fix (hopefully) by the end of the week.  I'm hesitant to provide an exact date until I know more about their ability to get into the release window.

**Comment by danadijans** [comment] 2016-05-09 00:09
@ppmtscory did this fix get rolled out?

Do we need to make code changes to take advantage of this fix?

**Comment by ppmtscory** [comment] 2016-05-09 14:56
@danadijans the issue with `setup_fee` showing 0 has been fixed.  I'm in the process of testing the other issue of `setup_fee` not charging instantly right now to see if it was fixed with the same release.

**Comment by ppmtscory** [comment] 2016-05-09 21:09
Unfortunately it doesn't look like the "delayed charging" was included with this release so I will follow up with the team to see about it's ETA for resolution.

**Comment by iadj** [comment] 2016-05-09 21:10
@ppmtscory Thank you for continued effort in keeping us up to date. Very appreciated!

**Comment by danadijans** [comment] 2016-05-16 00:31
Hi @ppmtscory, sorry for the repetition, but is there any update on the setup fee and pending agreement fixes?

It looks to be about two and a half months this has been running, but it remains a critical blocker for us.

I don't suppose there's a way for the public to see the status of PPPLMER-11245 & PPPLMER-11251 you noted earlier? We do appreciate you're the middle man in this scenario, but it doesn't appear to be discussed much elsewhere.

Thanks!

**Comment by ppmtscory** [comment] 2016-05-16 18:56
Those are internal IDs that are not viewable externally.  Unfortunately I don't have any reliable ETA yet, but know that I'm continuously following up and trying to push things along.  I definitely understand the problems caused by `setup_fee` not charging immediately.  I know it's not ideal, but as a workaround, you can do just a one-time payment and _then_ have them sign up for the recurring charge.  Either way, I will be sure to post any updates here once I have them.

**Comment by delmicio** [comment] 2016-05-26 21:04
@ppmtscory thanks for your answers.
Maybe you could help me with how `initial_fail_amount_action` works. Is it triggered if `setup_fee` failed?
We need to know if `setup_fee` charge fail then paypal would suspend the agreement (and send IPN notification)? or maybe send the `recurring_payment_failed` IPN type?
In our case we can give our users access until the `setup_fee` is charged as long as we get notified if charge failed.

Thanks!

**Comment by ppmtscory** [comment] 2016-06-03 21:02
My apologies for the delay, @delmicio, yes the `initial_fail_amount_action` is based on the `setup_fee`.  You should then get the appropriate notification.

**Comment by iadj** [comment] 2016-06-05 21:02
@ppmtscory Any news on the setup fee not charging instantly?

**Comment by rdgreen16** [comment] 2016-06-05 21:03
@iadj really!!!! This is killing my business right now smh

**Comment by rdgreen16** [comment] 2016-06-05 21:05
You would think billion dollar companies would have these issues quickly fixed!!!!

**Comment by danadijans** [comment] 2016-06-05 23:16
Hi all, 
I've been in touch with Paypal support for the past month or so and it indeed looks like PPPLMER-11245 & PPPLMER-11251 are **resolved**. This was deployed a week or two ago.

These were the issues related to recurring payments that incur a setup fee not charging immediately and not activating the agreement.

My tests in sandbox confirm the setup fee is being charged and the agreement is activated instantly, though I have yet to test in production. I'd suggest everyone re-checks their specific implementations to confirm.

Thanks @ppmtscory for keeping across this.

**Comment by iadj** [comment] 2016-06-05 23:17
Can @ppmtscory confirm?

**Comment by rdgreen16** [comment] 2016-06-05 23:29
No it's not working still if the payment doesn't go through my api isn't notified and the customer continues to receieve free benefits with a manual cancellation on my part

**Comment by rdgreen16** [comment] 2016-06-05 23:30
**i have to do the manual cancellation I mean

**Comment by rdgreen16** [comment] 2016-06-05 23:31
And logging in PayPal site to check these isn't the fastest site to do this every time

**Comment by danadijans** [comment] 2016-06-05 23:51
@rdgreen16 is your instance testing a user with no funds and it still gets approved (returns a success message)? 

I'm pretty sure there's a known issue testing Paypal **sandbox** with users that have 0 funds, separate to the tickets I noted.

**Comment by rdgreen16** [comment] 2016-06-05 23:56
No this is real-time real life clients ordering services on my website. The billing agreement shows successfully created and itt goes through but on PayPal side it says pending. I'm sure they then try to retrieve funds but if the funds a cant be retrieved, PayPal canceles the billing agreement with no notification to me. So the user gets benefits with no payment

**Comment by danadijans** [comment] 2016-06-06 01:17
@rdgreen16 what might help is lodging a ticket direct to Paypal tech support here: https://www.paypal-techsupport.com (if you haven't already)

This was the only way we seemed to get traction for our issue and they were able to look at the specifics of our problem including our account and the request/ response logs with the Paypal API.

We had no success with calling any of the support numbers.

**Comment by ppmtscory** [comment] 2016-06-06 15:50
All,
I know it's not cool, and I am cringing while I type this, but I still don't have any ETA on `setup_fee` not charging instantly.  I'm trying to light as many fires as I can to get this rectified, so please know that I do greatly, GREATLY, appreciate your patience.  I realize it's wearing thin so thank you for sticking with me so far.  

As for the internal tickets, let me clarify a couple things with those.  This was a multi-issue thread to start with so those tickets were filed accordingly.

- PPPLMER-11245 - this was filed for `setup_fee` always showing `$0.00`.  This was resolved and so that's why that ticket is closed.
- PPPLMER-11251 - this was the ticket filed for `setup_fee` not charging instantly.  This ticket was mistakenly closed and is being tracked differently internally.  I'm now pressing these product owners directly via emails instead of through this internal ticketing.  This is why the support folks stated that it was closed.

Again, my sincere apologies for not having a new positive answer here, but I'm working with as many people as I can to get this changed.  As always, as soon as I hear any updates, I will be sure to post them here.

**Comment by danadijans** [comment] 2016-06-06 23:32
@ppmtscory, although I can't confirm in production with real funds yet, I have had [apparent] success in sandbox with setup_fee funds being received and the agreement set to active (which were all failing previously).

Here's a screenshot of the summary in Paypal Sandbox merchant account: http://screencast.com/t/NoIxcFz4n4k 

I'm not sure if you have access to this but the support ticket reference ID is: # 160510-000046

I'm not trying to give false hope here, but wish to clarify what actually was changed and fixed. I was simply told to restest and things appeared to work.

**Comment by ppmtscory** [comment] 2016-06-07 17:32
You are correct, however the sandbox issue and fix was a bit different than what's happening in Live right now.

As for that, I've been told by the engineering team that the ETA for this is June 23rd.  This is due to availability of release windows and also dependencies on other services.  If anything happens sooner, I will let everyone know, as well as if something happens to push this date back.

**Comment by danadijans** [comment] 2016-06-08 00:23
Thanks for the update @ppmtscory 

It's little concerning that sandbox is being used as a UAT environment, rather than being in sync with production code. Hopefully more users don't get caught out thinking their code is fine and then push it live. Not your call obviously, but misleading for devs out there.

**Comment by ppmtscory** [comment] 2016-06-08 14:48
Understood.  Just to be clear, though, the main issue in SB was capacity and not a code/service issue.

**Comment by omarkilani** [comment] 2016-06-17 19:34
It'll be pretty amazing if this actually gets fixed. This is the bane of my (and support people's) existence.

**Comment by iadj** [comment] 2016-06-17 22:08
I bit the bullet and am using Braintree instead, even though there's less supported countries for subscriptions.

**Comment by omarkilani** [comment] 2016-06-17 22:20
@iadj we tried to use Braintree, and they asked me why I wanted to use it (I said "PayPal subscriptions"). They rejected us because we wouldn't process our CC stuff through them as well.

**Comment by ackerchez** [comment] 2016-06-26 10:27
@ppmtscory has anything advanced here as we are past the 23rd ofJune? I have seen the setup fee being taken immediately when processing in sandbox but there is no webhook to notify of successful payment. The only webhooks that come back are for billing plan created, billing plan updated, and billing subscription created. How in future are we to know that payment has happened? Rely on IPN? Also when I used the setup fee for the immediate process and offset the subscription start date to account for the setup fee, the agreement was not "active but rather was "pending" and then no webhooks were returned when it was cancelled. Detailed information would be helpful here.

**Comment by ppmtscory** [comment] 2016-06-28 17:03
All - I will need to check with the team to see if it was pushed out or not.  I'm still seeing a decent delay in the test that I just ran.  I will update here once they let me know.

**Comment by vbresults** [comment] 2016-07-17 01:11
@ppmtscory Any updates?

**Comment by rdgreen16** [comment] 2016-07-17 01:26
Seems to be have been working great on my end since July 14th, not one fail for me so far.

**Comment by ppmtscory** [comment] 2016-07-18 15:05
Unfortunately not.  They've pushed some code to reduce the delay to a shorter period, but it still may not be immediate since it's ran with a batch process.  The work to make `setup_fee` charge real-time, I'm told, is set for the end of Q3/early Q4.  I'm still pressing them for something sooner, but that is the latest update that I have.

**Comment by danadijans** [comment] 2016-07-20 01:12
Thanks for the update @ppmtscory 

So is this understanding correct for subscriptions that include an initial setup fee in _production_:

- The setup_fee amount isn't charged immediately/ real-time, and despite a "success" response from Paypal, the funds/payment could still fail.
-  In the agreement setup, the agreement status is batch processed, and despite a "success" response from Paypal, the agreement status may remain pending for some time while it's in the queue.

We've received conflicting reports from Paypal reps, but I seem to be getting the most accurate information through this thread. Thanks!

**Comment by ppmtscory** [comment] 2016-07-20 15:41
@danadijans that's accurate.  The `setup_fee` is batch processed currently and that's taking approximately ~9 mins to charge.  Therefore, the agreement can be Pending.  The work to make this `setup_fee` immediate is what this thread is all about and is actively being worked on as we speak.

**Comment by DevinWalker** [comment] 2016-07-21 05:49
What a longwinded mess... it is a pretty basic request that when starting a subscription you charge an initial amount immediately - if this fails, the subscription is not created.

Is our best course of action to use `setup_fee` still?

**Comment by danadijans** [comment] 2016-07-21 06:45
Thanks for the confirmation @ppmtscory 

We have indeed proven the scenario of receiving a success response and then the setup_fee payment failed when it was processed later.

As an interim fix can anyone confirm which webhook event should fire when a setup_fee payment fails? 
https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/#event-types

This is causing us masses of trouble but if we can at least rectify accounts that fail payments we can mitigate some risk.

**Comment by iadj** [comment] 2016-07-21 12:02
It's odd because Braintree does appear to have said feature for Paypal 
subscriptions.

**Comment by rachnatib** [comment] 2016-07-22 04:15
This will be fixed by 22nd Aug 2016. 
setup fee will be charged immediately at the time of subscription profile creation. Apologies it took us so long to close this.

**Comment by DevinWalker** [comment] 2016-07-22 17:55
For what it's worth, yesterday during my testing in the sandbox `setup_fee` appeared to be charging immediately.

**Comment by viper-pranish** [comment] 2016-07-27 08:06
I have successfully created a billing agreement having setup fees $50. And when I look into my facilitator account, the same $50 is added to my balance. But how do I get confirmation about this? Can I get any payment id or anything else like that from which I can confirm that the amount paid is from the particular customer.

**Comment by omarkilani** [comment] 2016-08-01 22:56
@viper-pranish you can get this information from an IPN, if (big if) it's working at the time.

**Comment by viper-pranish** [comment] 2016-08-03 04:04
@omarkilani  Currently I am making initial payment for the subscription calculated on pro-rata basis as a 1 time credit card payment. Then for the next month, I create agreement. I could use setup_fee for creating agreements but as far as the discussions here, there seems to be some bugs in it? Is it?

**Comment by viper-pranish** [comment] 2016-08-03 04:06
@omarkilani  when does the agreement gets started and the first payment is made? Is it on the `agreement_start_date` or `next_billing_date` . I have been waiting for the agreement to get executed on the `agreement_start_date` but it is not getting executed.

**Comment by danadijans** [comment] 2016-08-16 23:16
HI @ppmtscory and @rachnatib ,

Is there any confirmation that this issue will be 100% resolved on/ by August 22nd? Has it made the release schedule etc?

Unfortunately previous indications of fixes in the past have been missed.

Thanks.

**Comment by danadijans** [comment] 2016-08-21 23:57
*bump* 
Any confirmation team? We're now at the 22nd!

**Comment by ppmtscory** [comment] 2016-08-22 16:25
@rachnatib is part of the team responsible for this change so I will defer to her.  I will follow up internally as well.

**Comment by rachnatib** [comment] 2016-08-23 15:51
Hi everyone,
Apologies for taking so long to respond. We are working actively to fix the issue but due to unanticipated delay in one of the components work we are delayed and the new LTS is 12th Sept2016. 
Pls bear with us as we work towards the finishing line.

Thx!

**Comment by omarkilani** [comment] 2016-08-23 16:22
:(

**Comment by sedrakpc** [comment] 2016-08-23 16:43
😢

**Comment by ppmtscory** [comment] 2016-09-12 14:16
All - since there are new services involved with this process, we're currently ramping them into traffic.  A certain percentage of traffic will be routed to these services, and barring any unforeseen consequences, we hope to have this 100% live by September 15th.  While this is being ramped, you may see some `setup_fee` payments charged immediately and you may see some take a few minutes as they do now.  We greatly appreciate your patience while we make sure that these new services don't have any unintended side effects.

**Comment by rachnatib** [comment] 2016-09-15 17:04
Hi everyone! The fix is now live.  Pls try and let us know if any more concerns.

**Comment by ppmtscory** [comment] 2016-09-16 20:29
Closing as this has been pushed live and verified.  We greatly appreciated your patience with us while we got this out there.

**Closed by ppmtscory** 2016-09-16 20:29 UTC
Labels: api-bug, api-subscription

**Comment by rdgreen16** [comment] 2016-09-27 06:20
Since this fix was announced I've had multiple failures it was working fine before the "live fix" come on PayPal!

**Comment by pikoloshanti** [comment] 2017-02-06 18:24
Can anyone confirm that when the agreement gets executed, paypal will return successful response ONLY if the setup_fee has been actually charged from customer's account?

We are switching from the paypal legacy api which had exactly those issues and would like to avoid falling into the same traps.

**Comment by cloud-tribal** [comment] 2017-02-27 22:31
Thanks for this. However some clarification is required.

The API docs state `initial_fail_amount_action` takes an enum: `CONTINUE` / `CANCEL`, but doesn't go into any detail about what they do.

What do

`initial_fail_amount_action: 'CANCEL'`

`initial_fail_amount_action: 'CONTINUE'`

do, specifically?

**Comment by 2tvenom** [comment] 2017-10-24 12:08
In sandbox agreement have state `Active`  but setup_fee not charged. How fix?

**Comment by dominhtri1995** [comment] 2019-02-27 19:19
THe problem in sandbox was never fixed. I still encounter this error in 2019 lol.

**Comment by jiteshtandel** [comment] 2019-03-22 15:35
Thanks for all this.

I wanted to charge a customer immediately. To do so, I configured following important parameters as mentioned in this issue thread.
frequency=week
frequency_interval=1
type=REGULAR

setup_fee=Euro 10.00
auto_bill_amount=no
**initial_fail_amount_action=CANCEL**
max_fail_attempts=0

However, I have enough balance in my card. The PayPal always failed initial amount and returns with "Cancelled " status after execute agreement API CALL.

I am talking about production environment.

I don't know what's the reason. How can we know the reason for failed initial amount?

How can we overcome this issue?

Please help. Thanks in advance.

**Comment by jiteshtandel** [comment] 2019-03-29 07:56
@ppmtscory 
I took Ajax Loop approach to know the exact status from the database table updated by IPN and Webhook notifications.
With this approach, the user has to wait around 3-4 minutes which I considered very bad user experience. I need quick notification. 
I suppose If we have exact payment status after "Execute Agreement" API call then it would be wonderful and very easy to integrate. Can we get the exact payment status after "Execute Agreement" API call?
If yes, please let me know. I always get "Active" state after "Execute Agreement" agreement API call.

**Comment by carnesca** [comment] 2020-02-14 23:50
@jiteshtandel are you still having this issue? Are you still using the solution you previously described?

**Comment by jiteshtandel** [comment] 2020-02-15 10:21
Actually, problem was in the Client's card. First, we resolved that card issue then after payment method is working smoothly. Card problem was very annoying but we resolved it.
I used the following configuration to charge the billing amount. 

**Payment Definition**    
name= Regular Payments
type=REGULAR
frequency=month
amount=10.00
currency=EURO

**Merchant Preferences** 
return_url=https://mysitename.com/return_url
cancel_url=https://mysitename.com/cancel_url
frequency=month
frequency_interval=1
type=REGULAR
setup_fee=10.00
currency= EURO
auto_bill_amount=yes
initial_fail_amount_action=CONTINUE
max_fail_attempts=0

**Agreement**
start_date = date("c", strtotime("+5 minutes"))
name="TEST NAME"
description="TEST LONG DESC"

Thanks to All
