### ISSUE TITLE
WARNING: Missing Accessor: PayPal\Auth\OAuthTokenCredential:setAccessToken

### ISSUE THREAD

**Issue by kevinbarbary** [paypal/PayPal-PHP-SDK#376] opened 2015-08-12 14:39 UTC
[12-08-2015 11:11:56] PayPal\Core\PayPalHttpConnection: INFO	: POST https://api.paypal.com/v1/oauth2/token
[12-08-2015 11:11:58] PayPal\Core\PayPalHttpConnection: INFO	: Response Status 	: 200
[12-08-2015 11:11:58] PayPal\Validation\ModelAccessorValidator: WARNING	: Missing Accessor: PayPal\Auth\OAuthTokenCredential:setAccessToken. Please let us know by creating an issue at https://github.com/paypal/PayPal-PHP-SDK/issues

This is an intermittent error on our live servers. Any help would be appreciated.

**Comment by jaypatel512** [comment] 2015-08-12 14:49
Hey @kevinbarbary !

Can you please pass a bit more context on when this happens ? I mean, what kind of call you are making during this process ? Payments ? Future Payments ? Authorization ? Any context would help determine this issue. 

Thanks.

**Comment by kevinbarbary** [comment] 2015-08-13 12:46
Hi,
This happens during a purchase, I have a shopping basket from which I submit the total cost of to PayPal for payment and sometimes it fails with the above error.

**Comment by jaypatel512** [comment] 2015-08-13 17:08
Hey @kevinbarbary !

I will try to reproduce this in my end. However, in the mean time, you should be able to disable the validation if you are using the latest version of our SDK. 

Here is the information on how to do that: https://github.com/paypal/PayPal-PHP-SDK/wiki/Validation

**Comment by jaypatel512** [comment] 2015-08-13 17:11
Also, it looks like the way you are using the code is creating this issue. In no place, you are required to set AccessToken by using that setMethod. If you are trying to do so, it may be that there is a more recommended way of doing it. You can checkout the [samples](https://github.com/paypal/PayPal-PHP-SDK/tree/master/sample) in our sdk, specially, [bootstrap.php](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/bootstrap.php), on how to setup the access token.

**Comment by kevinbarbary** [comment] 2015-08-14 10:59
OK, many thanks for your help - I'll try disabling the validation but I may not have time to look into the AccessToken usage until after next weekend.
Thanks again, I'll let you know how I get on.

**Comment by jaypatel512** [comment] 2015-08-14 15:59
Sounds good. Let me know, if you are using the access token in any different way than this.

**Comment by kevinbarbary** [comment] 2015-08-17 09:53
Hi,
I've checked the logs after disabling validation and unfortunately the issue persists. One purchase has been made since and it looks like the user got the error twice and on the third attempt the purchase went through.
I'll try to find some time to remove the part of the code which sets the AccessToken and let you know how I get on.

**Comment by jaypatel512** [comment] 2015-08-17 18:06
Interesting. 

Please let me know where you are setting the access token that way. I can help you refactor it to make it work with SDK better, and future proof :) 

I am closing this issue for now, as this is a valid warning. Will re-open if found otherwise.

**Closed by jaypatel512** 2015-08-17 18:06 UTC
Labels: question

**Comment by kevinbarbary** [comment] 2015-08-18 14:45
Hi,

Here's an extract of the code we have:

		if(!$testMode){
			$sdkConfig = array(
				"mode" => "live",
				'validation.level' => 'disable',
				'log.LogEnabled' => true,
				'log.FileName' => '/var/tmp/PayPal.log',
				'log.LogLevel' => 'FINE'
			);
		}else{
			$sdkConfig = array(
				"mode" => "sandbox",
				'log.LogEnabled' => true,
				'log.FileName' => '/var/tmp/PayPal.log',
				'log.LogLevel' => 'FINE'
			);
		}
		
		$cred = new \PayPal\Auth\OAuthTokenCredential(
			$this->getPaymentSetting($ClientID),
			$this->getPaymentSetting($ClientSecret),
			$sdkConfig
		);
		$cred->accessToken = $cred->getAccessToken($sdkConfig);
		$_SESSION['accessToken']=$cred->accessToken;
		$_SESSION['siteId']=$Transaction->SiteID;
		$_SESSION['siteDirectory']=$Site->SiteDirectory;
		$_SESSION['userId']=$Transaction->UserID;
		$_SESSION['basketId']=$Transaction->BasketID;
		$_SESSION['amount']=$Transaction->TransactionPrice;

		$apiContext = new \PayPal\Rest\ApiContext(
			$cred
		);

		$apiContext->setConfig(
			$sdkConfig
		);
		 
		try {
			$payer = new Payer();
			$payer->setPaymentMethod("paypal");

			$amount = new Amount();
			$amount->setCurrency('GBP');
			$amount->setTotal($ShoppingBasket->TotalPrice);

			$transaction = new Transaction();
			$transaction->setDescription("creating a payment");
			$transaction->setAmount($amount);
			$transaction->setItemList($itemList);
			$transaction->setDescription("Payment description");
			$transaction->setInvoiceNumber(uniqid());

			$payment = new Payment();
			$payment->setIntent("sale");
			$payment->setPayer($payer);
			$payment->setRedirectUrls($redirectUrls);
			$payment->setTransactions(array($transaction));
			$payment->create($apiContext);
			$approvalUrl = $payment->getApprovalLink();
			$arrResponse = $this->requestPost($approvalUrl, $strTransaction);
			echo '<script language="javascript">window.top.location.href="'.$approvalUrl.'";</script>';
			echo '<a href="' . $approvalUrl . '">If you are not automatically redirected to PayPal in 10 seconds please click here.</a>';
		} catch (Exception $ex) {
			// error

		}

**Comment by jaypatel512** [comment] 2015-08-18 17:21
Great ! Thanks.

I see the culprit here:

```php
$cred->accessToken = $cred->getAccessToken($sdkConfig);
$_SESSION['accessToken']=$cred->accessToken;
```
Unless you are using the given accessToken for any specific reason, there is no need for you to store that in the session. The accessToken is used only to make calls to the PAyPal APIs, and they do expire after certain period of time. If they expire, they are automatically re-created.

Please remove those two lines and you should be fine.

**Comment by kevinbarbary** [comment] 2015-08-19 09:45
Hi,

The accessToken is stored in the session so that it can later be used in a cURL session thus:

	$payment_execute = array(
		'payer_id' => $_GET["PayerID"]
	);

	$postdata = json_encode($payment_execute);

	$curl = curl_init("https://api.paypal.com/v1/payments/payment/".$_GET["paymentId"]."/execute/"); 
	...
	curl_setopt($curl, CURLOPT_HTTPHEADER, array(
				'Authorization: Bearer '.$accessToken,
				'Accept: application/json',
				'Content-Type: application/json'
				));
	curl_setopt($curl, CURLOPT_POSTFIELDS, $postdata);

**Comment by jaypatel512** [comment] 2015-08-19 15:44
Oh ! You do not need to use curl request for any API operations in Paypal, if you are using the SDK. Here are the sample source that explains how to do an express checkout (Pay with PayPal), and execute them. You can also run the samples in your local machines to get an idea of how it works. Its extremely easy to setup samples.

Sample Setup: https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples
Create Payment: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingPayPal.html
Execute Payment: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/ExecutePayment.html

Also, there are many more samples you can view online: http://paypal.github.io/PayPal-PHP-SDK/sample/

**Comment by kevinbarbary** [comment] 2015-08-19 15:52
Thanks. Looks like we won't be using this contractor again.

**Comment by jaypatel512** [comment] 2015-08-19 15:54
@kevinbarbary ! I think he did good for most part except this. Also, we are adding more and more documentation nowadays, to help developers get the most out of the SDK. 

I would recommend him going through the [SDK wiki](https://github.com/paypal/PayPal-PHP-SDK/wiki)

**Comment by jaypatel512** [comment] 2015-08-19 16:05
Also, @kevinbarbary ! 

I think the fault is on our part than the contractor. Improper documentation or lack of information may have caused him to use the curl option. If we would have done our job better, we potentially could have let the developer get it right in the first place. This motivates me to find ways to make it even easier for developers to use our SDKs.
