### ISSUE TITLE
Payment token is not available in the Payment creation API call, must be parsed from the approval_url link

### ISSUE THREAD

**Issue by PhoneixS** [paypal/PayPal-PHP-SDK#832] opened 2017-04-28 09:34 UTC
When a payment execution is canceled by the user, is redirected to the cancel URL. In this cancel URL you only recibe the express checkout token not its id. The problem is that when you create the payment (`$payment->create()`) this token is only found in the approval_url so you must parse it to extract and save it in your DB.

It could be better if the api already have this token filled after creating the payment.

This is the same issue as https://github.com/paypal/PayPal-NET-SDK/issues/24 but for PHP so look at it if what I mean isn't clear.

They fixed this parsing the URL after receiving the response and setting a token property in the Payment object. I think we could have more or less the same.

**Comment by xiaoleih41** [comment] 2017-04-28 20:34
I am submitting a request on this.

**Comment by xiaoleih41** [comment] 2017-05-01 18:53
. We are actually working on adding the payment ID to the cancel URL. The issue is being tracked here https://github.com/paypal/PayPal-REST-API-issues/issues/29.  We are also submitting a pull request to add the token object to the response.

**Comment by xiaoleih41** [comment] 2017-05-05 14:23
'getToken()' has been added to payment class of the SDK. Close this issue as it has been solved.

**Closed by xiaoleih41** 2017-05-05 14:23 UTC
Labels: sdk-enhancement
