### ISSUE TITLE
Reauthorize: An internal service error occurred.

### ISSUE THREAD

**Issue by shahankitb997** [paypal/PayPal-PHP-SDK#837] opened 2017-05-03 09:31 UTC
Mode: Sandbox 

When I run 

`https://api.sandbox.paypal.com/v1/payments/authorization/XXXXXXX/reauthorize`

It gives

**An internal service error occurred.**

For more info & code

http://stackoverflow.com/questions/43583789/paypal-unable-to-reauthorize-authorized-payment-error-an-internal-service-err

**Comment by xiaoleih41** [comment] 2017-05-03 15:33
Please create a new authorization and then re-authorize it after three days. Please provide the newest debug_ID for us to do troubleshooting.  

Re-authorization supports only the amount request parameter. You can re-authorize a payment only once from four to 29 days. A [re-authorized](https://developer.paypal.com/docs/api/payments/#authorization_reauthorize) payment itself has a new three-day honor period. You can re-authorize a transaction once for up to 115% of the originally authorized amount, not to exceed an increase of $75 USD.

**Comment by shahankitb997** [comment] 2017-05-04 01:16
I have created Authozation Id: 1C599096RA419354J with 45 SGD On 2017-04-25 11:44:01. Trying to reauthorize still it gives same error. Debug Id : 80f1ca1045b13 / 970bb684e9670.

Please let me know if can what is wrong with StackOverflow corePHP.

Thanks

**Comment by xiaoleih41** [comment] 2017-05-08 14:11
I could not get any more detail on why the transaction failed from the debug ID. I am checking with product to see if there's another way to figure out the cause of it.

**Comment by pp-randy** [comment] 2017-05-12 15:50
@shahankitb997 would you be able to provide a new debug id to help with our investigation?

**Comment by shahankitb997** [comment] 2017-05-15 01:11
I already given Debug Id : 80f1ca1045b13 / 970bb684e9670 Or Debug Id : 2d75fc7af01b1

**Comment by pp-randy** [comment] 2017-05-15 13:54
Thank you for the newer debug id 2d75fc7af01b1.

**Comment by pp-randy** [comment] 2017-05-15 14:07
Did the new debug id (2d75fc7af01b1) return a 200 OK response instead of an INTERNAL_ERROR?  Are you still able to reproduce this? 

I'm not able to get logs on your previous debug_ids which is why I am asking for new ones.

**Comment by pp-randy** [comment] 2017-05-19 13:42
Closing the issue, please let us know if you are able to provide more recent debug_ids so we can continue our investigation.

**Closed by pp-randy** 2017-05-19 13:42 UTC
Labels: question
