### ISSUE TITLE
Error from Paypal response: Method PayPal\Api\Capture::getTransactionFee() does not exist

### ISSUE THREAD

**Issue by justiniso** [paypal/PayPal-PHP-SDK#256] opened 2015-02-26 21:17 UTC
Since early this morning, we started receiving these errors from the paypal SDK 0.13.0. 

    Error from Paypal response: Method PayPal\Api\Capture::getTransactionFee() does not exist

Merchant technical support seems to have no knowledge of the issue.

It seems that this method did not even exist until it was authored 23 days ago and exists only in the latest version:
https://github.com/paypal/PayPal-PHP-SDK/commit/ec46c397fe2d1b9e2357412e3b8ccc34fe04bf7e#diff-d50fbe02bce07374b24321cb3a114e66

We have not found exactly what is executing that, but Paypal is either sending this as a callback from their server (really guys?!) or this is somehow getting included in the response. Please fix your API's backwards-compatibility. I cannot believe PayPal would be so cavalier and irresponsible about updating their API without notifying their merchants or properly deprecating. We have already experienced a severe financial impact and I cannot imagine the millions of dollars merchants have lost from this.

**Comment by jaypatel512** [comment] 2015-02-26 21:22
Duplicate of https://github.com/paypal/PayPal-PHP-SDK/issues/255.

Please update your SDK to [latest version v1.2.1](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.2.1). The fix has been applied and released recently. This was actually a forward-compatibility issue, that happened because of SDK not being able to handle the case where a new object was created in future APIs. 

Apologies for having this issue happening on Live environment.

**Closed by jaypatel512** 2015-02-26 21:22 UTC

**Comment by justiniso** [comment] 2015-02-26 21:31
@jaypatel512 thanks for your quick response. Just to be clear, the official word from Paypal is that you now dropped support for all versions of the SDK older than 1.2.1?
