### ISSUE TITLE
Agreement::get() not updating with all information

### ISSUE THREAD

**Issue by zanderwar** [paypal/PayPal-PHP-SDK#956] opened 2017-10-20 03:11 UTC
Agreement is successfully created:

```
        $agreementDescription = sprintf('%s Ref:%s', $paymentPlan->Title, $store->ID);

        $agreement = new Agreement();
        $agreement->setName('Payment Agreement')->setDescription($agreementDescription)->setStartDate($this->getAgreementStartDate($paymentPlan));

        $plan = new Plan();
        $plan->setId($paymentPlan->PlanID);

        $payer = new Payer();
        $payer->setPaymentMethod('paypal');

        $agreement->setPayer($payer);
        $agreement->setPlan($plan);

        $data = json_decode($store->Data, true);

        try {
            $agreement = $agreement->create($context);
            Logger::add(sprintf('Created billing agreement: %s (%s %s)', $agreementDescription, $data['FirstName'], $data['Surname']));
        } catch (PayPalConnectionException $ex) {
            Logger::add(sprintf('Failed to create billing agreement: %s %s', $ex->getCode(), $ex->getData()));
            return $this->httpError(500);
        } catch (\Exception $ex) {
            Logger::add(sprintf('Failed to create billing agreement: %s', $ex->getCode()));
            return $this->httpError(500);
        }
```

and executed perfectly fine:

```
$agreement = new Agreement();

        try {
            $agreement->execute($token, $apiContext);
        } catch (\Exception $e) {
            Logger::add(sprintf('Error executing agreement: %s %s', $token, $e->getMessage()));
            return false;
        }
```

and fetched perfectly fine

```php
$agreement = Agreement::get($data['billing_agreement_id'], $apiContext);
```

however

`$agreement->getName()` = NULL
`$agreement->getDescription()` = 'The description I set correctly above'
`$agreement->getPlan()->getId()` = NULL

Note:

In the recurring payments dashboard of paypal. The Description comes through as the Agreement Name.

**Comment by xiaoleih41** [comment] 2017-10-20 18:38
You are right by looking at the Get agreement response object.  It doesn't contain agreement name or Billing plan ID. The missing billing plan ID is tracked at https://github.com/paypal/PayPal-REST-API-issues/issues/92.  I will submit an issue to request the name to be added to Get billing agreement response object too.

**Comment by zanderwar** [comment] 2017-10-20 20:56
I see that's been dated back to June. 

It's paramount that I know exactly what plan an agreement is on so that I can increment customers time on their account accordingly, unfortunately this led me to having to create a lot of redundant functionality and database entries along with some guess work. 

Do you have an alternate method in mind, as one would assume when you "get" an agreement, you should have in excess; all the information you could possibly desire about that agreement.

I don't wanna say the word slack here, but that's 5 months of waiting for something that should obviously be there before release

**Comment by xiaoleih41** [comment] 2017-10-25 14:45
@zanderwar Thank you for your feedback. I have forwarded it to the product team. The discussion thread of the above issue showed the possible workaround. Will update the thread once it's solved.

**Comment by pp-randy** [comment] 2017-11-13 16:35
Closing as the issue is being tracked here: https://github.com/paypal/PayPal-REST-API-issues/issues/92

**Closed by pp-randy** 2017-11-13 16:35 UTC

**Comment by Nikhilchudasama** [comment] 2019-11-28 12:17
when i fetched agreement details missing plan id on response, can any one help how to solve this issue in my billing agreement. 
show in api details it come with this link https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_get 
but PHP SDK agreement not come.
Thank for advance.

**Comment by prakash-gangadharan** [comment] 2019-11-28 16:01
@Nikhilchudasama , can you help us with the `Paypal-Debug-Id` ?
