### ISSUE TITLE
failed setting cipher list 

### ISSUE THREAD

**Issue by 33sKamal** [paypal/PayPal-PHP-SDK#1053] opened 2018-02-06 12:39 UTC
i'm using **Laravel** and **payPal-PHP-SDK** to build some
i process payment **locally** everything seem great,  but when i did upload it to shared hosting ; i got this message shown  on the picture 
----

![capture](https://user-images.githubusercontent.com/19997864/35860120-b6481aee-0b3a-11e8-96bf-83556549ca27.JPG)

---
Need help please

**Comment by xiaoleih41** [comment] 2018-02-06 16:38
This might have been caused by the cipher suite you have specified that is not compatible with us. Please choose one of the below to connect to us instead. 
```# TLS 1.2 
TLS_RSA_WITH_AES_256_CBC_SHA256 (0x3d)   256
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)   256
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)   128
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)   112
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   ECDH secp384r1 (eq. 7680 bits RSA)   FS    256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)   ECDH secp384r1 (eq. 7680 bits RSA)   FS    256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH secp384r1 (eq. 7680 bits RSA)   FS    256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)   ECDH secp384r1 (eq. 7680 bits RSA)   FS    128
# TLS 1.1 
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)   256
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)   128
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)   112
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH secp384r1 (eq. 7680 bits RSA)   FS    256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)   ECDH secp384r1 (eq. 7680 bits RSA)   FS    128
# TLS 1.0 
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)   256
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)   128
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)   112
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH secp384r1 (eq. 7680 bits RSA)   FS    256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)   ECDH secp384r1 (eq. 7680 bits RSA)   FS    128
TLS_RSA_WITH_RC4_128_SHA (0x5)   128
TLS_RSA_WITH_RC4_128_MD5 (0x4)   128```

**Comment by xiaoleih41** [comment] 2018-02-08 16:40
Close this issue as the answer has been provided.

**Closed by xiaoleih41** 2018-02-08 16:40 UTC

**Comment by 33sKamal** [comment] 2018-02-08 17:09
Sorru Sir i can't release what you mean

**Comment by xiaoleih41** [comment] 2018-02-08 20:02
You site might be running an old version of Open SSL. To connect to PayPal endpoint, you will need to be able to support TLSv1.2  which means you should at least upgrade to OpenSSL 1.01
