### ISSUE TITLE
Invalid client, Client Authentication failed

### ISSUE THREAD

**Issue by Levelleor** [paypal/PayPal-PHP-SDK#925] opened 2017-09-17 01:04 UTC
* SDK/Library version: Last one, I guess...
* Environment: Production issue
* Language, language version, and OS: PHP 7, Win10

I couldn't find the links to make requests to when was changing the environment to Live. I use these right now: 
Token: https://api.paypal.com/v1/oauth2/token
Create payment: https://api.paypal.com/v1/payments/payment
Execute: https://api.paypal.com/v1/payments/payment/paymentID/execute/
Receipt: https://api.paypal.com/v1/payments/payment/paymentId

I get this error: 
`{"error":"invalid_client","error_description":"Client Authentication failed"}`

I know what it means, but there is a lot of different factors that might cause it. May you list all the requirements for transition to the production environment? I would really appreciate that.

**Comment by xiaoleih41** [comment] 2017-09-18 16:23
Please provide the `debugId` of the API call.  Please make sure that you are using the live credential associated with your live REST App that is making the API calls.

**Comment by Levelleor** [comment] 2017-09-19 13:13
How do I get `debugId`? I thought it should be in the answer body, but the line I sent before was the whole reply from PayPal. 

Anyway, the problem is not in code or PayPal, everything seems working fine on my account, but my client has some problems with that. He has a credit card connected to account, I thought that's enough to have a business account and make this work. Are there any other requirements for an account to work with PayPal SDK?

**Comment by xiaoleih41** [comment] 2017-09-19 13:47
Did you use your client's API credential to make the call? That could be the cause. the `debugId` should be located at the header of the API response.

**Comment by Levelleor** [comment] 2017-09-19 21:21
Yup. I mean how should I pass all of this to him if not with his credentials? 

Debug ID: ae6ba7ad54d9a

**Comment by xiaoleih41** [comment] 2017-09-19 22:17
I got the error message shows that the client ID you have passed on is invalid. Please double check on that. As it's public forum. I can't discuss account specific detail. If after you copy and paste the client id still doesn't solve the issue, you may open a ticket with the same debugId  at www.paypal-techsupport.com to get more account specific support.

**Comment by xiaoleih41** [comment] 2017-09-20 14:13
Close this issue as the answer has been given.

**Closed by xiaoleih41** 2017-09-20 14:13 UTC

**Comment by Levelleor** [comment] 2017-09-20 15:51
ср, 20 сент. 2017 г. в 10:13, Xiaolei Wheelock <notifications@github.com>:

**Comment by xiaoleih41** [comment] 2017-09-20 16:53
The `clientId` doesn't seem to be correct, that was my finding. If you need more in detail assistance, please file a ticket at  www.paypal-techsupport.com to get more account specific support as I cannot disclose your live account info on this public forum.
