### ISSUE TITLE
Webhook verification from simulator always fails

### ISSUE THREAD

**Issue by TJBIII** [paypal/PayPal-PHP-SDK#720] opened 2016-11-17 20:00 UTC
### Required Information

- PHP Version: PHP 5.5.19
- PayPal-PHP-SDK Version: 1.10.0
- Debug ID(s): d6cbd6047e486

### Issue Description

I am using a webhook for payout batch event notifications. I followed the example webhook validation as described in the [docs](http://paypal.github.io/PayPal-PHP-SDK/sample/doc/notifications/ValidateWebhookEvent.html). I always receive `{ "verification_status": "FAILURE"}` as the response. I am in sandbox mode and firing the notification from the webhook simulator in the developer dashboard.

Here is an example of my post data for the verification request:
```
{
   "auth_algo":"SHA256withRSA",
   "transmission_id":"505fcad0-acfc-11e6-8e5f-13662a490b19",
   "cert_url":"https://api.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-df8cd2d5",
   "webhook_id":"2A9741408B151863U",
 "transmission_sig":"ks91bo8HXCMsQBrXKOyOrs46KJkTVZRA7Az2oArXKNNaSxnMHENKIBUv4yOolVplwwFC1+u1pF1fIqRysqFgpgnQ8i8huROBJHiKaN9BeBdm1qnQiXyF7CSmHJ4MDVAQPvB1zHncbnJ5lIbzOhFm9TRLp7CaFk8IXNvCR6FTO5jqwfhpzTmf5k1MRbneexbnjmipQ9P3IDmKpAGLxweN/THixXgmC2GMdIIfVHCXZ8bvhcKPeMJ/0J8DQxlwpOteRbEYY25Kkpaej1ZhzAZ9/JjfxEZnARcax0i/O5ht8GOGPBhOUYKB19u1ZHxjoWEDUrrE1GDJOklNUpmqIPRug==",
   "transmission_time":"2016-11-17T19:30:36Z",
   "webhook_event":{
      "id":"WH-9J627718KS478452F-0TT97515BN811434B",
      "event_version":"1.0",
      "create_time":"2015-09-14T13:18:15Z",
      "resource_type":"payouts",
      "event_type":"PAYMENT.PAYOUTSBATCH.PROCESSING",
      "summary":"Payouts batch is getting processed.",
      "resource":{
         "batch_header":{
            "payout_batch_id":"X24X9BJL2UK52",
            "batch_status":"PROCESSING",
            "time_created":"2015-09-14T13:18:13Z",
            "sender_batch_header":{
               "sender_batch_id":"ISO-22"
            },
            "amount":{
               "currency":"USD",
               "value":"12.43"
            },
            "fees":{
               "currency":"USD",
               "value":"0.5"
            },
            "payments":2
         },
         "links":[
            {
               "href":"https://api.paypal.com/v1/payments/payouts/X24X9BJL2UK52",
               "rel":"self",
               "method":"GET"
            }
         ]
      },
      "links":[
         {
            "href":"https://api.paypal.com/v1/notifications/webhooks-events/WH-9J627718KS478452F-0TT97515BN811434B",
            "rel":"self",
            "method":"GET"
         },
         {
            "href":"https://api.paypal.com/v1/notifications/webhooks-events/WH-9J627718KS478452F-0TT97515BN811434B/resend",
            "rel":"resend",
            "method":"POST"
         }
      ]
   }
}
```

CURL_HEADER_OUT:
```
POST /v1/notifications/verify-webhook-signature HTTP/1.1
Host: api.sandbox.paypal.com
Accept: */*
Content-Type: application/json
User-Agent: PayPalSDK/PayPal-PHP-SDK 1.10.0
Authorization: Bearer <my access token>
PayPal-Request-Id: 288679526856147939137562357
Content-Length: 1535
```

The response:
```
 HTTP/1.1 200 OK
Date: Thu, 17 Nov 2016 19:30:42 GMT
Server: Apache
PROXY_SERVER_INFO: host=slcsbplatformapiserv3002.slc.paypal.com;threadId=541
Paypal-Debug-Id: d6cbd6047e486
CORRELATION-ID: d6cbd6047e486
Content-Language: *
Paypal-Debug-Id: d6cbd6047e486
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dplatformapiserv%26TIME%3D1644506712%26HTTP_X_PP_AZ_LOCATOR%3D; Expires=Thu, 17 Nov 2016 20:00:42 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Vary: Authorization
Content-Length: 33
Connection: close
Content-Type: application/json

{"verification_status":"FAILURE"}
```

**Comment by pp-randy** [comment] 2016-11-17 23:12
I have my listener created and working on verification.  

Do you know @TJBIII does verification work for you with a sandbox generated webhook and not one from the simulator?

**Comment by TJBIII** [comment] 2016-11-17 23:22
@pp-randy I do not know. I have only tried through the webhook simulator.

**Comment by jurgenhaas** [comment] 2016-11-18 13:41
I've got the same problem and thanks to the question from @TJBIII I've then tried a sanbox payment with the result that I get a SUCCESS from the verification. So it seems that the verification only fails with the simulator.

**Comment by pp-randy** [comment] 2016-11-18 14:37
@jurgenhaas thank you for the information that is very helpful.

**Comment by pp-randy** [comment] 2016-11-18 15:35
Internal Tracking: SRE-44062

**Comment by webface** [comment] 2016-11-21 15:15
<img width="894" alt="screen shot 2016-11-21 at 9 48 53 am" src="https://cloud.githubusercontent.com/assets/681890/20487966/611f1dec-afd3-11e6-81ba-2922d368c3f4.png">

Now the webhook events appear to be broken for 3 days now.

**Comment by pp-randy** [comment] 2016-11-21 16:00
You have No Apps showing in the Left Drop Down.  Can you log out and try again?  It is working for me at this time.

**Comment by webface** [comment] 2016-11-21 17:07
@pp-randy Yes the left dropdown is now showing no apps. I have logged out and logged in on different browsers. Same result.

**Comment by pp-randy** [comment] 2016-11-21 17:12
@webface can you reach out to PayPal Technical Support for the webhooks not displaying on your Developer Dashboard?  Contact them at https://www.paypal-techsupport.com/app/ask/

**Comment by webface** [comment] 2016-11-21 18:01
Now awaiting their response

**Comment by azngeek** [comment] 2016-11-24 15:43
+ 1 . Seems to be a global problem.

**Comment by webface** [comment] 2016-11-25 19:12
The Paypal "Engineers" are looking into it. Will post when I get more updates

**Comment by NazirNoori44** [comment] 2016-12-01 03:22
Was anyone able to get any progress on this?

My webhook verifications always return FAILURE as well from the webhook simulator. When I try to pay an invoice through sandbox to trigger a webhook notification, it deson't seem like it's firing because when I go to the "Webhook Events" section on the developer portal, it's not showing any new webhook notifications. My last one was from Nov 25 but nothing from my tests today.

**Comment by webface** [comment] 2016-12-01 17:48
Nothing from paypal yet. Webhooks verification still report FAILURE on all counts and the webhook events are still not showing up on the dashboard. This has been over 2 weeks. Paypal cmon!

**Comment by pp-randy** [comment] 2016-12-01 19:22
@webface what is your PayPal Support ticket number?

**Comment by webface** [comment] 2016-12-01 19:24
@pp-randy  Reference # 161121-000262

**Comment by pp-randy** [comment] 2016-12-01 19:32
Thank you @webface I will escalate the dashboard issue.  My dashboard is also not working, but my sandbox webhooks are sending.  Are you at least getting the webhooks? 

------------------------------
Sandbox Webhook Dashboard No Apps showing
Internal Tracking: PPPLMER-23680

**Comment by webface** [comment] 2016-12-01 19:33
Im getting the webhooks but the verification fails as well as the dashboard issue.

**Comment by pp-randy** [comment] 2016-12-01 20:28
@webface are you able to provide the request JSON you are sending?  

This some times trips me up, but double check the webhook id parameter matches the webhook id from your REST API app.
![image](https://cloud.githubusercontent.com/assets/6819909/20811197/64b31286-b7d2-11e6-8257-3c3a3f90f338.png)

**Comment by webface** [comment] 2016-12-01 20:35
Event Data Sent. The webhook ID doesnt match my webhook id. When I make a payment, the webhook ids dont match either. Maybe thats why the verification fails.
`{
	"id": "WH-0T490472X6099635W-7LJ29748BW389372K",
	"create_time": "2015-09-25T23:14:14Z",
	"resource_type": "invoices",
	"event_type": "INVOICING.INVOICE.PAID",
	"summary": "An invoice was created",
	"resource": {
		"total_amount": {
			"currency": "USD",
			"value": "1.00"
		},
		"status": "PAID",
		"links": [
			{
				"rel": "self",
				"href": "https://api.paypal.com/v1/invoicing/invoices/INV2-8FSD-3HT6-BRHR-UHYV",
				"method": "GET"
			}
		],
		"number": "MM00063",
		"invoice_date": "2015-09-28 PDT",
		"tax_inclusive": false,
		"merchant_info": {
			"email": "example@outlook.com",
			"first_name": "Dennis",
			"last_name": "Doctor",
			"business_name": "Medical Professional LLC",
			"address": {
				"line1": "1234 Main St",
				"line2": "Apt 302",
				"city": "Portland",
				"state": "OR",
				"postal_code": "97217",
				"country_code": "US"
			}
		},
		"billing_info": [
			{
				"email": "example@example.com",
				"business_name": "Medical Professionals LLC",
				"language": "en_US"
			}
		],
		"payment_term": {
			"term_type": "DUE_ON_RECEIPT",
			"due_date": "2015-09-28 PDT"
		},
		"id": "INV2-8FSD-3HT6-BRHR-UHYV",
		"items": [
			{
				"name": "Sample Item",
				"quantity": 1,
				"unit_price": {
					"currency": "USD",
					"value": "1.00"
				},
				"unit_of_measure": "QUANTITY"
			}
		],
		"payments": [
			{
				"type": "PAYPAL",
				"transaction_id": "22592127VV907111U",
				"transaction_type": "SALE",
				"method": "PAYPAL",
				"date": "2015-09-28 14:37:13 PDT"
			}
		],
		"tax_calculated_after_discount": true,
		"paid_amount": {
			"paypal": {
				"currency": "USD",
				"value": "1.00"
			}
		},
		"metadata": {
			"created_date": "2015-09-28 14:35:46 PDT",
			"last_updated_date": "2015-09-28 14:37:13 PDT",
			"first_sent_date": "2015-09-28 14:35:47 PDT",
			"last_sent_date": "2015-09-28 14:35:47 PDT"
		}
	},
	"links": [
		{
			"href": "https://api.paypal.com/v1/notifications/webhooks-events/WH-0T490472X6099635W-7LJ29748BW389372K",
			"rel": "self",
			"method": "GET",
			"encType": "application/json"
		},
		{
			"href": "https://api.paypal.com/v1/notifications/webhooks-events/WH-0T490472X6099635W-7LJ29748BW389372K/resend",
			"rel": "resend",
			"method": "POST",
			"encType": "application/json"
		}
	],
	"event_version": "1.0"
}`

**Comment by webface** [comment] 2016-12-01 20:36
Sorry for the messy code.

**Comment by pp-randy** [comment] 2016-12-01 20:39
What you provided looks like the webhook data that was sent to you, so this is one of the values you provide it as "webhook_event" value.   Look at what beginning comment https://github.com/paypal/PayPal-PHP-SDK/issues/720#issue-190148170 it has the correct structure.

**Comment by pp-randy** [comment] 2016-12-01 20:40
The other fields with exception to webhook_id you get from the headers https://developer.paypal.com/docs/api/webhooks/#verify-webhook-signature

**Comment by webface** [comment] 2016-12-01 20:43
Im using the php sdk.. here is my current code with a mailto function to debug:
`
    function validate_webhook() {
        $bodyReceived = file_get_contents('php://input');
        $headers = getallheaders();
        $headers = array_change_key_case($headers, CASE_UPPER);

        $signatureVerification = new VerifyWebhookSignature();
        $signatureVerification->setAuthAlgo($headers['PAYPAL-AUTH-ALGO']);
        $signatureVerification->setTransmissionId($headers['PAYPAL-TRANSMISSION-ID']);
        $signatureVerification->setCertUrl($headers['PAYPAL-CERT-URL']);
        $signatureVerification->setWebhookId("46305473VL4472144"); // Note that the Webhook ID must be a currently valid Webhook that you created with your client ID/secret.
        $signatureVerification->setTransmissionSig($headers['PAYPAL-TRANSMISSION-SIG']);
        $signatureVerification->setTransmissionTime($headers['PAYPAL-TRANSMISSION-TIME']);

        $webhookEvent = new WebhookEvent();
        $webhookEvent->fromJson($bodyReceived);
        $signatureVerification->setWebhookEvent($webhookEvent);
        $request = clone $signatureVerification;

        try {
            /** @var \PayPal\Api\VerifyWebhookSignatureResponse $output */
            $output = $signatureVerification->post($this->apiContext);
        } catch (PayPal\Exception\PayPalConnectionException $ex) {
            echo $ex->getCode(); // Prints the Error Code
            echo $ex->getData(); // Prints the detailed error message 
            die($ex);
        } catch (Exception $ex) {
            die($ex);
        }
        
        include_once ($modx->config['base_path'] . "manager/includes/controls/class.phpmailer.php");
        $mail = new PHPMailer();
        $mail->IsMail();
        $mail->IsHTML(TRUE);
        $mail->From = "no-reply@me.ca";
        $mail->FromName = $modx->config['site_name'];
        $mail->Subject = "Citywide Training Webhook Submission";
        $mail->Body = $output->getVerificationStatus();
        $this->AddAddressToMailer($mail, "to", 'me@me.ca');
        $mail->send();
        return $bodyReceived;
        if ($output->getVerificationStatus() === 'SUCCESS') {
            return $bodyReceived;
        }
    }

    function AddAddressToMailer(&$mail, $type, $addr) {
        $a = explode(",", $addr);
        for ($i = 0; $i < count($a); $i++) {
            if (!empty($a[$i])) {
                if ($type == "to")
                    $mail->AddAddress($a[$i]);
                elseif ($type == "cc")
                    $mail->AddCC($a[$i]);
                elseif ($type == "bcc")
                    $mail->AddBCC($a[$i]);
                elseif ($type == "replyto")
                    $mail->AddReplyTo($a[$i]);
            }
        }
    }`

**Comment by pp-randy** [comment] 2016-12-01 20:48
To make sure we are on the same page, this does or does not match the webhook_id from your REST App on the developer dashboard? 
   `$signatureVerification->setWebhookId("46305473VL4472144"); `

**Comment by webface** [comment] 2016-12-01 20:49
Thats the webhook id on my developer dashboard

**Comment by pp-randy** [comment] 2016-12-01 20:51
You said the webhook_id was incorrect before and you just fixed it or it was correct and your verification still failed?  Sorry for my confusion, just need to be clear that its still failing with everything looking correct.

**Comment by webface** [comment] 2016-12-01 20:53
The webhook id on my dashboard and in my code have always been the same. The returned json from the webhook event is what doesnt match up. When I make payments, my invoice ids are correct just the response doesnt have a matching webhook id.

**Comment by pp-randy** [comment] 2016-12-01 20:58
I will run some tests on invoice webhooks to double check, as this could also be something for just invoices especially if your webhook verification works for other forms of payment.

**Comment by webface** [comment] 2016-12-01 20:59
I've only tried it for invoices with no luck

**Comment by NazirNoori44** [comment] 2016-12-02 02:44
I'm also using pretty much the same code as webface and my call to getVerificationStatus() always returns failure as well. I've only tried invoice webhook events, this is the only type of payment in scope of my application. My sandbox webhook events on my dashboard also does not show any new events that I'm trying to trigger, seems bugged and not updating. Let me know if you need any further info.

**Comment by pp-randy** [comment] 2016-12-02 02:51
@webface was that invoice from Production? The webhook shows production URLs.  If not that is probably the problem and the actual sandbox webhook is malformed.

**Comment by pp-randy** [comment] 2016-12-02 02:57
Also got word the webhook simulator webhooks will not pass validation so I will be looking into getting the documentation a little clearer on that.

**Comment by webface** [comment] 2016-12-02 15:10
@pp-randy The invoice was generated in the sandbox and paid in the sandbox environment

**Comment by pp-randy** [comment] 2016-12-02 16:30
@webface that webhook is a Production Webhook from 2015.  You recently just got that testing in sandbox?

**Comment by pp-randy** [comment] 2016-12-02 16:32
The example webhook you provided is the webhook from the webhook simulator, those won't validate.

**Comment by webface** [comment] 2016-12-02 17:09
This is a webhook payload from the sandbox. This one is not from the simulator. It deosnt validate either.
`{
    "id": "WH-37J41080EA804702L-8YX90722YV0026639",
    "event_version": "1.0",
    "create_time": "2016-12-02T17:04:51Z",
    "resource_type": "invoices",
    "event_type": "INVOICING.INVOICE.PAID",
    "summary": "An invoice has been paid",
    "resource": {
        "invoice": {
            "id": "INV2-38HD-4UKV-RX2E-EEAT",
            "number": "0101",
            "templateId": "TEMP-529800116J311113X",
            "uri": null,
            "status": "PAID",
            "merchantInfo": {
                "email": "accounts-facilitator@webfacemedia.com",
                "firstName": "Citywide",
                "lastName": "Training",
                "businessName": "Humber College",
                "phone": {
                    "countryCode": "001",
                    "nationalNumber": "5032141716",
                    "extension": null
                },
                "fax": null,
                "website": null,
                "address": {
                    "line1": "1234 Main St.",
                    "line2": null,
                    "city": "Portland",
                    "state": "OR",
                    "postalCode": "97217",
                    "countryCode": "US",
                    "phone": null
                },
                "additionalInfo": null,
                "additionalInfoLabel": null,
                "taxId": null
            },
            "billingInfo": [
                {
                    "email": "webface@gmail.com",
                    "firstName": null,
                    "lastName": null,
                    "businessName": "Tribute Entertainment",
                    "phone": null,
                    "fax": null,
                    "website": null,
                    "address": {
                        "line1": "1920 Eglington Avenue West",
                        "line2": null,
                        "city": "Scarborough",
                        "state": "SK",
                        "postalCode": "M1N1R3",
                        "countryCode": "CA",
                        "phone": null
                    },
                    "additionalInfo": "This is the billing Info",
                    "additionalInfoLabel": null,
                    "language": null,
                    "notificationPreference": null
                }
            ],
            "shippingInfo": {
                "email": null,
                "firstName": "John Doe",
                "lastName": null,
                "businessName": "Tribute Entertainment",
                "phone": {
                    "countryCode": "001",
                    "nationalNumber": "6479668624",
                    "extension": null
                },
                "fax": null,
                "website": null,
                "address": {
                    "line1": "1920 Eglington Avenue West",
                    "line2": null,
                    "city": "Scarborough",
                    "state": "SK",
                    "postalCode": "M1N1R3",
                    "countryCode": "CA",
                    "phone": null
                },
                "additionalInfo": null,
                "additionalInfoLabel": null
            },
            "ccInfo": null,
            "reference": null,
            "items": [
                {
                    "name": "Nasa Training Shuttles",
                    "description": null,
                    "quantity": 1,
                    "unitPrice": {
                        "currencyCode": "CAD",
                        "value": "45.01"
                    },
                    "tax": {
                        "taxId": null,
                        "uri": null,
                        "name": "HST Tax on Event",
                        "percent": 13,
                        "amount": {
                            "currencyCode": "CAD",
                            "value": "5.85"
                        },
                        "merchantAccountNumber": null
                    },
                    "date": null,
                    "discount": null,
                    "unitOfMeasure": null,
                    "imageUrl": null
                }
            ],
            "currencyCode": null,
            "invoiceDate": "2016-12-02 PST",
            "invoiceDateTime": null,
            "paymentTerm": {
                "termType": "NET_45",
                "dueDate": "2017-01-16 PST"
            },
            "discount": null,
            "custom": null,
            "taxCalculatedAfterDiscount": false,
            "taxInclusive": false,
            "terms": null,
            "note": "Nasa Training Shuttles Invoice December 2, 2016",
            "merchantMemo": null,
            "shipping": null,
            "logoUrl": "https://www.paypalobjects.com/webstatic/i/logo/rebrand/ppcom.svg",
            "totalAmount": {
                "currencyCode": "CAD",
                "value": "50.86"
            },
            "tip": null,
            "paidAmount": {
                "paypal": {
                    "currencyCode": "CAD",
                    "value": "50.86"
                },
                "other": null
            },
            "refundedAmount": null,
            "payments": [
                {
                    "type": "PAYPAL",
                    "transactionType": "SALE",
                    "note": null,
                    "date": "2016-12-02 09:04:06 PST",
                    "method": "PAYPAL",
                    "transactionId": "2T838725YP165101U",
                    "amount": {
                        "currencyCode": "CAD",
                        "value": "50.86"
                    }
                }
            ],
            "refunds": null,
            "metadata": {
                "createdDate": "2016-12-02 07:15:59 PST",
                "createdBy": null,
                "cancelledDate": null,
                "cancelledBy": null,
                "lastUpdatedDate": "2016-12-02 09:04:06 PST",
                "lastUpdatedBy": null,
                "firstSentDate": "2016-12-02 07:16:03 PST",
                "lastSentDate": "2016-12-02 07:16:03 PST",
                "lastSentBy": null,
                "payerViewUrl": null
            },
            "referrerCode": null,
            "additionalData": null,
            "allowPartialPayments": null,
            "minimumAmountDue": null,
            "attachments": null,
            "links": [
                {
                    "rel": "self",
                    "href": "https://api.sandbox.paypal.com/v1/invoicing/invoices/INV2-38HD-4UKV-RX2E-EEAT",
                    "method": "GET"
                }
            ]
        }
    },
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-37J41080EA804702L-8YX90722YV0026639",
            "rel": "self",
            "method": "GET"
        },
        {
            "href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-37J41080EA804702L-8YX90722YV0026639/resend",
            "rel": "resend",
            "method": "POST"
        }
    ]
}`

**Comment by pp-randy** [comment] 2016-12-02 21:33
I will use https://github.com/paypal/PayPal-PHP-SDK/issues/704 to track sandbox invoice webhooks not validating. 

Closing this issue since it has been confirmed that Webhooks from the Webhook Simulator (not simulated from API) are not able to be validated.

**Closed by pp-randy** 2016-12-02 21:33 UTC
Labels: api-webhooks, question

**Comment by pp-randy** [comment] 2016-12-02 22:42
Also @webface thank you for all the help with both of these issues.
