### ISSUE TITLE
Billing Agreement API does not return id?

### ISSUE THREAD

**Issue by dannyvankooten** [paypal/PayPal-PHP-SDK#733] opened 2016-11-30 19:08 UTC
### Required Information

- PHP Version: 7.0.8
- PayPal-PHP-SDK Version: 1.10.0
- Debug ID(s): 

### Issue Description
The billing agreement API no longer returns an `id` property after creating an agreement. Therefore, `Agreement::getId()` always returns `null`.

https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_create_response

Documentation states an `id` should be responded with on the left side, but the example response (on the right side of the page) does not reflect this.

I can't see how anyone would build anything useful without the `id` parameter though.

**Comment by bluk** [comment] 2016-11-30 19:49
@dannyvankooten This is a duplicate of https://github.com/paypal/PayPal-node-SDK/issues/215 I believe. If you believe it is not, please leave a comment and we can reopen. Thanks!

**Closed by bluk** 2016-11-30 19:49 UTC
