### ISSUE TITLE
substr_compare(): The start position cannot exceed initial string length

### ISSUE THREAD

**Issue by waiylgeek** [paypal/PayPal-PHP-SDK#333] opened 2015-06-22 17:41 UTC
When I click the buy button I get this error: `substr_compare(): The start position cannot exceed initial string length`

NB: I'm running the app from `localhost` and I don't have `SSL`. But I don't think the issue is coming from here!

![screenshot from 2015-06-22 17 38 56](https://cloud.githubusercontent.com/assets/4692358/8288577/f45a084a-190e-11e5-8fd5-7022ba1d5d01.png)

You may need to view my code. Here it is:

```	
public function postPayment()
	{
		$payer = new Payer();
		$payer->setPaymentMethod('paypal');
		
		$app_price = 99;

		$item_1 = new Item();
		$item_1
		->setName('Cellphones Store E-commerce Application')
		->setCurrency('USD')
		->setQuantity(2)
		->setPrice($app_price);

		$item_list = new ItemList();
		$item_list->setItems([$item_1]);

		$amount = new Amount();
		$amount->setCurrency('USD')
		->setTotal($app_price);

		$transaction = new Transaction();
		$transaction->setAmount($amount)
		->setItemList($item_list)
		->setDescription('Transaction description');

		$redirect_urls = new RedirectUrls();
		$redirect_urls->setReturnUrl(URL::route('payment.status'))
		->setCancelUrl(URL::route('payment.status'));

		$payment = new Payment();
		$payment->setIntent('Sale')
		->setPayer($payer)
		->setRedirectUrls($redirect_urls)
		->setTransactions(array($transaction));

		try {
			$payment->create($this->_api_context);
		} catch (\PayPal\Exception\PPConnectionException $ex) {
			if (\Config::get('app.debug')) {
				echo "Exception: " . $ex->getMessage() . PHP_EOL;
				$err_data = json_decode($ex->getData(), true);
				exit;
			} else {
				die('Some error occur, sorry for inconvenient');
			}
		}

		foreach($payment->getLinks() as $link) {
			if($link->getRel() == 'approval_url') {
				$redirect_url = $link->getHref();
				break;
			}
		}

    // add payment ID to session
		Session::put('paypal_payment_id', $payment->getId());

		if(isset($redirect_url)) {
        // redirect to paypal
			return Redirect::away($redirect_url);
		}

		return Redirect::route('checkout.index')
		->with('error', 'Unknown error occurred');
	}
```

**Comment by jaypatel512** [comment] 2015-06-22 17:54
Hey @waiylgeek !

First of all, I think you need to get the SSL enabled. 

However, currently the issue is because the $sslVersion is empty, it fails on wrong string length. To resolve that, can you please see if you could manually modify the above file to something like this: 

```php
if (!empty($sslVersion) && substr_compare($sslVersion, "NSS/", 0, strlen("NSS/")) === 0) {
            //Remove the Cipher List for NSS
            $this->removeCurlOption(CURLOPT_SSL_CIPHER_LIST);
        }

```

If it works fine, let me know, and I should be able to make a fix for it. 

Thanks.

**Comment by waiylgeek** [comment] 2015-06-22 18:31
Thank you for your quick response @jaypatel512 I replaced the code with the one you gave me, I'm no longer getting the `substr_compare()` exception, but I'm getting this now `Protocol https not supported or disabled in libcurl` which clearly means that I need SSL installed on my machine. I will get SSL and test and get back to you again!

However, can't I disable the SSL exception I just need to test my code if it works?

Thanks.

**Comment by jaypatel512** [comment] 2015-06-22 18:34
You wont be able to make calls to PayPal APIs, without having SSL installed. However, if you are using a conventional machine, setting up ssl is extremely easy. 

You must be able to enabled openssl by uncommenting `extension=php_openssl.dll` in your php.ini.

**Comment by waiylgeek** [comment] 2015-06-22 19:26
Perfect, thanks for your help! I will install SSL and then if any error or any inconvenience occur I will let you know.

Thanks!

**Comment by jaypatel512** [comment] 2015-06-22 19:26
Sounds great :)

**Comment by jaypatel512** [comment] 2015-06-22 19:40
Btw, I will close the issue for now. However, feel free to re-open or comment if the issue doesnt get resolved.

**Closed by jaypatel512** 2015-06-22 19:40 UTC
Labels: question, sdk-bug
