### ISSUE TITLE
Getting some errors today: 'ReflectionException' with message 'Method PayPal\Api\Sale::getTransactionFee() does not exist' in paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PPReflectionUtil.php:73

### ISSUE THREAD

**Issue by jasonsavard** [paypal/PayPal-PHP-SDK#255] opened 2015-02-26 13:07 UTC
I've been successfully using PayPal for payments for months now and this happened all of sudden today, here's the tracelog

Thu, 26 Feb 2015 01:53:20 exception 'ReflectionException' with message 'Method PayPal\Api\Sale::getTransactionFee() does not exist' in /home/dsinnig/websites/apps.jasonsavard.com/paymentSystems/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PPReflectionUtil.php:73
Stack trace:
#0 /home/dsinnig/websites/apps.jasonsavard.com/paymentSystems/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PPReflectionUtil.php(73): ReflectionMethod->__construct('PayPal\Api\Sale', 'getTransactionF...')
#1 /home/dsinnig/websites/apps.jasonsavard.com/paymentSystems/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PPReflectionUtil.php(38): PayPal\Common\PPReflectionUtil::propertyAnnotations('PayPal\Api\Sale', 'transaction_fee')
#2 /home/dsinnig/websites/apps.jasonsavard.com/paymentSystems/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PPModel.php(157): PayPal\Common\PPReflectionUtil::getPropertyClass('PayPal\Api\Sale', 'transaction_fee')
#3 /home/dsinnig/websites/apps.jasonsavard.com/paymentSystems/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PPModel.php(161): PayPal\Common\PPModel->fromArray(Array)
#4 /home/dsinnig/websites/apps.jasonsavard.com/paymentSystems/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PPModel.php(168): PayPal\Common\PPModel->fromArray(Array)
#5 /home/dsinnig/websites/apps.jasonsavard.com/paymentSystems/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PPModel.php(168): PayPal\Common\PPModel->fromArray(Array)
#6 /home/dsinnig/websites/apps.jasonsavard.com/paymentSystems/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PPModel.php(202): PayPal\Common\PPModel->fromArray(Array)
#7 /home/dsinnig/websites/apps.jasonsavard.com/paymentSystems/paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php(463): PayPal\Common\PPModel->fromJson('{"id":"PAY-8SJ5...')
#8 /home/dsinnig/websites/apps.jasonsavard.com/paymentSystems/paypal/executePayment.php(48): PayPal\Api\Payment->execute(Object(PayPal\Api\PaymentExecution), Object(PayPal\Rest\ApiContext))
#9 {main}<br><br>Payment: {"id":"PAY-123","create_time":"2015-02-26T06:52:04Z","update_time":"2015-02-26T06:53:20Z","state":"approved","intent":"sale","payer":{"payment_method":"paypal","payer_info":{"email":"123@gmail.com","first_name":"abc","last_name":"def","payer_id":"123","shipping_address":{"line1":"1233-2","city":"Riga","state":"Riga","postal_code":"LV-1019","country_code":"LV","recipient_name":"123"}}},"transactions":[{"amount":{"total":"1.00","currency":"USD","details":{"subtotal":"1.00"}},"description":"Checker Plus for Gmail","item_list":{"items":[{"name":"Checker Plus for Gmail","price":"1.00","currency":"USD","quantity":"1"}]},"related_resources":[]}],"links":[{"href":"https://api.paypal.com/v1/payments/payment/PAY-123","rel":"self","method":"GET"},{"href":"https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-123","rel":"approval_url","method":"REDIRECT"},{"href":"https://api.paypal.com/v1/payments/payment/PAY-123/execute","rel":"execute","method":"POST"}]} niceError:  php_self: /paymentSystems/paypal/executePayment.php post parameters: []

**Comment by jasonsavard** [comment] 2015-02-26 13:27
sorry, it seems my API might need some upgrading, investigating currently and will report back here...

**Comment by jziaja** [comment] 2015-02-26 14:10
@jasonsavard , please try the [latest 1.2.1](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.2.1) release that @jaypatel512 released a couple days ago.  Hopefully that should get your app working again.  Just a heads up - it'll still log a warning indicating that it's missing a `transaction_fee` getter & setter.  We're currently working to resolve this (see [this related issue on the Ruby SDK](https://github.com/paypal/PayPal-Ruby-SDK/issues/14#issuecomment-75602853) for more information).

Out of curiosity, are you able to see the newer `transaction_fee` field on sandbox as well?

**Comment by jasonsavard** [comment] 2015-02-26 14:16
I'm embarrassed to say I haven't setup the sandbox version just the live one. But thank you for replying I have just updated the API and it's working again.

To avoid this issue in the future how can I subscribe to notifications/emails of updates for minor/major code changes to the PHP SDK? https://github.com/paypal/PayPal-PHP-SDK/releases

**Comment by jziaja** [comment] 2015-02-26 14:28
No worries!  Our team is in the opposite boat, where we do all of our testing on sandbox.  However, the API on sandbox hasn't been updated yet, making it very difficult for our team to update the SDK.  That issue has been escalated internally.

> To avoid this issue in the future how can I subscribe to notifications/emails of updates for minor/major code changes to the PHP SDK? https://github.com/paypal/PayPal-PHP-SDK/releases

At the top of the repo, click the [Watch button](https://help.github.com/articles/watching-repositories/) and it'll send you notifications of issues and PRs as they're created and responded to, as well as notifications of when new releases are made available. :)

**Comment by platformoperations** [comment] 2015-02-26 14:29
Hey,

It looks like its not working on v0.13.2 SDK version as well. Can you look into that please?

Thanks,
B.

**Comment by jziaja** [comment] 2015-02-26 14:31
@platformoperations , are you able to upgrade to the latest version [1.2.1](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.2.1)?

**Comment by jfordhay** [comment] 2015-02-26 15:19
@jziaja we too were affected by this issue this morning, but upgrading the SDK resolved the issue.  Was there some sort of API deprecation we should have been aware of that caused this?  If so, where can we find that information in the future?

**Comment by jaypatel512** [comment] 2015-02-26 15:25
Hey @jfordhay ! The issue was caused by new fields that were released on live/sandbox recently, with newer fields. Originally, the SDK was designed to withstand future additions. However, it was not equipped to handle the case where an object was added.

E.g. SDK could handle a new field like this:
```
{
   "old_fields":"old_values"
    ...
    "new_field": "new_value" 
    ...
}
```

However, it was not equipped to handle this:
```
{
   "old_fields":"old_values"
    ...
    "new_object": {
          "new_field":"new_value"
    }
    ...
}
```

The latest release has a fix for this now, and so, it would be future proof. Any new additions that any API might do should be handled properly by SDK now. It was indeed an oversight on SDK capabilities to handle future changes to APIs. However, this has been fixed now, and should not likely happen again.

**Comment by jfordhay** [comment] 2015-02-26 15:29
@jaypatel512 thank you for the explanation, much appreciated!

**Comment by nathanwelch** [comment] 2015-02-26 17:46
@jaypatel512 To be clear, does this mean upgrading to 1.2.1 is required?

**Comment by jaypatel512** [comment] 2015-02-26 17:49
Hey @nathanwelch ! Unfortunately yes. I have updated the latest release to have the fix that will accept any future changes gracefully, and would allow limiting any such future breaks. Apologies for the inconvenience. Also, there are few good features that have been added in last few releases that may be helpful to you.

However, if there is an absolute blockage that would not allow you to update (which should be fairly easy if you are already on 1.* release), let me know and I would love to help you resolve any issues/conflicts. Again, this was an unplanned break in SDK, and we are trying our best in resolving the issue. :) 

Thanks.

**Comment by platformoperations** [comment] 2015-02-26 17:58
@jziaja After upgrade to SDK **1.2.1** we started struggling with connection issues. 

After short investigation we found php curl library needs to be upgraded as to at least version **>=7.30.0** in order to properly handle **CURLINFO_HEADER_SIZE**.used by **1.2.1**. 

Now, in the meantime, before we look into possibility to upgrade to proper curl version, we found a workaround and manually applied a patch inside SDK, we changed  

    $responseHeaderSize = curl_getinfo($ch, CURLINFO_HEADER_SIZE);

to

    $responseHeaderSize = strlen($result) - curl_getinfo($ch, CURLINFO_SIZE_DOWNLOAD);

Looking into composer dependencies, there is no explicitly defined curl version required to use SDK.

Hope it helps,
B.

**Comment by jaypatel512** [comment] 2015-02-26 18:03
Hey @platformoperations ! Thats amazing you have already found a work around to the curl issue. I agree. If not absolutely required, we dont want to set minimum limits to curl version. I will definitely look into this issue, and update the SDK if required to keep the curl version to lower versions. 

Thanks for that. Definitely helps.

**Comment by dannetstudio** [comment] 2015-02-26 19:37
I think its increible that paypal launches an SDK update that causes problems with the previous installed versions (although these versions are very recent), making payments through paypal in production environments fail.

I found that "I may upgrade" just by calls from customers with errors in their payments, a bad way to notify about updates.

**Comment by jaypatel512** [comment] 2015-02-26 21:49
Hey @dannetstudio ! I completely understand about the short notice. The issue was caused by new fields that were released on live/sandbox recently, with newer fields in Payment APIs. Originally, the SDK was designed to withstand future additions. However, it was not equipped to handle the case where an object was added.

E.g. SDK could handle a new field like this:
```
{
   "old_fields":"old_values"
    ...
    "new_field": "new_value" 
    ...
}
```

However, it was not equipped to handle this:
```
{
   "old_fields":"old_values"
    ...
    "new_object": {
          "new_field":"new_value"
    }
    ...
}
```

The latest release has a fix for this now, and so, it would be future proof. Any new additions that any API might do should be handled properly by SDK now. It was indeed an oversight on SDK capabilities to handle future changes to APIs. However, this has been fixed now, and should not likely happen again.

**Comment by geel9** [comment] 2015-02-26 22:19
How in the hell can you possibly justify breaking anyone not running a completely up to date version?

**Comment by dannetstudio** [comment] 2015-02-26 23:21
Hi jaypatel512, thanks for your reply! I complety understand.

Do you know if the error "Call to undefined method PayPal\Api\CreditCard::setExpire_month" is also related with this api update? it seems like the setExpire_month class / function is not available in new API version, and Im getting that error trying to save a credit card in vault.

Thanks in advance!

**Comment by jaypatel512** [comment] 2015-02-26 23:24
Hey @dannetstudio ! The issue is because of the removal of deprecated methods. We moved from methods having `_` in the name. Each Method could be used with Camel Case. Here is the list of all [breaking changes in 1.0.0](https://github.com/paypal/PayPal-PHP-SDK/wiki/Breaking-Changes---1.0.0).

You could easily fix that issue by calling `setExpireMonth` instead of `setExpire_month` and you should be good to go. :)

**Comment by jaypatel512** [comment] 2015-02-26 23:29
Btw, I will be trying to respond to any issues you or anyone may have related to this bug as soon as possible. I will respond to all the issues as fast as I could to reduce the impact you may have on your live environment. Please create an issue on github, and I will respond them. I apologize again for the oversight.

I understand that the need for updating the SDK is unjustified to some extent, but considering the bug, the fastest and best solution to it is to update to the latest SDK.

**Comment by guillermog** [comment] 2015-02-27 02:26
Hi, we had the same Capture::getTransactionFee() issue but were able to resolve it by updating the SDK to latest version. Everything seemed to be working for a while but now we keep getting this new error:

Fatal error: Uncaught exception 'PayPal\Exception\PayPalConnectionException' with message 'Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment/PAY-5UP82391BC107934PKTX5AAI/execute.' in /home/theoffic/public_html/tssc/secure/checkout/payments/Paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:176 Stack trace: #0 /home/theoffic/public_html/tssc/secure/checkout/payments/Paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(74): PayPal\Core\PayPalHttpConnection->execute('{"payer_id":"JY...') #1 /home/theoffic/public_html/tssc/secure/checkout/payments/Paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(103): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/pa...', 'POST', '{"payer_id":"JY...', NULL) #2 /home/theoffic/public_html/tssc/secure/checkout/payments/Paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php(379): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/pa...', 'POST', in /home/theoffic/public_html/tssc/secure/checkout/payments/Paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php on line 176

any ideas?

**Comment by jaypatel512** [comment] 2015-02-27 03:14
One good news is, the exception is from the server, and not the SDK. So, your SDK upgrade went successful. Can you please post the logs if you have it enabled. If not, you could catch the PayPalConnectionException, and print the crucial data as follows:

```php
try {

    $payment->execute(...);

// Catch at PayPalConnectionException Level
} catch (\PayPal\Exception\PayPalConnectionException $ex) {
    echo $ex->getData();
}
```

This should give you the exact message about why it is throwing this error.

Thanks.

**Comment by guillermog** [comment] 2015-02-27 11:23
@jaypatel512  thank you for your suggestion, but it is so weird because I went to try it today, and everything seemed to be working correctly. We did not get any errors. I'll keep an eye out for it, in case it happens again, and will try to catch the error info as you suggested.

Thanks.

**Comment by jaypatel512** [comment] 2015-02-27 22:59
Hello Everyone! I just wanted to update you all on the newer release. I have just completed the [release](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.3.0) that includes Payment API Updates that covers all the new additional fields that Payment API introduced. You should be able to quickly update your setup to this version to get rid of all those missing accessors issue.

Please checkout the release at https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.3.0

**Closed by jaypatel512** 2015-02-27 22:59 UTC
Labels: api-payments, sdk-bug

**Comment by raghucodingbrains** [comment] 2016-05-13 18:19
same error as stated by @guillermog

**Comment by jaypatel512** [comment] 2016-05-13 18:21
Please make sure to follow instructions on comments below them, and find the actual error message. Also, always good to update to latest version.
