### ISSUE TITLE
New checkout paypal

### ISSUE THREAD

**Issue by adnan-adiatman** [paypal/PayPal-PHP-SDK#419] opened 2015-10-12 09:27 UTC
in live is the product description on a subscription will appear like this?

![drobbox subscription](http://i.imgur.com/kp5Ryfn.png)

or how to make it look like?

**Comment by jaypatel512** [comment] 2015-10-12 15:32
Duplicate of https://github.com/paypal/PayPal-PHP-SDK/issues/149

**Closed by jaypatel512** 2015-10-12 15:32 UTC
