### ISSUE TITLE
Can't receive PayerID after creating billing agreement

### ISSUE THREAD

**Issue by vovanushka** [paypal/PayPal-PHP-SDK#280] opened 2015-04-02 14:18 UTC
I'm using rest api and billing plans for recurring payments in my system.
I have a problem with comparing agreements and users.
After finishing agreement on paypall page, user returns to my return url, but paypal sending only Token GET parameter on it. In simple payments I had PayerID parameter, wich I've used for users. I also tried to get PayerId after agreement executing but paypal returns emtpy Payer object, in agreement.
It's bug or feature?
It's important for me, because I'm using IPN to track transaction.
Maybe there is another way to identify user, using IPN?

**Comment by jaypatel512** [comment] 2015-04-02 15:08
Duplicate of #155

**Closed by jaypatel512** 2015-04-02 15:08 UTC
